<?php

namespace Cms\Orm\Mail\Definition;

/**
 * @method \Cms\Orm\Mail\Definition\Query equals($value)
 * @method \Cms\Orm\Mail\Definition\Query notEquals($value)
 * @method \Cms\Orm\Mail\Definition\Query greater($value)
 * @method \Cms\Orm\Mail\Definition\Query less($value)
 * @method \Cms\Orm\Mail\Definition\Query greaterOrEquals($value)
 * @method \Cms\Orm\Mail\Definition\Query lessOrEquals($value)
 * @method \Cms\Orm\Mail\Definition\Query like($value)
 * @method \Cms\Orm\Mail\Definition\Query ilike($value)
 * @method \Cms\Orm\Mail\Definition\Query equalsColumnId()
 * @method \Cms\Orm\Mail\Definition\Query notEqualsColumnId()
 * @method \Cms\Orm\Mail\Definition\Query greaterThanColumnId()
 * @method \Cms\Orm\Mail\Definition\Query lessThanColumnId()
 * @method \Cms\Orm\Mail\Definition\Query greaterOrEqualsColumnId()
 * @method \Cms\Orm\Mail\Definition\Query lessOrEqualsColumnId()
 * @method \Cms\Orm\Mail\Definition\Query equalsColumnLang()
 * @method \Cms\Orm\Mail\Definition\Query notEqualsColumnLang()
 * @method \Cms\Orm\Mail\Definition\Query greaterThanColumnLang()
 * @method \Cms\Orm\Mail\Definition\Query lessThanColumnLang()
 * @method \Cms\Orm\Mail\Definition\Query greaterOrEqualsColumnLang()
 * @method \Cms\Orm\Mail\Definition\Query lessOrEqualsColumnLang()
 * @method \Cms\Orm\Mail\Definition\Query equalsColumnCmsMailServerId()
 * @method \Cms\Orm\Mail\Definition\Query notEqualsColumnCmsMailServerId()
 * @method \Cms\Orm\Mail\Definition\Query greaterThanColumnCmsMailServerId()
 * @method \Cms\Orm\Mail\Definition\Query lessThanColumnCmsMailServerId()
 * @method \Cms\Orm\Mail\Definition\Query greaterOrEqualsColumnCmsMailServerId()
 * @method \Cms\Orm\Mail\Definition\Query lessOrEqualsColumnCmsMailServerId()
 * @method \Cms\Orm\Mail\Definition\Query equalsColumnName()
 * @method \Cms\Orm\Mail\Definition\Query notEqualsColumnName()
 * @method \Cms\Orm\Mail\Definition\Query greaterThanColumnName()
 * @method \Cms\Orm\Mail\Definition\Query lessThanColumnName()
 * @method \Cms\Orm\Mail\Definition\Query greaterOrEqualsColumnName()
 * @method \Cms\Orm\Mail\Definition\Query lessOrEqualsColumnName()
 * @method \Cms\Orm\Mail\Definition\Query equalsColumnReplyTo()
 * @method \Cms\Orm\Mail\Definition\Query notEqualsColumnReplyTo()
 * @method \Cms\Orm\Mail\Definition\Query greaterThanColumnReplyTo()
 * @method \Cms\Orm\Mail\Definition\Query lessThanColumnReplyTo()
 * @method \Cms\Orm\Mail\Definition\Query greaterOrEqualsColumnReplyTo()
 * @method \Cms\Orm\Mail\Definition\Query lessOrEqualsColumnReplyTo()
 * @method \Cms\Orm\Mail\Definition\Query equalsColumnFromName()
 * @method \Cms\Orm\Mail\Definition\Query notEqualsColumnFromName()
 * @method \Cms\Orm\Mail\Definition\Query greaterThanColumnFromName()
 * @method \Cms\Orm\Mail\Definition\Query lessThanColumnFromName()
 * @method \Cms\Orm\Mail\Definition\Query greaterOrEqualsColumnFromName()
 * @method \Cms\Orm\Mail\Definition\Query lessOrEqualsColumnFromName()
 * @method \Cms\Orm\Mail\Definition\Query equalsColumnSubject()
 * @method \Cms\Orm\Mail\Definition\Query notEqualsColumnSubject()
 * @method \Cms\Orm\Mail\Definition\Query greaterThanColumnSubject()
 * @method \Cms\Orm\Mail\Definition\Query lessThanColumnSubject()
 * @method \Cms\Orm\Mail\Definition\Query greaterOrEqualsColumnSubject()
 * @method \Cms\Orm\Mail\Definition\Query lessOrEqualsColumnSubject()
 * @method \Cms\Orm\Mail\Definition\Query equalsColumnMessage()
 * @method \Cms\Orm\Mail\Definition\Query notEqualsColumnMessage()
 * @method \Cms\Orm\Mail\Definition\Query greaterThanColumnMessage()
 * @method \Cms\Orm\Mail\Definition\Query lessThanColumnMessage()
 * @method \Cms\Orm\Mail\Definition\Query greaterOrEqualsColumnMessage()
 * @method \Cms\Orm\Mail\Definition\Query lessOrEqualsColumnMessage()
 * @method \Cms\Orm\Mail\Definition\Query equalsColumnHtml()
 * @method \Cms\Orm\Mail\Definition\Query notEqualsColumnHtml()
 * @method \Cms\Orm\Mail\Definition\Query greaterThanColumnHtml()
 * @method \Cms\Orm\Mail\Definition\Query lessThanColumnHtml()
 * @method \Cms\Orm\Mail\Definition\Query greaterOrEqualsColumnHtml()
 * @method \Cms\Orm\Mail\Definition\Query lessOrEqualsColumnHtml()
 * @method \Cms\Orm\Mail\Definition\Query equalsColumnDateAdd()
 * @method \Cms\Orm\Mail\Definition\Query notEqualsColumnDateAdd()
 * @method \Cms\Orm\Mail\Definition\Query greaterThanColumnDateAdd()
 * @method \Cms\Orm\Mail\Definition\Query lessThanColumnDateAdd()
 * @method \Cms\Orm\Mail\Definition\Query greaterOrEqualsColumnDateAdd()
 * @method \Cms\Orm\Mail\Definition\Query lessOrEqualsColumnDateAdd()
 * @method \Cms\Orm\Mail\Definition\Query equalsColumnDateModify()
 * @method \Cms\Orm\Mail\Definition\Query notEqualsColumnDateModify()
 * @method \Cms\Orm\Mail\Definition\Query greaterThanColumnDateModify()
 * @method \Cms\Orm\Mail\Definition\Query lessThanColumnDateModify()
 * @method \Cms\Orm\Mail\Definition\Query greaterOrEqualsColumnDateModify()
 * @method \Cms\Orm\Mail\Definition\Query lessOrEqualsColumnDateModify()
 * @method \Cms\Orm\Mail\Definition\Query equalsColumnActive()
 * @method \Cms\Orm\Mail\Definition\Query notEqualsColumnActive()
 * @method \Cms\Orm\Mail\Definition\Query greaterThanColumnActive()
 * @method \Cms\Orm\Mail\Definition\Query lessThanColumnActive()
 * @method \Cms\Orm\Mail\Definition\Query greaterOrEqualsColumnActive()
 * @method \Cms\Orm\Mail\Definition\Query lessOrEqualsColumnActive()
 */
class QueryField extends \Mmi\Orm\QueryField {

}
