<?php

namespace Cms\Orm;

//<editor-fold defaultstate="collapsed" desc="CmsAttributeRelationQuery">
/**
 * @method CmsAttributeRelationQuery limit($limit = null)
 * @method CmsAttributeRelationQuery offset($offset = null)
 * @method CmsAttributeRelationQuery orderAsc($fieldName, $tableName = null)
 * @method CmsAttributeRelationQuery orderDesc($fieldName, $tableName = null)
 * @method CmsAttributeRelationQuery andQuery(\Mmi\Orm\Query $query)
 * @method CmsAttributeRelationQuery whereQuery(\Mmi\Orm\Query $query)
 * @method CmsAttributeRelationQuery orQuery(\Mmi\Orm\Query $query)
 * @method CmsAttributeRelationQuery resetOrder()
 * @method CmsAttributeRelationQuery resetWhere()
 * @method QueryHelper\CmsAttributeRelationQueryField whereId()
 * @method QueryHelper\CmsAttributeRelationQueryField andFieldId()
 * @method QueryHelper\CmsAttributeRelationQueryField orFieldId()
 * @method CmsAttributeRelationQuery orderAscId()
 * @method CmsAttributeRelationQuery orderDescId()
 * @method CmsAttributeRelationQuery groupById()
 * @method QueryHelper\CmsAttributeRelationQueryField whereCmsAttributeId()
 * @method QueryHelper\CmsAttributeRelationQueryField andFieldCmsAttributeId()
 * @method QueryHelper\CmsAttributeRelationQueryField orFieldCmsAttributeId()
 * @method CmsAttributeRelationQuery orderAscCmsAttributeId()
 * @method CmsAttributeRelationQuery orderDescCmsAttributeId()
 * @method CmsAttributeRelationQuery groupByCmsAttributeId()
 * @method QueryHelper\CmsAttributeRelationQueryField whereCmsAttributeValueId()
 * @method QueryHelper\CmsAttributeRelationQueryField andFieldCmsAttributeValueId()
 * @method QueryHelper\CmsAttributeRelationQueryField orFieldCmsAttributeValueId()
 * @method CmsAttributeRelationQuery orderAscCmsAttributeValueId()
 * @method CmsAttributeRelationQuery orderDescCmsAttributeValueId()
 * @method CmsAttributeRelationQuery groupByCmsAttributeValueId()
 * @method QueryHelper\CmsAttributeRelationQueryField whereFilterClasses()
 * @method QueryHelper\CmsAttributeRelationQueryField andFieldFilterClasses()
 * @method QueryHelper\CmsAttributeRelationQueryField orFieldFilterClasses()
 * @method CmsAttributeRelationQuery orderAscFilterClasses()
 * @method CmsAttributeRelationQuery orderDescFilterClasses()
 * @method CmsAttributeRelationQuery groupByFilterClasses()
 * @method QueryHelper\CmsAttributeRelationQueryField whereValidatorClasses()
 * @method QueryHelper\CmsAttributeRelationQueryField andFieldValidatorClasses()
 * @method QueryHelper\CmsAttributeRelationQueryField orFieldValidatorClasses()
 * @method CmsAttributeRelationQuery orderAscValidatorClasses()
 * @method CmsAttributeRelationQuery orderDescValidatorClasses()
 * @method CmsAttributeRelationQuery groupByValidatorClasses()
 * @method QueryHelper\CmsAttributeRelationQueryField whereRequired()
 * @method QueryHelper\CmsAttributeRelationQueryField andFieldRequired()
 * @method QueryHelper\CmsAttributeRelationQueryField orFieldRequired()
 * @method CmsAttributeRelationQuery orderAscRequired()
 * @method CmsAttributeRelationQuery orderDescRequired()
 * @method CmsAttributeRelationQuery groupByRequired()
 * @method QueryHelper\CmsAttributeRelationQueryField whereUnique()
 * @method QueryHelper\CmsAttributeRelationQueryField andFieldUnique()
 * @method QueryHelper\CmsAttributeRelationQueryField orFieldUnique()
 * @method CmsAttributeRelationQuery orderAscUnique()
 * @method CmsAttributeRelationQuery orderDescUnique()
 * @method CmsAttributeRelationQuery groupByUnique()
 * @method QueryHelper\CmsAttributeRelationQueryField whereMaterialized()
 * @method QueryHelper\CmsAttributeRelationQueryField andFieldMaterialized()
 * @method QueryHelper\CmsAttributeRelationQueryField orFieldMaterialized()
 * @method CmsAttributeRelationQuery orderAscMaterialized()
 * @method CmsAttributeRelationQuery orderDescMaterialized()
 * @method CmsAttributeRelationQuery groupByMaterialized()
 * @method QueryHelper\CmsAttributeRelationQueryField whereObject()
 * @method QueryHelper\CmsAttributeRelationQueryField andFieldObject()
 * @method QueryHelper\CmsAttributeRelationQueryField orFieldObject()
 * @method CmsAttributeRelationQuery orderAscObject()
 * @method CmsAttributeRelationQuery orderDescObject()
 * @method CmsAttributeRelationQuery groupByObject()
 * @method QueryHelper\CmsAttributeRelationQueryField whereObjectId()
 * @method QueryHelper\CmsAttributeRelationQueryField andFieldObjectId()
 * @method QueryHelper\CmsAttributeRelationQueryField orFieldObjectId()
 * @method CmsAttributeRelationQuery orderAscObjectId()
 * @method CmsAttributeRelationQuery orderDescObjectId()
 * @method CmsAttributeRelationQuery groupByObjectId()
 * @method QueryHelper\CmsAttributeRelationQueryField whereOrder()
 * @method QueryHelper\CmsAttributeRelationQueryField andFieldOrder()
 * @method QueryHelper\CmsAttributeRelationQueryField orFieldOrder()
 * @method CmsAttributeRelationQuery orderAscOrder()
 * @method CmsAttributeRelationQuery orderDescOrder()
 * @method CmsAttributeRelationQuery groupByOrder()
 * @method QueryHelper\CmsAttributeRelationQueryField andField($fieldName, $tableName = null)
 * @method QueryHelper\CmsAttributeRelationQueryField where($fieldName, $tableName = null)
 * @method QueryHelper\CmsAttributeRelationQueryField orField($fieldName, $tableName = null)
 * @method QueryHelper\CmsAttributeRelationQueryJoin join($tableName, $targetTableName = null, $alias = null)
 * @method QueryHelper\CmsAttributeRelationQueryJoin joinLeft($tableName, $targetTableName = null, $alias = null)
 * @method CmsAttributeRelationRecord[] find()
 * @method CmsAttributeRelationRecord findFirst()
 * @method CmsAttributeRelationRecord findPk($value)
 */
//</editor-fold>
class CmsAttributeRelationQuery extends \Mmi\Orm\Query {

	protected $_tableName = 'cms_attribute_relation';

}