<?php

namespace Cms\Orm;

//<editor-fold defaultstate="collapsed" desc="CmsAttributeGroupAttributeQuery">
/**
 * @method CmsAttributeGroupAttributeQuery limit($limit = null)
 * @method CmsAttributeGroupAttributeQuery offset($offset = null)
 * @method CmsAttributeGroupAttributeQuery orderAsc($fieldName, $tableName = null)
 * @method CmsAttributeGroupAttributeQuery orderDesc($fieldName, $tableName = null)
 * @method CmsAttributeGroupAttributeQuery andQuery(\Mmi\Orm\Query $query)
 * @method CmsAttributeGroupAttributeQuery whereQuery(\Mmi\Orm\Query $query)
 * @method CmsAttributeGroupAttributeQuery orQuery(\Mmi\Orm\Query $query)
 * @method CmsAttributeGroupAttributeQuery resetOrder()
 * @method CmsAttributeGroupAttributeQuery resetWhere()
 * @method QueryHelper\CmsAttributeGroupAttributeQueryField whereId()
 * @method QueryHelper\CmsAttributeGroupAttributeQueryField andFieldId()
 * @method QueryHelper\CmsAttributeGroupAttributeQueryField orFieldId()
 * @method CmsAttributeGroupAttributeQuery orderAscId()
 * @method CmsAttributeGroupAttributeQuery orderDescId()
 * @method CmsAttributeGroupAttributeQuery groupById()
 * @method QueryHelper\CmsAttributeGroupAttributeQueryField whereCmsAttributeId()
 * @method QueryHelper\CmsAttributeGroupAttributeQueryField andFieldCmsAttributeId()
 * @method QueryHelper\CmsAttributeGroupAttributeQueryField orFieldCmsAttributeId()
 * @method CmsAttributeGroupAttributeQuery orderAscCmsAttributeId()
 * @method CmsAttributeGroupAttributeQuery orderDescCmsAttributeId()
 * @method CmsAttributeGroupAttributeQuery groupByCmsAttributeId()
 * @method QueryHelper\CmsAttributeGroupAttributeQueryField whereCmsAttributeGroupId()
 * @method QueryHelper\CmsAttributeGroupAttributeQueryField andFieldCmsAttributeGroupId()
 * @method QueryHelper\CmsAttributeGroupAttributeQueryField orFieldCmsAttributeGroupId()
 * @method CmsAttributeGroupAttributeQuery orderAscCmsAttributeGroupId()
 * @method CmsAttributeGroupAttributeQuery orderDescCmsAttributeGroupId()
 * @method CmsAttributeGroupAttributeQuery groupByCmsAttributeGroupId()
 * @method QueryHelper\CmsAttributeGroupAttributeQueryField whereRequired()
 * @method QueryHelper\CmsAttributeGroupAttributeQueryField andFieldRequired()
 * @method QueryHelper\CmsAttributeGroupAttributeQueryField orFieldRequired()
 * @method CmsAttributeGroupAttributeQuery orderAscRequired()
 * @method CmsAttributeGroupAttributeQuery orderDescRequired()
 * @method CmsAttributeGroupAttributeQuery groupByRequired()
 * @method QueryHelper\CmsAttributeGroupAttributeQueryField whereUnique()
 * @method QueryHelper\CmsAttributeGroupAttributeQueryField andFieldUnique()
 * @method QueryHelper\CmsAttributeGroupAttributeQueryField orFieldUnique()
 * @method CmsAttributeGroupAttributeQuery orderAscUnique()
 * @method CmsAttributeGroupAttributeQuery orderDescUnique()
 * @method CmsAttributeGroupAttributeQuery groupByUnique()
 * @method QueryHelper\CmsAttributeGroupAttributeQueryField whereMaterialized()
 * @method QueryHelper\CmsAttributeGroupAttributeQueryField andFieldMaterialized()
 * @method QueryHelper\CmsAttributeGroupAttributeQueryField orFieldMaterialized()
 * @method CmsAttributeGroupAttributeQuery orderAscMaterialized()
 * @method CmsAttributeGroupAttributeQuery orderDescMaterialized()
 * @method CmsAttributeGroupAttributeQuery groupByMaterialized()
 * @method QueryHelper\CmsAttributeGroupAttributeQueryField whereActive()
 * @method QueryHelper\CmsAttributeGroupAttributeQueryField andFieldActive()
 * @method QueryHelper\CmsAttributeGroupAttributeQueryField orFieldActive()
 * @method CmsAttributeGroupAttributeQuery orderAscActive()
 * @method CmsAttributeGroupAttributeQuery orderDescActive()
 * @method CmsAttributeGroupAttributeQuery groupByActive()
 * @method QueryHelper\CmsAttributeGroupAttributeQueryField andField($fieldName, $tableName = null)
 * @method QueryHelper\CmsAttributeGroupAttributeQueryField where($fieldName, $tableName = null)
 * @method QueryHelper\CmsAttributeGroupAttributeQueryField orField($fieldName, $tableName = null)
 * @method QueryHelper\CmsAttributeGroupAttributeQueryJoin join($tableName, $targetTableName = null, $alias = null)
 * @method QueryHelper\CmsAttributeGroupAttributeQueryJoin joinLeft($tableName, $targetTableName = null, $alias = null)
 * @method CmsAttributeGroupAttributeRecord[] find()
 * @method CmsAttributeGroupAttributeRecord findFirst()
 * @method CmsAttributeGroupAttributeRecord findPk($value)
 */
//</editor-fold>
class CmsAttributeGroupAttributeQuery extends \Mmi\Orm\Query {

	protected $_tableName = 'cms_attribute_group_attribute';

}