<?php

namespace Cms\Orm;

//<editor-fold defaultstate="collapsed" desc="CmsContactQuery">
/**
 * @method CmsContactQuery limit($limit = null)
 * @method CmsContactQuery offset($offset = null)
 * @method CmsContactQuery orderAsc($fieldName, $tableName = null)
 * @method CmsContactQuery orderDesc($fieldName, $tableName = null)
 * @method CmsContactQuery andQuery(\Mmi\Orm\Query $query)
 * @method CmsContactQuery whereQuery(\Mmi\Orm\Query $query)
 * @method CmsContactQuery orQuery(\Mmi\Orm\Query $query)
 * @method CmsContactQuery resetOrder()
 * @method CmsContactQuery resetWhere()
 * @method QueryHelper\CmsContactQueryField whereId()
 * @method QueryHelper\CmsContactQueryField andFieldId()
 * @method QueryHelper\CmsContactQueryField orFieldId()
 * @method CmsContactQuery orderAscId()
 * @method CmsContactQuery orderDescId()
 * @method CmsContactQuery groupById()
 * @method QueryHelper\CmsContactQueryField whereCmsContactOptionId()
 * @method QueryHelper\CmsContactQueryField andFieldCmsContactOptionId()
 * @method QueryHelper\CmsContactQueryField orFieldCmsContactOptionId()
 * @method CmsContactQuery orderAscCmsContactOptionId()
 * @method CmsContactQuery orderDescCmsContactOptionId()
 * @method CmsContactQuery groupByCmsContactOptionId()
 * @method QueryHelper\CmsContactQueryField whereDateAdd()
 * @method QueryHelper\CmsContactQueryField andFieldDateAdd()
 * @method QueryHelper\CmsContactQueryField orFieldDateAdd()
 * @method CmsContactQuery orderAscDateAdd()
 * @method CmsContactQuery orderDescDateAdd()
 * @method CmsContactQuery groupByDateAdd()
 * @method QueryHelper\CmsContactQueryField whereText()
 * @method QueryHelper\CmsContactQueryField andFieldText()
 * @method QueryHelper\CmsContactQueryField orFieldText()
 * @method CmsContactQuery orderAscText()
 * @method CmsContactQuery orderDescText()
 * @method CmsContactQuery groupByText()
 * @method QueryHelper\CmsContactQueryField whereReply()
 * @method QueryHelper\CmsContactQueryField andFieldReply()
 * @method QueryHelper\CmsContactQueryField orFieldReply()
 * @method CmsContactQuery orderAscReply()
 * @method CmsContactQuery orderDescReply()
 * @method CmsContactQuery groupByReply()
 * @method QueryHelper\CmsContactQueryField whereCmsAuthIdReply()
 * @method QueryHelper\CmsContactQueryField andFieldCmsAuthIdReply()
 * @method QueryHelper\CmsContactQueryField orFieldCmsAuthIdReply()
 * @method CmsContactQuery orderAscCmsAuthIdReply()
 * @method CmsContactQuery orderDescCmsAuthIdReply()
 * @method CmsContactQuery groupByCmsAuthIdReply()
 * @method QueryHelper\CmsContactQueryField whereUri()
 * @method QueryHelper\CmsContactQueryField andFieldUri()
 * @method QueryHelper\CmsContactQueryField orFieldUri()
 * @method CmsContactQuery orderAscUri()
 * @method CmsContactQuery orderDescUri()
 * @method CmsContactQuery groupByUri()
 * @method QueryHelper\CmsContactQueryField whereName()
 * @method QueryHelper\CmsContactQueryField andFieldName()
 * @method QueryHelper\CmsContactQueryField orFieldName()
 * @method CmsContactQuery orderAscName()
 * @method CmsContactQuery orderDescName()
 * @method CmsContactQuery groupByName()
 * @method QueryHelper\CmsContactQueryField wherePhone()
 * @method QueryHelper\CmsContactQueryField andFieldPhone()
 * @method QueryHelper\CmsContactQueryField orFieldPhone()
 * @method CmsContactQuery orderAscPhone()
 * @method CmsContactQuery orderDescPhone()
 * @method CmsContactQuery groupByPhone()
 * @method QueryHelper\CmsContactQueryField whereEmail()
 * @method QueryHelper\CmsContactQueryField andFieldEmail()
 * @method QueryHelper\CmsContactQueryField orFieldEmail()
 * @method CmsContactQuery orderAscEmail()
 * @method CmsContactQuery orderDescEmail()
 * @method CmsContactQuery groupByEmail()
 * @method QueryHelper\CmsContactQueryField whereIp()
 * @method QueryHelper\CmsContactQueryField andFieldIp()
 * @method QueryHelper\CmsContactQueryField orFieldIp()
 * @method CmsContactQuery orderAscIp()
 * @method CmsContactQuery orderDescIp()
 * @method CmsContactQuery groupByIp()
 * @method QueryHelper\CmsContactQueryField whereCmsAuthId()
 * @method QueryHelper\CmsContactQueryField andFieldCmsAuthId()
 * @method QueryHelper\CmsContactQueryField orFieldCmsAuthId()
 * @method CmsContactQuery orderAscCmsAuthId()
 * @method CmsContactQuery orderDescCmsAuthId()
 * @method CmsContactQuery groupByCmsAuthId()
 * @method QueryHelper\CmsContactQueryField whereActive()
 * @method QueryHelper\CmsContactQueryField andFieldActive()
 * @method QueryHelper\CmsContactQueryField orFieldActive()
 * @method CmsContactQuery orderAscActive()
 * @method CmsContactQuery orderDescActive()
 * @method CmsContactQuery groupByActive()
 * @method QueryHelper\CmsContactQueryField andField($fieldName, $tableName = null)
 * @method QueryHelper\CmsContactQueryField where($fieldName, $tableName = null)
 * @method QueryHelper\CmsContactQueryField orField($fieldName, $tableName = null)
 * @method QueryHelper\CmsContactQueryJoin join($tableName, $targetTableName = null)
 * @method QueryHelper\CmsContactQueryJoin joinLeft($tableName, $targetTableName = null)
 * @method CmsContactRecord[] find()
 * @method CmsContactRecord findFirst()
 * @method CmsContactRecord findPk($value)
 */
//</editor-fold>
class CmsContactQuery extends \Mmi\Orm\Query {

	protected $_tableName = 'cms_contact';

	/**
	 * @return CmsContactQuery
	 */
	public static function factory($tableName = null) {
		return new self($tableName);
	}

}
