<?php

namespace Cms\Orm;

//<editor-fold defaultstate="collapsed" desc="CmsCategoryQuery">
/**
 * @method CmsCategoryQuery limit($limit = null)
 * @method CmsCategoryQuery offset($offset = null)
 * @method CmsCategoryQuery orderAsc($fieldName, $tableName = null)
 * @method CmsCategoryQuery orderDesc($fieldName, $tableName = null)
 * @method CmsCategoryQuery andQuery(\Mmi\Orm\Query $query)
 * @method CmsCategoryQuery whereQuery(\Mmi\Orm\Query $query)
 * @method CmsCategoryQuery orQuery(\Mmi\Orm\Query $query)
 * @method CmsCategoryQuery resetOrder()
 * @method CmsCategoryQuery resetWhere()
 * @method QueryHelper\CmsCategoryQueryField whereId()
 * @method QueryHelper\CmsCategoryQueryField andFieldId()
 * @method QueryHelper\CmsCategoryQueryField orFieldId()
 * @method CmsCategoryQuery orderAscId()
 * @method CmsCategoryQuery orderDescId()
 * @method CmsCategoryQuery groupById()
 * @method QueryHelper\CmsCategoryQueryField whereLang()
 * @method QueryHelper\CmsCategoryQueryField andFieldLang()
 * @method QueryHelper\CmsCategoryQueryField orFieldLang()
 * @method CmsCategoryQuery orderAscLang()
 * @method CmsCategoryQuery orderDescLang()
 * @method CmsCategoryQuery groupByLang()
 * @method QueryHelper\CmsCategoryQueryField whereName()
 * @method QueryHelper\CmsCategoryQueryField andFieldName()
 * @method QueryHelper\CmsCategoryQueryField orFieldName()
 * @method CmsCategoryQuery orderAscName()
 * @method CmsCategoryQuery orderDescName()
 * @method CmsCategoryQuery groupByName()
 * @method QueryHelper\CmsCategoryQueryField whereDescription()
 * @method QueryHelper\CmsCategoryQueryField andFieldDescription()
 * @method QueryHelper\CmsCategoryQueryField orFieldDescription()
 * @method CmsCategoryQuery orderAscDescription()
 * @method CmsCategoryQuery orderDescDescription()
 * @method CmsCategoryQuery groupByDescription()
 * @method QueryHelper\CmsCategoryQueryField whereUri()
 * @method QueryHelper\CmsCategoryQueryField andFieldUri()
 * @method QueryHelper\CmsCategoryQueryField orFieldUri()
 * @method CmsCategoryQuery orderAscUri()
 * @method CmsCategoryQuery orderDescUri()
 * @method CmsCategoryQuery groupByUri()
 * @method QueryHelper\CmsCategoryQueryField whereCode()
 * @method QueryHelper\CmsCategoryQueryField andFieldCode()
 * @method QueryHelper\CmsCategoryQueryField orFieldCode()
 * @method CmsCategoryQuery orderAscCode()
 * @method CmsCategoryQuery orderDescCode()
 * @method CmsCategoryQuery groupByCode()
 * @method QueryHelper\CmsCategoryQueryField whereParentId()
 * @method QueryHelper\CmsCategoryQueryField andFieldParentId()
 * @method QueryHelper\CmsCategoryQueryField orFieldParentId()
 * @method CmsCategoryQuery orderAscParentId()
 * @method CmsCategoryQuery orderDescParentId()
 * @method CmsCategoryQuery groupByParentId()
 * @method QueryHelper\CmsCategoryQueryField whereOrder()
 * @method QueryHelper\CmsCategoryQueryField andFieldOrder()
 * @method QueryHelper\CmsCategoryQueryField orFieldOrder()
 * @method CmsCategoryQuery orderAscOrder()
 * @method CmsCategoryQuery orderDescOrder()
 * @method CmsCategoryQuery groupByOrder()
 * @method QueryHelper\CmsCategoryQueryField whereDateAdd()
 * @method QueryHelper\CmsCategoryQueryField andFieldDateAdd()
 * @method QueryHelper\CmsCategoryQueryField orFieldDateAdd()
 * @method CmsCategoryQuery orderAscDateAdd()
 * @method CmsCategoryQuery orderDescDateAdd()
 * @method CmsCategoryQuery groupByDateAdd()
 * @method QueryHelper\CmsCategoryQueryField whereDateModify()
 * @method QueryHelper\CmsCategoryQueryField andFieldDateModify()
 * @method QueryHelper\CmsCategoryQueryField orFieldDateModify()
 * @method CmsCategoryQuery orderAscDateModify()
 * @method CmsCategoryQuery orderDescDateModify()
 * @method CmsCategoryQuery groupByDateModify()
 * @method QueryHelper\CmsCategoryQueryField whereActive()
 * @method QueryHelper\CmsCategoryQueryField andFieldActive()
 * @method QueryHelper\CmsCategoryQueryField orFieldActive()
 * @method CmsCategoryQuery orderAscActive()
 * @method CmsCategoryQuery orderDescActive()
 * @method CmsCategoryQuery groupByActive()
 * @method QueryHelper\CmsCategoryQueryField andField($fieldName, $tableName = null)
 * @method QueryHelper\CmsCategoryQueryField where($fieldName, $tableName = null)
 * @method QueryHelper\CmsCategoryQueryField orField($fieldName, $tableName = null)
 * @method QueryHelper\CmsCategoryQueryJoin join($tableName, $targetTableName = null, $alias = null)
 * @method QueryHelper\CmsCategoryQueryJoin joinLeft($tableName, $targetTableName = null, $alias = null)
 * @method CmsCategoryRecord[] find()
 * @method CmsCategoryRecord findFirst()
 * @method CmsCategoryRecord findPk($value)
 */
//</editor-fold>
class CmsCategoryQuery extends \Mmi\Orm\Query {

	protected $_tableName = 'cms_category';

}