<?php

namespace Cms\Orm;

//<editor-fold defaultstate="collapsed" desc="CmsMailQuery">
/**
 * @method CmsMailQuery limit($limit = null)
 * @method CmsMailQuery offset($offset = null)
 * @method CmsMailQuery orderAsc($fieldName, $tableName = null)
 * @method CmsMailQuery orderDesc($fieldName, $tableName = null)
 * @method CmsMailQuery andQuery(\Mmi\Orm\Query $query)
 * @method CmsMailQuery whereQuery(\Mmi\Orm\Query $query)
 * @method CmsMailQuery orQuery(\Mmi\Orm\Query $query)
 * @method CmsMailQuery resetOrder()
 * @method CmsMailQuery resetWhere()
 * @method QueryHelper\CmsMailQueryField whereId()
 * @method QueryHelper\CmsMailQueryField andFieldId()
 * @method QueryHelper\CmsMailQueryField orFieldId()
 * @method CmsMailQuery orderAscId()
 * @method CmsMailQuery orderDescId()
 * @method CmsMailQuery groupById()
 * @method QueryHelper\CmsMailQueryField whereCmsMailDefinitionId()
 * @method QueryHelper\CmsMailQueryField andFieldCmsMailDefinitionId()
 * @method QueryHelper\CmsMailQueryField orFieldCmsMailDefinitionId()
 * @method CmsMailQuery orderAscCmsMailDefinitionId()
 * @method CmsMailQuery orderDescCmsMailDefinitionId()
 * @method CmsMailQuery groupByCmsMailDefinitionId()
 * @method QueryHelper\CmsMailQueryField whereFromName()
 * @method QueryHelper\CmsMailQueryField andFieldFromName()
 * @method QueryHelper\CmsMailQueryField orFieldFromName()
 * @method CmsMailQuery orderAscFromName()
 * @method CmsMailQuery orderDescFromName()
 * @method CmsMailQuery groupByFromName()
 * @method QueryHelper\CmsMailQueryField whereTo()
 * @method QueryHelper\CmsMailQueryField andFieldTo()
 * @method QueryHelper\CmsMailQueryField orFieldTo()
 * @method CmsMailQuery orderAscTo()
 * @method CmsMailQuery orderDescTo()
 * @method CmsMailQuery groupByTo()
 * @method QueryHelper\CmsMailQueryField whereReplyTo()
 * @method QueryHelper\CmsMailQueryField andFieldReplyTo()
 * @method QueryHelper\CmsMailQueryField orFieldReplyTo()
 * @method CmsMailQuery orderAscReplyTo()
 * @method CmsMailQuery orderDescReplyTo()
 * @method CmsMailQuery groupByReplyTo()
 * @method QueryHelper\CmsMailQueryField whereSubject()
 * @method QueryHelper\CmsMailQueryField andFieldSubject()
 * @method QueryHelper\CmsMailQueryField orFieldSubject()
 * @method CmsMailQuery orderAscSubject()
 * @method CmsMailQuery orderDescSubject()
 * @method CmsMailQuery groupBySubject()
 * @method QueryHelper\CmsMailQueryField whereMessage()
 * @method QueryHelper\CmsMailQueryField andFieldMessage()
 * @method QueryHelper\CmsMailQueryField orFieldMessage()
 * @method CmsMailQuery orderAscMessage()
 * @method CmsMailQuery orderDescMessage()
 * @method CmsMailQuery groupByMessage()
 * @method QueryHelper\CmsMailQueryField whereAttachements()
 * @method QueryHelper\CmsMailQueryField andFieldAttachements()
 * @method QueryHelper\CmsMailQueryField orFieldAttachements()
 * @method CmsMailQuery orderAscAttachements()
 * @method CmsMailQuery orderDescAttachements()
 * @method CmsMailQuery groupByAttachements()
 * @method QueryHelper\CmsMailQueryField whereType()
 * @method QueryHelper\CmsMailQueryField andFieldType()
 * @method QueryHelper\CmsMailQueryField orFieldType()
 * @method CmsMailQuery orderAscType()
 * @method CmsMailQuery orderDescType()
 * @method CmsMailQuery groupByType()
 * @method QueryHelper\CmsMailQueryField whereDateAdd()
 * @method QueryHelper\CmsMailQueryField andFieldDateAdd()
 * @method QueryHelper\CmsMailQueryField orFieldDateAdd()
 * @method CmsMailQuery orderAscDateAdd()
 * @method CmsMailQuery orderDescDateAdd()
 * @method CmsMailQuery groupByDateAdd()
 * @method QueryHelper\CmsMailQueryField whereDateSent()
 * @method QueryHelper\CmsMailQueryField andFieldDateSent()
 * @method QueryHelper\CmsMailQueryField orFieldDateSent()
 * @method CmsMailQuery orderAscDateSent()
 * @method CmsMailQuery orderDescDateSent()
 * @method CmsMailQuery groupByDateSent()
 * @method QueryHelper\CmsMailQueryField whereDateSendAfter()
 * @method QueryHelper\CmsMailQueryField andFieldDateSendAfter()
 * @method QueryHelper\CmsMailQueryField orFieldDateSendAfter()
 * @method CmsMailQuery orderAscDateSendAfter()
 * @method CmsMailQuery orderDescDateSendAfter()
 * @method CmsMailQuery groupByDateSendAfter()
 * @method QueryHelper\CmsMailQueryField whereActive()
 * @method QueryHelper\CmsMailQueryField andFieldActive()
 * @method QueryHelper\CmsMailQueryField orFieldActive()
 * @method CmsMailQuery orderAscActive()
 * @method CmsMailQuery orderDescActive()
 * @method CmsMailQuery groupByActive()
 * @method QueryHelper\CmsMailQueryField andField($fieldName, $tableName = null)
 * @method QueryHelper\CmsMailQueryField where($fieldName, $tableName = null)
 * @method QueryHelper\CmsMailQueryField orField($fieldName, $tableName = null)
 * @method QueryHelper\CmsMailQueryJoin join($tableName, $targetTableName = null, $alias = null)
 * @method QueryHelper\CmsMailQueryJoin joinLeft($tableName, $targetTableName = null, $alias = null)
 * @method CmsMailRecord[] find()
 * @method CmsMailRecord findFirst()
 * @method CmsMailRecord findPk($value)
 */
//</editor-fold>
class CmsMailQuery extends \Mmi\Orm\Query {

	protected $_tableName = 'cms_mail';

}
