<?php

namespace Cms\Orm\Comment\Query;

/**
 * @method \Cms\Orm\Comment\Query equals($value)
 * @method \Cms\Orm\Comment\Query notEquals($value)
 * @method \Cms\Orm\Comment\Query greater($value)
 * @method \Cms\Orm\Comment\Query less($value)
 * @method \Cms\Orm\Comment\Query greaterOrEquals($value)
 * @method \Cms\Orm\Comment\Query lessOrEquals($value)
 * @method \Cms\Orm\Comment\Query like($value)
 * @method \Cms\Orm\Comment\Query ilike($value)
 * @method \Cms\Orm\Comment\Query equalsColumnId()
 * @method \Cms\Orm\Comment\Query notEqualsColumnId()
 * @method \Cms\Orm\Comment\Query greaterThanColumnId()
 * @method \Cms\Orm\Comment\Query lessThanColumnId()
 * @method \Cms\Orm\Comment\Query greaterOrEqualsColumnId()
 * @method \Cms\Orm\Comment\Query lessOrEqualsColumnId()
 * @method \Cms\Orm\Comment\Query equalsColumnCmsAuthId()
 * @method \Cms\Orm\Comment\Query notEqualsColumnCmsAuthId()
 * @method \Cms\Orm\Comment\Query greaterThanColumnCmsAuthId()
 * @method \Cms\Orm\Comment\Query lessThanColumnCmsAuthId()
 * @method \Cms\Orm\Comment\Query greaterOrEqualsColumnCmsAuthId()
 * @method \Cms\Orm\Comment\Query lessOrEqualsColumnCmsAuthId()
 * @method \Cms\Orm\Comment\Query equalsColumnParentId()
 * @method \Cms\Orm\Comment\Query notEqualsColumnParentId()
 * @method \Cms\Orm\Comment\Query greaterThanColumnParentId()
 * @method \Cms\Orm\Comment\Query lessThanColumnParentId()
 * @method \Cms\Orm\Comment\Query greaterOrEqualsColumnParentId()
 * @method \Cms\Orm\Comment\Query lessOrEqualsColumnParentId()
 * @method \Cms\Orm\Comment\Query equalsColumnDateAdd()
 * @method \Cms\Orm\Comment\Query notEqualsColumnDateAdd()
 * @method \Cms\Orm\Comment\Query greaterThanColumnDateAdd()
 * @method \Cms\Orm\Comment\Query lessThanColumnDateAdd()
 * @method \Cms\Orm\Comment\Query greaterOrEqualsColumnDateAdd()
 * @method \Cms\Orm\Comment\Query lessOrEqualsColumnDateAdd()
 * @method \Cms\Orm\Comment\Query equalsColumnTitle()
 * @method \Cms\Orm\Comment\Query notEqualsColumnTitle()
 * @method \Cms\Orm\Comment\Query greaterThanColumnTitle()
 * @method \Cms\Orm\Comment\Query lessThanColumnTitle()
 * @method \Cms\Orm\Comment\Query greaterOrEqualsColumnTitle()
 * @method \Cms\Orm\Comment\Query lessOrEqualsColumnTitle()
 * @method \Cms\Orm\Comment\Query equalsColumnText()
 * @method \Cms\Orm\Comment\Query notEqualsColumnText()
 * @method \Cms\Orm\Comment\Query greaterThanColumnText()
 * @method \Cms\Orm\Comment\Query lessThanColumnText()
 * @method \Cms\Orm\Comment\Query greaterOrEqualsColumnText()
 * @method \Cms\Orm\Comment\Query lessOrEqualsColumnText()
 * @method \Cms\Orm\Comment\Query equalsColumnSignature()
 * @method \Cms\Orm\Comment\Query notEqualsColumnSignature()
 * @method \Cms\Orm\Comment\Query greaterThanColumnSignature()
 * @method \Cms\Orm\Comment\Query lessThanColumnSignature()
 * @method \Cms\Orm\Comment\Query greaterOrEqualsColumnSignature()
 * @method \Cms\Orm\Comment\Query lessOrEqualsColumnSignature()
 * @method \Cms\Orm\Comment\Query equalsColumnIp()
 * @method \Cms\Orm\Comment\Query notEqualsColumnIp()
 * @method \Cms\Orm\Comment\Query greaterThanColumnIp()
 * @method \Cms\Orm\Comment\Query lessThanColumnIp()
 * @method \Cms\Orm\Comment\Query greaterOrEqualsColumnIp()
 * @method \Cms\Orm\Comment\Query lessOrEqualsColumnIp()
 * @method \Cms\Orm\Comment\Query equalsColumnStars()
 * @method \Cms\Orm\Comment\Query notEqualsColumnStars()
 * @method \Cms\Orm\Comment\Query greaterThanColumnStars()
 * @method \Cms\Orm\Comment\Query lessThanColumnStars()
 * @method \Cms\Orm\Comment\Query greaterOrEqualsColumnStars()
 * @method \Cms\Orm\Comment\Query lessOrEqualsColumnStars()
 * @method \Cms\Orm\Comment\Query equalsColumnObject()
 * @method \Cms\Orm\Comment\Query notEqualsColumnObject()
 * @method \Cms\Orm\Comment\Query greaterThanColumnObject()
 * @method \Cms\Orm\Comment\Query lessThanColumnObject()
 * @method \Cms\Orm\Comment\Query greaterOrEqualsColumnObject()
 * @method \Cms\Orm\Comment\Query lessOrEqualsColumnObject()
 * @method \Cms\Orm\Comment\Query equalsColumnObjectId()
 * @method \Cms\Orm\Comment\Query notEqualsColumnObjectId()
 * @method \Cms\Orm\Comment\Query greaterThanColumnObjectId()
 * @method \Cms\Orm\Comment\Query lessThanColumnObjectId()
 * @method \Cms\Orm\Comment\Query greaterOrEqualsColumnObjectId()
 * @method \Cms\Orm\Comment\Query lessOrEqualsColumnObjectId()
 */
class Field extends \Mmi\Orm\Query\Field {

}
