<?php

/**
 * Mmi Framework (https://github.com/milejko/mmi.git)
 *
 * @link       https://github.com/milejko/mmi.git
 * @copyright  Copyright (c) 2010-2016 Mariusz Miłejko (http://milejko.com)
 * @license    http://milejko.com/new-bsd.txt New BSD License
 */

namespace CmsAdmin\App\NavPart;

/**
 * Konfiguracja nawigatora tekstów stałych
 */
class NavPartSystem extends \Mmi\Navigation\NavigationConfig
{

    /**
     * Zwraca menu
     * @return \Mmi\Navigation\NavigationConfigElement
     */
    public static function getMenu()
    {
        return (new \Mmi\Navigation\NavigationConfigElement)
            ->setLabel('Systemowe')
            ->setIcon('fa-cogs')
            ->setUri('#')
            ->setModule('cmsAdmin')
            ->setController('cache')
            ->addChild((new \Mmi\Navigation\NavigationConfigElement)
                ->setLabel('Atrybuty')
                ->setIcon('fa-book')
                ->setUri('#')
                ->setModule('cmsAdmin')
                ->setController('attribute')
                ->addChild((new \Mmi\Navigation\NavigationConfigElement)
                    ->setLabel('Lista atrybutów')
                    ->setIcon('fa-table')
                    ->setModule('cmsAdmin')
                    ->setController('attribute'))
                ->addChild((new \Mmi\Navigation\NavigationConfigElement)
                    ->setLabel('Dodaj atrybut')
                    ->setIcon('fa-plus')
                    ->setModule('cmsAdmin')
                    ->setController('attribute')
                    ->setAction('edit')))
            //szablony
            ->addChild((new \Mmi\Navigation\NavigationConfigElement)
                ->setLabel('Szablony')
                ->setIcon('fa-clone')
                ->setModule('cmsAdmin')
                ->setController('categoryType')
                ->setUri('#')
                ->addChild((new \Mmi\Navigation\NavigationConfigElement)
                    ->setLabel('Lista szablonów')
                    ->setIcon('fa-table')
                    ->setModule('cmsAdmin'))
                ->addChild((new \Mmi\Navigation\NavigationConfigElement)
                    ->setLabel('Dodaj szablon')
                    ->setIcon('fa-plus')
                    ->setModule('cmsAdmin')
                    ->setController('categoryType')
                    ->setAction('edit'))
            )
            //widgety
            ->addChild((new \Mmi\Navigation\NavigationConfigElement)
                ->setLabel('Widgety')
                ->setIcon('fa-bars')
                ->setUri('#')
                ->setModule('cmsAdmin')
                ->setController('categoryWidget')
                ->addChild((new \Mmi\Navigation\NavigationConfigElement)
                        ->setLabel('Lista widgetów')
                        ->setIcon('fa-table')
                        ->setModule('cmsAdmin')
                        ->setController('categoryWidget')
                )
                ->addChild((new \Mmi\Navigation\NavigationConfigElement)
                    ->setLabel('Dodaj widget')
                    ->setIcon('fa-plus')
                    ->setModule('cmsAdmin')
                    ->setController('categoryWidget')
                    ->setAction('edit')))
            ->addChild((new \Mmi\Navigation\NavigationConfigElement)
                ->setLabel('Tagi')
                ->setIcon('fa-tags')
                ->setUri('#')
                ->setModule('cmsAdmin')
                ->setController('tag')
                ->addChild((new \Mmi\Navigation\NavigationConfigElement)
                    ->setLabel('Lista tagów')
                    ->setIcon('fa-table')
                    ->setModule('cmsAdmin')
                    ->setController('tag'))
                ->addChild((new \Mmi\Navigation\NavigationConfigElement)
                    ->setLabel('Relacje tagów')
                    ->setIcon('fa-tag')
                    ->setModule('cmsAdmin')
                    ->setController('tagRelation'))
                ->addChild((new \Mmi\Navigation\NavigationConfigElement)
                    ->setLabel('Dodaj tag')
                    ->setIcon('fa-plus')
                    ->setModule('cmsAdmin')
                    ->setController('tag')
                    ->setAction('edit')))
            ->addChild((new \Mmi\Navigation\NavigationConfigElement)
                ->setLabel('Cron')
                ->setIcon('fa-calendar')
                ->setUri('#')
                ->setModule('cmsAdmin')
                ->setController('cron')
                ->addChild((new \Mmi\Navigation\NavigationConfigElement)
                    ->setLabel('Lista zadań')
                    ->setIcon('fa-table')
                    ->setModule('cmsAdmin')
                    ->setController('cron'))
                ->addChild((new \Mmi\Navigation\NavigationConfigElement)
                    ->setLabel('Dodaj zadanie')
                    ->setIcon('fa-plus')
                    ->setModule('cmsAdmin')
                    ->setController('cron')
                    ->setAction('edit')
                )
            )
            ->addChild((new \Mmi\Navigation\NavigationConfigElement)
                ->setLabel('Pliki')
                ->setIcon('fa-file')
                ->setModule('cmsAdmin')
                ->setController('file'))
            ->addChild((new \Mmi\Navigation\NavigationConfigElement)
                ->setLabel('Import danych')
                ->setIcon('fa-cloud-download')
                ->setModule('cmsAdmin')
                ->setController('connector')
                ->addChild((new \Mmi\Navigation\NavigationConfigElement)
                    ->setLabel('Import plików')
                    ->setModule('cmsAdmin')
                    ->setController('connector')
                    ->setAction('files')
                    ->setDisabled()
                ))
            ->addChild((new \Mmi\Navigation\NavigationConfigElement)
                ->setLabel('Log')
                ->setIcon('fa-list')
                ->setModule('cmsAdmin')
                ->setController('logi'))
            ->addChild((new \Mmi\Navigation\NavigationConfigElement)
                ->setLabel('Wyczyść bufor')
                ->setModule('cmsAdmin')
                ->setIcon('fa-trash')
                ->setController('cache'))

            ;
    }

}
