<?php

namespace Cms\Orm\Mail\Server;

/**
 * @method \Cms\Orm\Mail\Server\Query equals($value)
 * @method \Cms\Orm\Mail\Server\Query notEquals($value)
 * @method \Cms\Orm\Mail\Server\Query greater($value)
 * @method \Cms\Orm\Mail\Server\Query less($value)
 * @method \Cms\Orm\Mail\Server\Query greaterOrEquals($value)
 * @method \Cms\Orm\Mail\Server\Query lessOrEquals($value)
 * @method \Cms\Orm\Mail\Server\Query like($value)
 * @method \Cms\Orm\Mail\Server\Query ilike($value)
 * @method \Cms\Orm\Mail\Server\Query equalsColumnId()
 * @method \Cms\Orm\Mail\Server\Query notEqualsColumnId()
 * @method \Cms\Orm\Mail\Server\Query greaterThanColumnId()
 * @method \Cms\Orm\Mail\Server\Query lessThanColumnId()
 * @method \Cms\Orm\Mail\Server\Query greaterOrEqualsColumnId()
 * @method \Cms\Orm\Mail\Server\Query lessOrEqualsColumnId()
 * @method \Cms\Orm\Mail\Server\Query equalsColumnAddress()
 * @method \Cms\Orm\Mail\Server\Query notEqualsColumnAddress()
 * @method \Cms\Orm\Mail\Server\Query greaterThanColumnAddress()
 * @method \Cms\Orm\Mail\Server\Query lessThanColumnAddress()
 * @method \Cms\Orm\Mail\Server\Query greaterOrEqualsColumnAddress()
 * @method \Cms\Orm\Mail\Server\Query lessOrEqualsColumnAddress()
 * @method \Cms\Orm\Mail\Server\Query equalsColumnPort()
 * @method \Cms\Orm\Mail\Server\Query notEqualsColumnPort()
 * @method \Cms\Orm\Mail\Server\Query greaterThanColumnPort()
 * @method \Cms\Orm\Mail\Server\Query lessThanColumnPort()
 * @method \Cms\Orm\Mail\Server\Query greaterOrEqualsColumnPort()
 * @method \Cms\Orm\Mail\Server\Query lessOrEqualsColumnPort()
 * @method \Cms\Orm\Mail\Server\Query equalsColumnUsername()
 * @method \Cms\Orm\Mail\Server\Query notEqualsColumnUsername()
 * @method \Cms\Orm\Mail\Server\Query greaterThanColumnUsername()
 * @method \Cms\Orm\Mail\Server\Query lessThanColumnUsername()
 * @method \Cms\Orm\Mail\Server\Query greaterOrEqualsColumnUsername()
 * @method \Cms\Orm\Mail\Server\Query lessOrEqualsColumnUsername()
 * @method \Cms\Orm\Mail\Server\Query equalsColumnPassword()
 * @method \Cms\Orm\Mail\Server\Query notEqualsColumnPassword()
 * @method \Cms\Orm\Mail\Server\Query greaterThanColumnPassword()
 * @method \Cms\Orm\Mail\Server\Query lessThanColumnPassword()
 * @method \Cms\Orm\Mail\Server\Query greaterOrEqualsColumnPassword()
 * @method \Cms\Orm\Mail\Server\Query lessOrEqualsColumnPassword()
 * @method \Cms\Orm\Mail\Server\Query equalsColumnFrom()
 * @method \Cms\Orm\Mail\Server\Query notEqualsColumnFrom()
 * @method \Cms\Orm\Mail\Server\Query greaterThanColumnFrom()
 * @method \Cms\Orm\Mail\Server\Query lessThanColumnFrom()
 * @method \Cms\Orm\Mail\Server\Query greaterOrEqualsColumnFrom()
 * @method \Cms\Orm\Mail\Server\Query lessOrEqualsColumnFrom()
 * @method \Cms\Orm\Mail\Server\Query equalsColumnDateAdd()
 * @method \Cms\Orm\Mail\Server\Query notEqualsColumnDateAdd()
 * @method \Cms\Orm\Mail\Server\Query greaterThanColumnDateAdd()
 * @method \Cms\Orm\Mail\Server\Query lessThanColumnDateAdd()
 * @method \Cms\Orm\Mail\Server\Query greaterOrEqualsColumnDateAdd()
 * @method \Cms\Orm\Mail\Server\Query lessOrEqualsColumnDateAdd()
 * @method \Cms\Orm\Mail\Server\Query equalsColumnDateModify()
 * @method \Cms\Orm\Mail\Server\Query notEqualsColumnDateModify()
 * @method \Cms\Orm\Mail\Server\Query greaterThanColumnDateModify()
 * @method \Cms\Orm\Mail\Server\Query lessThanColumnDateModify()
 * @method \Cms\Orm\Mail\Server\Query greaterOrEqualsColumnDateModify()
 * @method \Cms\Orm\Mail\Server\Query lessOrEqualsColumnDateModify()
 * @method \Cms\Orm\Mail\Server\Query equalsColumnActive()
 * @method \Cms\Orm\Mail\Server\Query notEqualsColumnActive()
 * @method \Cms\Orm\Mail\Server\Query greaterThanColumnActive()
 * @method \Cms\Orm\Mail\Server\Query lessThanColumnActive()
 * @method \Cms\Orm\Mail\Server\Query greaterOrEqualsColumnActive()
 * @method \Cms\Orm\Mail\Server\Query lessOrEqualsColumnActive()
 * @method \Cms\Orm\Mail\Server\Query equalsColumnSsl()
 * @method \Cms\Orm\Mail\Server\Query notEqualsColumnSsl()
 * @method \Cms\Orm\Mail\Server\Query greaterThanColumnSsl()
 * @method \Cms\Orm\Mail\Server\Query lessThanColumnSsl()
 * @method \Cms\Orm\Mail\Server\Query greaterOrEqualsColumnSsl()
 * @method \Cms\Orm\Mail\Server\Query lessOrEqualsColumnSsl()
 */
class QueryField extends \Mmi\Orm\QueryField {

}
