<?php

namespace Cms\Orm\Article;

/**
 * @method \Cms\Orm\Article\Query equals($value)
 * @method \Cms\Orm\Article\Query notEquals($value)
 * @method \Cms\Orm\Article\Query greater($value)
 * @method \Cms\Orm\Article\Query less($value)
 * @method \Cms\Orm\Article\Query greaterOrEquals($value)
 * @method \Cms\Orm\Article\Query lessOrEquals($value)
 * @method \Cms\Orm\Article\Query like($value)
 * @method \Cms\Orm\Article\Query ilike($value)
 * @method \Cms\Orm\Article\Query equalsColumnId()
 * @method \Cms\Orm\Article\Query notEqualsColumnId()
 * @method \Cms\Orm\Article\Query greaterThanColumnId()
 * @method \Cms\Orm\Article\Query lessThanColumnId()
 * @method \Cms\Orm\Article\Query greaterOrEqualsColumnId()
 * @method \Cms\Orm\Article\Query lessOrEqualsColumnId()
 * @method \Cms\Orm\Article\Query equalsColumnLang()
 * @method \Cms\Orm\Article\Query notEqualsColumnLang()
 * @method \Cms\Orm\Article\Query greaterThanColumnLang()
 * @method \Cms\Orm\Article\Query lessThanColumnLang()
 * @method \Cms\Orm\Article\Query greaterOrEqualsColumnLang()
 * @method \Cms\Orm\Article\Query lessOrEqualsColumnLang()
 * @method \Cms\Orm\Article\Query equalsColumnTitle()
 * @method \Cms\Orm\Article\Query notEqualsColumnTitle()
 * @method \Cms\Orm\Article\Query greaterThanColumnTitle()
 * @method \Cms\Orm\Article\Query lessThanColumnTitle()
 * @method \Cms\Orm\Article\Query greaterOrEqualsColumnTitle()
 * @method \Cms\Orm\Article\Query lessOrEqualsColumnTitle()
 * @method \Cms\Orm\Article\Query equalsColumnUri()
 * @method \Cms\Orm\Article\Query notEqualsColumnUri()
 * @method \Cms\Orm\Article\Query greaterThanColumnUri()
 * @method \Cms\Orm\Article\Query lessThanColumnUri()
 * @method \Cms\Orm\Article\Query greaterOrEqualsColumnUri()
 * @method \Cms\Orm\Article\Query lessOrEqualsColumnUri()
 * @method \Cms\Orm\Article\Query equalsColumnDateAdd()
 * @method \Cms\Orm\Article\Query notEqualsColumnDateAdd()
 * @method \Cms\Orm\Article\Query greaterThanColumnDateAdd()
 * @method \Cms\Orm\Article\Query lessThanColumnDateAdd()
 * @method \Cms\Orm\Article\Query greaterOrEqualsColumnDateAdd()
 * @method \Cms\Orm\Article\Query lessOrEqualsColumnDateAdd()
 * @method \Cms\Orm\Article\Query equalsColumnDateModify()
 * @method \Cms\Orm\Article\Query notEqualsColumnDateModify()
 * @method \Cms\Orm\Article\Query greaterThanColumnDateModify()
 * @method \Cms\Orm\Article\Query lessThanColumnDateModify()
 * @method \Cms\Orm\Article\Query greaterOrEqualsColumnDateModify()
 * @method \Cms\Orm\Article\Query lessOrEqualsColumnDateModify()
 * @method \Cms\Orm\Article\Query equalsColumnText()
 * @method \Cms\Orm\Article\Query notEqualsColumnText()
 * @method \Cms\Orm\Article\Query greaterThanColumnText()
 * @method \Cms\Orm\Article\Query lessThanColumnText()
 * @method \Cms\Orm\Article\Query greaterOrEqualsColumnText()
 * @method \Cms\Orm\Article\Query lessOrEqualsColumnText()
 * @method \Cms\Orm\Article\Query equalsColumnNoindex()
 * @method \Cms\Orm\Article\Query notEqualsColumnNoindex()
 * @method \Cms\Orm\Article\Query greaterThanColumnNoindex()
 * @method \Cms\Orm\Article\Query lessThanColumnNoindex()
 * @method \Cms\Orm\Article\Query greaterOrEqualsColumnNoindex()
 * @method \Cms\Orm\Article\Query lessOrEqualsColumnNoindex()
 */
class QueryField extends \Mmi\Orm\QueryField {

}
