<?php

namespace Cms\Orm\Mail\Query;

/**
 * @method \Cms\Orm\Mail\Query equals($value)
 * @method \Cms\Orm\Mail\Query notEquals($value)
 * @method \Cms\Orm\Mail\Query greater($value)
 * @method \Cms\Orm\Mail\Query less($value)
 * @method \Cms\Orm\Mail\Query greaterOrEquals($value)
 * @method \Cms\Orm\Mail\Query lessOrEquals($value)
 * @method \Cms\Orm\Mail\Query like($value)
 * @method \Cms\Orm\Mail\Query ilike($value)
 * @method \Cms\Orm\Mail\Query equalsColumnId()
 * @method \Cms\Orm\Mail\Query notEqualsColumnId()
 * @method \Cms\Orm\Mail\Query greaterThanColumnId()
 * @method \Cms\Orm\Mail\Query lessThanColumnId()
 * @method \Cms\Orm\Mail\Query greaterOrEqualsColumnId()
 * @method \Cms\Orm\Mail\Query lessOrEqualsColumnId()
 * @method \Cms\Orm\Mail\Query equalsColumnCmsMailDefinitionId()
 * @method \Cms\Orm\Mail\Query notEqualsColumnCmsMailDefinitionId()
 * @method \Cms\Orm\Mail\Query greaterThanColumnCmsMailDefinitionId()
 * @method \Cms\Orm\Mail\Query lessThanColumnCmsMailDefinitionId()
 * @method \Cms\Orm\Mail\Query greaterOrEqualsColumnCmsMailDefinitionId()
 * @method \Cms\Orm\Mail\Query lessOrEqualsColumnCmsMailDefinitionId()
 * @method \Cms\Orm\Mail\Query equalsColumnFromName()
 * @method \Cms\Orm\Mail\Query notEqualsColumnFromName()
 * @method \Cms\Orm\Mail\Query greaterThanColumnFromName()
 * @method \Cms\Orm\Mail\Query lessThanColumnFromName()
 * @method \Cms\Orm\Mail\Query greaterOrEqualsColumnFromName()
 * @method \Cms\Orm\Mail\Query lessOrEqualsColumnFromName()
 * @method \Cms\Orm\Mail\Query equalsColumnTo()
 * @method \Cms\Orm\Mail\Query notEqualsColumnTo()
 * @method \Cms\Orm\Mail\Query greaterThanColumnTo()
 * @method \Cms\Orm\Mail\Query lessThanColumnTo()
 * @method \Cms\Orm\Mail\Query greaterOrEqualsColumnTo()
 * @method \Cms\Orm\Mail\Query lessOrEqualsColumnTo()
 * @method \Cms\Orm\Mail\Query equalsColumnReplyTo()
 * @method \Cms\Orm\Mail\Query notEqualsColumnReplyTo()
 * @method \Cms\Orm\Mail\Query greaterThanColumnReplyTo()
 * @method \Cms\Orm\Mail\Query lessThanColumnReplyTo()
 * @method \Cms\Orm\Mail\Query greaterOrEqualsColumnReplyTo()
 * @method \Cms\Orm\Mail\Query lessOrEqualsColumnReplyTo()
 * @method \Cms\Orm\Mail\Query equalsColumnSubject()
 * @method \Cms\Orm\Mail\Query notEqualsColumnSubject()
 * @method \Cms\Orm\Mail\Query greaterThanColumnSubject()
 * @method \Cms\Orm\Mail\Query lessThanColumnSubject()
 * @method \Cms\Orm\Mail\Query greaterOrEqualsColumnSubject()
 * @method \Cms\Orm\Mail\Query lessOrEqualsColumnSubject()
 * @method \Cms\Orm\Mail\Query equalsColumnMessage()
 * @method \Cms\Orm\Mail\Query notEqualsColumnMessage()
 * @method \Cms\Orm\Mail\Query greaterThanColumnMessage()
 * @method \Cms\Orm\Mail\Query lessThanColumnMessage()
 * @method \Cms\Orm\Mail\Query greaterOrEqualsColumnMessage()
 * @method \Cms\Orm\Mail\Query lessOrEqualsColumnMessage()
 * @method \Cms\Orm\Mail\Query equalsColumnAttachements()
 * @method \Cms\Orm\Mail\Query notEqualsColumnAttachements()
 * @method \Cms\Orm\Mail\Query greaterThanColumnAttachements()
 * @method \Cms\Orm\Mail\Query lessThanColumnAttachements()
 * @method \Cms\Orm\Mail\Query greaterOrEqualsColumnAttachements()
 * @method \Cms\Orm\Mail\Query lessOrEqualsColumnAttachements()
 * @method \Cms\Orm\Mail\Query equalsColumnType()
 * @method \Cms\Orm\Mail\Query notEqualsColumnType()
 * @method \Cms\Orm\Mail\Query greaterThanColumnType()
 * @method \Cms\Orm\Mail\Query lessThanColumnType()
 * @method \Cms\Orm\Mail\Query greaterOrEqualsColumnType()
 * @method \Cms\Orm\Mail\Query lessOrEqualsColumnType()
 * @method \Cms\Orm\Mail\Query equalsColumnDateAdd()
 * @method \Cms\Orm\Mail\Query notEqualsColumnDateAdd()
 * @method \Cms\Orm\Mail\Query greaterThanColumnDateAdd()
 * @method \Cms\Orm\Mail\Query lessThanColumnDateAdd()
 * @method \Cms\Orm\Mail\Query greaterOrEqualsColumnDateAdd()
 * @method \Cms\Orm\Mail\Query lessOrEqualsColumnDateAdd()
 * @method \Cms\Orm\Mail\Query equalsColumnDateSent()
 * @method \Cms\Orm\Mail\Query notEqualsColumnDateSent()
 * @method \Cms\Orm\Mail\Query greaterThanColumnDateSent()
 * @method \Cms\Orm\Mail\Query lessThanColumnDateSent()
 * @method \Cms\Orm\Mail\Query greaterOrEqualsColumnDateSent()
 * @method \Cms\Orm\Mail\Query lessOrEqualsColumnDateSent()
 * @method \Cms\Orm\Mail\Query equalsColumnDateSendAfter()
 * @method \Cms\Orm\Mail\Query notEqualsColumnDateSendAfter()
 * @method \Cms\Orm\Mail\Query greaterThanColumnDateSendAfter()
 * @method \Cms\Orm\Mail\Query lessThanColumnDateSendAfter()
 * @method \Cms\Orm\Mail\Query greaterOrEqualsColumnDateSendAfter()
 * @method \Cms\Orm\Mail\Query lessOrEqualsColumnDateSendAfter()
 * @method \Cms\Orm\Mail\Query equalsColumnActive()
 * @method \Cms\Orm\Mail\Query notEqualsColumnActive()
 * @method \Cms\Orm\Mail\Query greaterThanColumnActive()
 * @method \Cms\Orm\Mail\Query lessThanColumnActive()
 * @method \Cms\Orm\Mail\Query greaterOrEqualsColumnActive()
 * @method \Cms\Orm\Mail\Query lessOrEqualsColumnActive()
 */
class Field extends \Mmi\Orm\Query\Field {

}
