<?php

namespace Cms\Orm\Acl\Query;

/**
 * @method \Cms\Orm\Acl\Query equals($value)
 * @method \Cms\Orm\Acl\Query notEquals($value)
 * @method \Cms\Orm\Acl\Query greater($value)
 * @method \Cms\Orm\Acl\Query less($value)
 * @method \Cms\Orm\Acl\Query greaterOrEquals($value)
 * @method \Cms\Orm\Acl\Query lessOrEquals($value)
 * @method \Cms\Orm\Acl\Query like($value)
 * @method \Cms\Orm\Acl\Query ilike($value)
 * @method \Cms\Orm\Acl\Query equalsColumnId()
 * @method \Cms\Orm\Acl\Query notEqualsColumnId()
 * @method \Cms\Orm\Acl\Query greaterThanColumnId()
 * @method \Cms\Orm\Acl\Query lessThanColumnId()
 * @method \Cms\Orm\Acl\Query greaterOrEqualsColumnId()
 * @method \Cms\Orm\Acl\Query lessOrEqualsColumnId()
 * @method \Cms\Orm\Acl\Query equalsColumnCmsRoleId()
 * @method \Cms\Orm\Acl\Query notEqualsColumnCmsRoleId()
 * @method \Cms\Orm\Acl\Query greaterThanColumnCmsRoleId()
 * @method \Cms\Orm\Acl\Query lessThanColumnCmsRoleId()
 * @method \Cms\Orm\Acl\Query greaterOrEqualsColumnCmsRoleId()
 * @method \Cms\Orm\Acl\Query lessOrEqualsColumnCmsRoleId()
 * @method \Cms\Orm\Acl\Query equalsColumnModule()
 * @method \Cms\Orm\Acl\Query notEqualsColumnModule()
 * @method \Cms\Orm\Acl\Query greaterThanColumnModule()
 * @method \Cms\Orm\Acl\Query lessThanColumnModule()
 * @method \Cms\Orm\Acl\Query greaterOrEqualsColumnModule()
 * @method \Cms\Orm\Acl\Query lessOrEqualsColumnModule()
 * @method \Cms\Orm\Acl\Query equalsColumnController()
 * @method \Cms\Orm\Acl\Query notEqualsColumnController()
 * @method \Cms\Orm\Acl\Query greaterThanColumnController()
 * @method \Cms\Orm\Acl\Query lessThanColumnController()
 * @method \Cms\Orm\Acl\Query greaterOrEqualsColumnController()
 * @method \Cms\Orm\Acl\Query lessOrEqualsColumnController()
 * @method \Cms\Orm\Acl\Query equalsColumnAction()
 * @method \Cms\Orm\Acl\Query notEqualsColumnAction()
 * @method \Cms\Orm\Acl\Query greaterThanColumnAction()
 * @method \Cms\Orm\Acl\Query lessThanColumnAction()
 * @method \Cms\Orm\Acl\Query greaterOrEqualsColumnAction()
 * @method \Cms\Orm\Acl\Query lessOrEqualsColumnAction()
 * @method \Cms\Orm\Acl\Query equalsColumnAccess()
 * @method \Cms\Orm\Acl\Query notEqualsColumnAccess()
 * @method \Cms\Orm\Acl\Query greaterThanColumnAccess()
 * @method \Cms\Orm\Acl\Query lessThanColumnAccess()
 * @method \Cms\Orm\Acl\Query greaterOrEqualsColumnAccess()
 * @method \Cms\Orm\Acl\Query lessOrEqualsColumnAccess()
 */
class Field extends \Mmi\Orm\Query\Field {

}
