<?php

namespace Cms\Orm\Auth\Query;

/**
 * @method \Cms\Orm\Auth\Query equals($value)
 * @method \Cms\Orm\Auth\Query notEquals($value)
 * @method \Cms\Orm\Auth\Query greater($value)
 * @method \Cms\Orm\Auth\Query less($value)
 * @method \Cms\Orm\Auth\Query greaterOrEquals($value)
 * @method \Cms\Orm\Auth\Query lessOrEquals($value)
 * @method \Cms\Orm\Auth\Query like($value)
 * @method \Cms\Orm\Auth\Query ilike($value)
 * @method \Cms\Orm\Auth\Query equalsColumnId()
 * @method \Cms\Orm\Auth\Query notEqualsColumnId()
 * @method \Cms\Orm\Auth\Query greaterThanColumnId()
 * @method \Cms\Orm\Auth\Query lessThanColumnId()
 * @method \Cms\Orm\Auth\Query greaterOrEqualsColumnId()
 * @method \Cms\Orm\Auth\Query lessOrEqualsColumnId()
 * @method \Cms\Orm\Auth\Query equalsColumnLang()
 * @method \Cms\Orm\Auth\Query notEqualsColumnLang()
 * @method \Cms\Orm\Auth\Query greaterThanColumnLang()
 * @method \Cms\Orm\Auth\Query lessThanColumnLang()
 * @method \Cms\Orm\Auth\Query greaterOrEqualsColumnLang()
 * @method \Cms\Orm\Auth\Query lessOrEqualsColumnLang()
 * @method \Cms\Orm\Auth\Query equalsColumnName()
 * @method \Cms\Orm\Auth\Query notEqualsColumnName()
 * @method \Cms\Orm\Auth\Query greaterThanColumnName()
 * @method \Cms\Orm\Auth\Query lessThanColumnName()
 * @method \Cms\Orm\Auth\Query greaterOrEqualsColumnName()
 * @method \Cms\Orm\Auth\Query lessOrEqualsColumnName()
 * @method \Cms\Orm\Auth\Query equalsColumnUsername()
 * @method \Cms\Orm\Auth\Query notEqualsColumnUsername()
 * @method \Cms\Orm\Auth\Query greaterThanColumnUsername()
 * @method \Cms\Orm\Auth\Query lessThanColumnUsername()
 * @method \Cms\Orm\Auth\Query greaterOrEqualsColumnUsername()
 * @method \Cms\Orm\Auth\Query lessOrEqualsColumnUsername()
 * @method \Cms\Orm\Auth\Query equalsColumnEmail()
 * @method \Cms\Orm\Auth\Query notEqualsColumnEmail()
 * @method \Cms\Orm\Auth\Query greaterThanColumnEmail()
 * @method \Cms\Orm\Auth\Query lessThanColumnEmail()
 * @method \Cms\Orm\Auth\Query greaterOrEqualsColumnEmail()
 * @method \Cms\Orm\Auth\Query lessOrEqualsColumnEmail()
 * @method \Cms\Orm\Auth\Query equalsColumnPassword()
 * @method \Cms\Orm\Auth\Query notEqualsColumnPassword()
 * @method \Cms\Orm\Auth\Query greaterThanColumnPassword()
 * @method \Cms\Orm\Auth\Query lessThanColumnPassword()
 * @method \Cms\Orm\Auth\Query greaterOrEqualsColumnPassword()
 * @method \Cms\Orm\Auth\Query lessOrEqualsColumnPassword()
 * @method \Cms\Orm\Auth\Query equalsColumnLastIp()
 * @method \Cms\Orm\Auth\Query notEqualsColumnLastIp()
 * @method \Cms\Orm\Auth\Query greaterThanColumnLastIp()
 * @method \Cms\Orm\Auth\Query lessThanColumnLastIp()
 * @method \Cms\Orm\Auth\Query greaterOrEqualsColumnLastIp()
 * @method \Cms\Orm\Auth\Query lessOrEqualsColumnLastIp()
 * @method \Cms\Orm\Auth\Query equalsColumnLastLog()
 * @method \Cms\Orm\Auth\Query notEqualsColumnLastLog()
 * @method \Cms\Orm\Auth\Query greaterThanColumnLastLog()
 * @method \Cms\Orm\Auth\Query lessThanColumnLastLog()
 * @method \Cms\Orm\Auth\Query greaterOrEqualsColumnLastLog()
 * @method \Cms\Orm\Auth\Query lessOrEqualsColumnLastLog()
 * @method \Cms\Orm\Auth\Query equalsColumnLastFailIp()
 * @method \Cms\Orm\Auth\Query notEqualsColumnLastFailIp()
 * @method \Cms\Orm\Auth\Query greaterThanColumnLastFailIp()
 * @method \Cms\Orm\Auth\Query lessThanColumnLastFailIp()
 * @method \Cms\Orm\Auth\Query greaterOrEqualsColumnLastFailIp()
 * @method \Cms\Orm\Auth\Query lessOrEqualsColumnLastFailIp()
 * @method \Cms\Orm\Auth\Query equalsColumnLastFailLog()
 * @method \Cms\Orm\Auth\Query notEqualsColumnLastFailLog()
 * @method \Cms\Orm\Auth\Query greaterThanColumnLastFailLog()
 * @method \Cms\Orm\Auth\Query lessThanColumnLastFailLog()
 * @method \Cms\Orm\Auth\Query greaterOrEqualsColumnLastFailLog()
 * @method \Cms\Orm\Auth\Query lessOrEqualsColumnLastFailLog()
 * @method \Cms\Orm\Auth\Query equalsColumnFailLogCount()
 * @method \Cms\Orm\Auth\Query notEqualsColumnFailLogCount()
 * @method \Cms\Orm\Auth\Query greaterThanColumnFailLogCount()
 * @method \Cms\Orm\Auth\Query lessThanColumnFailLogCount()
 * @method \Cms\Orm\Auth\Query greaterOrEqualsColumnFailLogCount()
 * @method \Cms\Orm\Auth\Query lessOrEqualsColumnFailLogCount()
 * @method \Cms\Orm\Auth\Query equalsColumnLogged()
 * @method \Cms\Orm\Auth\Query notEqualsColumnLogged()
 * @method \Cms\Orm\Auth\Query greaterThanColumnLogged()
 * @method \Cms\Orm\Auth\Query lessThanColumnLogged()
 * @method \Cms\Orm\Auth\Query greaterOrEqualsColumnLogged()
 * @method \Cms\Orm\Auth\Query lessOrEqualsColumnLogged()
 * @method \Cms\Orm\Auth\Query equalsColumnActive()
 * @method \Cms\Orm\Auth\Query notEqualsColumnActive()
 * @method \Cms\Orm\Auth\Query greaterThanColumnActive()
 * @method \Cms\Orm\Auth\Query lessThanColumnActive()
 * @method \Cms\Orm\Auth\Query greaterOrEqualsColumnActive()
 * @method \Cms\Orm\Auth\Query lessOrEqualsColumnActive()
 */
class Field extends \Mmi\Orm\Query\Field {

}
