<?php

namespace Cms\Orm\Page\Widget\Query;

/**
 * @method \Cms\Orm\Page\Widget\Query equals($value)
 * @method \Cms\Orm\Page\Widget\Query notEquals($value)
 * @method \Cms\Orm\Page\Widget\Query greater($value)
 * @method \Cms\Orm\Page\Widget\Query less($value)
 * @method \Cms\Orm\Page\Widget\Query greaterOrEquals($value)
 * @method \Cms\Orm\Page\Widget\Query lessOrEquals($value)
 * @method \Cms\Orm\Page\Widget\Query like($value)
 * @method \Cms\Orm\Page\Widget\Query ilike($value)
 * @method \Cms\Orm\Page\Widget\Query equalsColumnId()
 * @method \Cms\Orm\Page\Widget\Query notEqualsColumnId()
 * @method \Cms\Orm\Page\Widget\Query greaterThanColumnId()
 * @method \Cms\Orm\Page\Widget\Query lessThanColumnId()
 * @method \Cms\Orm\Page\Widget\Query greaterOrEqualsColumnId()
 * @method \Cms\Orm\Page\Widget\Query lessOrEqualsColumnId()
 * @method \Cms\Orm\Page\Widget\Query equalsColumnName()
 * @method \Cms\Orm\Page\Widget\Query notEqualsColumnName()
 * @method \Cms\Orm\Page\Widget\Query greaterThanColumnName()
 * @method \Cms\Orm\Page\Widget\Query lessThanColumnName()
 * @method \Cms\Orm\Page\Widget\Query greaterOrEqualsColumnName()
 * @method \Cms\Orm\Page\Widget\Query lessOrEqualsColumnName()
 * @method \Cms\Orm\Page\Widget\Query equalsColumnModule()
 * @method \Cms\Orm\Page\Widget\Query notEqualsColumnModule()
 * @method \Cms\Orm\Page\Widget\Query greaterThanColumnModule()
 * @method \Cms\Orm\Page\Widget\Query lessThanColumnModule()
 * @method \Cms\Orm\Page\Widget\Query greaterOrEqualsColumnModule()
 * @method \Cms\Orm\Page\Widget\Query lessOrEqualsColumnModule()
 * @method \Cms\Orm\Page\Widget\Query equalsColumnController()
 * @method \Cms\Orm\Page\Widget\Query notEqualsColumnController()
 * @method \Cms\Orm\Page\Widget\Query greaterThanColumnController()
 * @method \Cms\Orm\Page\Widget\Query lessThanColumnController()
 * @method \Cms\Orm\Page\Widget\Query greaterOrEqualsColumnController()
 * @method \Cms\Orm\Page\Widget\Query lessOrEqualsColumnController()
 * @method \Cms\Orm\Page\Widget\Query equalsColumnAction()
 * @method \Cms\Orm\Page\Widget\Query notEqualsColumnAction()
 * @method \Cms\Orm\Page\Widget\Query greaterThanColumnAction()
 * @method \Cms\Orm\Page\Widget\Query lessThanColumnAction()
 * @method \Cms\Orm\Page\Widget\Query greaterOrEqualsColumnAction()
 * @method \Cms\Orm\Page\Widget\Query lessOrEqualsColumnAction()
 * @method \Cms\Orm\Page\Widget\Query equalsColumnParams()
 * @method \Cms\Orm\Page\Widget\Query notEqualsColumnParams()
 * @method \Cms\Orm\Page\Widget\Query greaterThanColumnParams()
 * @method \Cms\Orm\Page\Widget\Query lessThanColumnParams()
 * @method \Cms\Orm\Page\Widget\Query greaterOrEqualsColumnParams()
 * @method \Cms\Orm\Page\Widget\Query lessOrEqualsColumnParams()
 * @method \Cms\Orm\Page\Widget\Query equalsColumnActive()
 * @method \Cms\Orm\Page\Widget\Query notEqualsColumnActive()
 * @method \Cms\Orm\Page\Widget\Query greaterThanColumnActive()
 * @method \Cms\Orm\Page\Widget\Query lessThanColumnActive()
 * @method \Cms\Orm\Page\Widget\Query greaterOrEqualsColumnActive()
 * @method \Cms\Orm\Page\Widget\Query lessOrEqualsColumnActive()
 */
class Field extends \Mmi\Orm\Query\Field {

}
