<?php

namespace Cms\Orm\Mail;

//<editor-fold defaultstate="collapsed" desc="cms_mail Query">
/**
 * @method \Cms\Orm\Mail\Query limit($limit = null)
 * @method \Cms\Orm\Mail\Query offset($offset = null)
 * @method \Cms\Orm\Mail\Query orderAsc($fieldName, $tableName = null)
 * @method \Cms\Orm\Mail\Query orderDesc($fieldName, $tableName = null)
 * @method \Cms\Orm\Mail\Query andQuery(\Mmi\Orm\Query $query)
 * @method \Cms\Orm\Mail\Query whereQuery(\Mmi\Orm\Query $query)
 * @method \Cms\Orm\Mail\Query orQuery(\Mmi\Orm\Query $query)
 * @method \Cms\Orm\Mail\Query resetOrder()
 * @method \Cms\Orm\Mail\Query resetWhere()
 * @method \Cms\Orm\Mail\QueryField whereId()
 * @method \Cms\Orm\Mail\QueryField andFieldId()
 * @method \Cms\Orm\Mail\QueryField orFieldId()
 * @method \Cms\Orm\Mail\Query orderAscId()
 * @method \Cms\Orm\Mail\Query orderDescId()
 * @method \Cms\Orm\Mail\Query groupById()
 * @method \Cms\Orm\Mail\QueryField whereCmsMailDefinitionId()
 * @method \Cms\Orm\Mail\QueryField andFieldCmsMailDefinitionId()
 * @method \Cms\Orm\Mail\QueryField orFieldCmsMailDefinitionId()
 * @method \Cms\Orm\Mail\Query orderAscCmsMailDefinitionId()
 * @method \Cms\Orm\Mail\Query orderDescCmsMailDefinitionId()
 * @method \Cms\Orm\Mail\Query groupByCmsMailDefinitionId()
 * @method \Cms\Orm\Mail\QueryField whereFromName()
 * @method \Cms\Orm\Mail\QueryField andFieldFromName()
 * @method \Cms\Orm\Mail\QueryField orFieldFromName()
 * @method \Cms\Orm\Mail\Query orderAscFromName()
 * @method \Cms\Orm\Mail\Query orderDescFromName()
 * @method \Cms\Orm\Mail\Query groupByFromName()
 * @method \Cms\Orm\Mail\QueryField whereTo()
 * @method \Cms\Orm\Mail\QueryField andFieldTo()
 * @method \Cms\Orm\Mail\QueryField orFieldTo()
 * @method \Cms\Orm\Mail\Query orderAscTo()
 * @method \Cms\Orm\Mail\Query orderDescTo()
 * @method \Cms\Orm\Mail\Query groupByTo()
 * @method \Cms\Orm\Mail\QueryField whereReplyTo()
 * @method \Cms\Orm\Mail\QueryField andFieldReplyTo()
 * @method \Cms\Orm\Mail\QueryField orFieldReplyTo()
 * @method \Cms\Orm\Mail\Query orderAscReplyTo()
 * @method \Cms\Orm\Mail\Query orderDescReplyTo()
 * @method \Cms\Orm\Mail\Query groupByReplyTo()
 * @method \Cms\Orm\Mail\QueryField whereSubject()
 * @method \Cms\Orm\Mail\QueryField andFieldSubject()
 * @method \Cms\Orm\Mail\QueryField orFieldSubject()
 * @method \Cms\Orm\Mail\Query orderAscSubject()
 * @method \Cms\Orm\Mail\Query orderDescSubject()
 * @method \Cms\Orm\Mail\Query groupBySubject()
 * @method \Cms\Orm\Mail\QueryField whereMessage()
 * @method \Cms\Orm\Mail\QueryField andFieldMessage()
 * @method \Cms\Orm\Mail\QueryField orFieldMessage()
 * @method \Cms\Orm\Mail\Query orderAscMessage()
 * @method \Cms\Orm\Mail\Query orderDescMessage()
 * @method \Cms\Orm\Mail\Query groupByMessage()
 * @method \Cms\Orm\Mail\QueryField whereAttachements()
 * @method \Cms\Orm\Mail\QueryField andFieldAttachements()
 * @method \Cms\Orm\Mail\QueryField orFieldAttachements()
 * @method \Cms\Orm\Mail\Query orderAscAttachements()
 * @method \Cms\Orm\Mail\Query orderDescAttachements()
 * @method \Cms\Orm\Mail\Query groupByAttachements()
 * @method \Cms\Orm\Mail\QueryField whereType()
 * @method \Cms\Orm\Mail\QueryField andFieldType()
 * @method \Cms\Orm\Mail\QueryField orFieldType()
 * @method \Cms\Orm\Mail\Query orderAscType()
 * @method \Cms\Orm\Mail\Query orderDescType()
 * @method \Cms\Orm\Mail\Query groupByType()
 * @method \Cms\Orm\Mail\QueryField whereDateAdd()
 * @method \Cms\Orm\Mail\QueryField andFieldDateAdd()
 * @method \Cms\Orm\Mail\QueryField orFieldDateAdd()
 * @method \Cms\Orm\Mail\Query orderAscDateAdd()
 * @method \Cms\Orm\Mail\Query orderDescDateAdd()
 * @method \Cms\Orm\Mail\Query groupByDateAdd()
 * @method \Cms\Orm\Mail\QueryField whereDateSent()
 * @method \Cms\Orm\Mail\QueryField andFieldDateSent()
 * @method \Cms\Orm\Mail\QueryField orFieldDateSent()
 * @method \Cms\Orm\Mail\Query orderAscDateSent()
 * @method \Cms\Orm\Mail\Query orderDescDateSent()
 * @method \Cms\Orm\Mail\Query groupByDateSent()
 * @method \Cms\Orm\Mail\QueryField whereDateSendAfter()
 * @method \Cms\Orm\Mail\QueryField andFieldDateSendAfter()
 * @method \Cms\Orm\Mail\QueryField orFieldDateSendAfter()
 * @method \Cms\Orm\Mail\Query orderAscDateSendAfter()
 * @method \Cms\Orm\Mail\Query orderDescDateSendAfter()
 * @method \Cms\Orm\Mail\Query groupByDateSendAfter()
 * @method \Cms\Orm\Mail\QueryField whereActive()
 * @method \Cms\Orm\Mail\QueryField andFieldActive()
 * @method \Cms\Orm\Mail\QueryField orFieldActive()
 * @method \Cms\Orm\Mail\Query orderAscActive()
 * @method \Cms\Orm\Mail\Query orderDescActive()
 * @method \Cms\Orm\Mail\Query groupByActive()
 * @method \Cms\Orm\Mail\QueryField andField($fieldName, $tableName = null)
 * @method \Cms\Orm\Mail\QueryField where($fieldName, $tableName = null)
 * @method \Cms\Orm\Mail\QueryField orField($fieldName, $tableName = null)
 * @method \Cms\Orm\Mail\QueryJoin join($tableName, $targetTableName = null)
 * @method \Cms\Orm\Mail\QueryJoin joinLeft($tableName, $targetTableName = null)
 * @method \Cms\Orm\Mail\Record[] find()
 * @method \Cms\Orm\Mail\Record findFirst()
 * @method \Cms\Orm\Mail\Record findPk($value)
 */
//</editor-fold>
class Query extends \Mmi\Orm\Query {

	protected $_tableName = 'cms_mail';

	/**
	 * @return \Cms\Orm\Mail\Query
	 */
	public static function factory($daoClassName = null) {
		return new self($daoClassName);
	}

}
