<?php

namespace Cms\Orm\Mail;

//<editor-fold defaultstate="collapsed" desc="cms_mail Query">
/**
 * @method \Cms\Orm\Mail\Query limit($limit = null)
 * @method \Cms\Orm\Mail\Query offset($offset = null)
 * @method \Cms\Orm\Mail\Query orderAsc($fieldName, $tableName = null)
 * @method \Cms\Orm\Mail\Query orderDesc($fieldName, $tableName = null)
 * @method \Cms\Orm\Mail\Query andQuery(\Mmi\Orm\Query $query)
 * @method \Cms\Orm\Mail\Query whereQuery(\Mmi\Orm\Query $query)
 * @method \Cms\Orm\Mail\Query orQuery(\Mmi\Orm\Query $query)
 * @method \Cms\Orm\Mail\Query resetOrder()
 * @method \Cms\Orm\Mail\Query resetWhere()
 * @method \Cms\Orm\Mail\Query\Field whereId()
 * @method \Cms\Orm\Mail\Query\Field andFieldId()
 * @method \Cms\Orm\Mail\Query\Field orFieldId()
 * @method \Cms\Orm\Mail\Query orderAscId()
 * @method \Cms\Orm\Mail\Query orderDescId()
 * @method \Cms\Orm\Mail\Query groupById()
 * @method \Cms\Orm\Mail\Query\Field whereCmsMailDefinitionId()
 * @method \Cms\Orm\Mail\Query\Field andFieldCmsMailDefinitionId()
 * @method \Cms\Orm\Mail\Query\Field orFieldCmsMailDefinitionId()
 * @method \Cms\Orm\Mail\Query orderAscCmsMailDefinitionId()
 * @method \Cms\Orm\Mail\Query orderDescCmsMailDefinitionId()
 * @method \Cms\Orm\Mail\Query groupByCmsMailDefinitionId()
 * @method \Cms\Orm\Mail\Query\Field whereFromName()
 * @method \Cms\Orm\Mail\Query\Field andFieldFromName()
 * @method \Cms\Orm\Mail\Query\Field orFieldFromName()
 * @method \Cms\Orm\Mail\Query orderAscFromName()
 * @method \Cms\Orm\Mail\Query orderDescFromName()
 * @method \Cms\Orm\Mail\Query groupByFromName()
 * @method \Cms\Orm\Mail\Query\Field whereTo()
 * @method \Cms\Orm\Mail\Query\Field andFieldTo()
 * @method \Cms\Orm\Mail\Query\Field orFieldTo()
 * @method \Cms\Orm\Mail\Query orderAscTo()
 * @method \Cms\Orm\Mail\Query orderDescTo()
 * @method \Cms\Orm\Mail\Query groupByTo()
 * @method \Cms\Orm\Mail\Query\Field whereReplyTo()
 * @method \Cms\Orm\Mail\Query\Field andFieldReplyTo()
 * @method \Cms\Orm\Mail\Query\Field orFieldReplyTo()
 * @method \Cms\Orm\Mail\Query orderAscReplyTo()
 * @method \Cms\Orm\Mail\Query orderDescReplyTo()
 * @method \Cms\Orm\Mail\Query groupByReplyTo()
 * @method \Cms\Orm\Mail\Query\Field whereSubject()
 * @method \Cms\Orm\Mail\Query\Field andFieldSubject()
 * @method \Cms\Orm\Mail\Query\Field orFieldSubject()
 * @method \Cms\Orm\Mail\Query orderAscSubject()
 * @method \Cms\Orm\Mail\Query orderDescSubject()
 * @method \Cms\Orm\Mail\Query groupBySubject()
 * @method \Cms\Orm\Mail\Query\Field whereMessage()
 * @method \Cms\Orm\Mail\Query\Field andFieldMessage()
 * @method \Cms\Orm\Mail\Query\Field orFieldMessage()
 * @method \Cms\Orm\Mail\Query orderAscMessage()
 * @method \Cms\Orm\Mail\Query orderDescMessage()
 * @method \Cms\Orm\Mail\Query groupByMessage()
 * @method \Cms\Orm\Mail\Query\Field whereAttachements()
 * @method \Cms\Orm\Mail\Query\Field andFieldAttachements()
 * @method \Cms\Orm\Mail\Query\Field orFieldAttachements()
 * @method \Cms\Orm\Mail\Query orderAscAttachements()
 * @method \Cms\Orm\Mail\Query orderDescAttachements()
 * @method \Cms\Orm\Mail\Query groupByAttachements()
 * @method \Cms\Orm\Mail\Query\Field whereType()
 * @method \Cms\Orm\Mail\Query\Field andFieldType()
 * @method \Cms\Orm\Mail\Query\Field orFieldType()
 * @method \Cms\Orm\Mail\Query orderAscType()
 * @method \Cms\Orm\Mail\Query orderDescType()
 * @method \Cms\Orm\Mail\Query groupByType()
 * @method \Cms\Orm\Mail\Query\Field whereDateAdd()
 * @method \Cms\Orm\Mail\Query\Field andFieldDateAdd()
 * @method \Cms\Orm\Mail\Query\Field orFieldDateAdd()
 * @method \Cms\Orm\Mail\Query orderAscDateAdd()
 * @method \Cms\Orm\Mail\Query orderDescDateAdd()
 * @method \Cms\Orm\Mail\Query groupByDateAdd()
 * @method \Cms\Orm\Mail\Query\Field whereDateSent()
 * @method \Cms\Orm\Mail\Query\Field andFieldDateSent()
 * @method \Cms\Orm\Mail\Query\Field orFieldDateSent()
 * @method \Cms\Orm\Mail\Query orderAscDateSent()
 * @method \Cms\Orm\Mail\Query orderDescDateSent()
 * @method \Cms\Orm\Mail\Query groupByDateSent()
 * @method \Cms\Orm\Mail\Query\Field whereDateSendAfter()
 * @method \Cms\Orm\Mail\Query\Field andFieldDateSendAfter()
 * @method \Cms\Orm\Mail\Query\Field orFieldDateSendAfter()
 * @method \Cms\Orm\Mail\Query orderAscDateSendAfter()
 * @method \Cms\Orm\Mail\Query orderDescDateSendAfter()
 * @method \Cms\Orm\Mail\Query groupByDateSendAfter()
 * @method \Cms\Orm\Mail\Query\Field whereActive()
 * @method \Cms\Orm\Mail\Query\Field andFieldActive()
 * @method \Cms\Orm\Mail\Query\Field orFieldActive()
 * @method \Cms\Orm\Mail\Query orderAscActive()
 * @method \Cms\Orm\Mail\Query orderDescActive()
 * @method \Cms\Orm\Mail\Query groupByActive()
 * @method \Cms\Orm\Mail\Query\Field andField($fieldName, $tableName = null)
 * @method \Cms\Orm\Mail\Query\Field where($fieldName, $tableName = null)
 * @method \Cms\Orm\Mail\Query\Field orField($fieldName, $tableName = null)
 * @method \Cms\Orm\Mail\Query\Join join($tableName, $targetTableName = null)
 * @method \Cms\Orm\Mail\Query\Join joinLeft($tableName, $targetTableName = null)
 * @method \Cms\Orm\Mail\Record[] find()
 * @method \Cms\Orm\Mail\Record findFirst()
 * @method \Cms\Orm\Mail\Record findPk($value)
 */
//</editor-fold>
class Query extends \Mmi\Orm\Query {

	protected $_tableName = 'cms_mail';

	/**
	 * @return \Cms\Orm\Mail\Query
	 */
	public static function factory($daoClassName = null) {
		return new self($daoClassName);
	}

}
