<?php

namespace Cms\Orm\QueryHelper;

/**
 * @method \Cms\Orm\CmsArticleQuery equals($value)
 * @method \Cms\Orm\CmsArticleQuery notEquals($value)
 * @method \Cms\Orm\CmsArticleQuery greater($value)
 * @method \Cms\Orm\CmsArticleQuery less($value)
 * @method \Cms\Orm\CmsArticleQuery greaterOrEquals($value)
 * @method \Cms\Orm\CmsArticleQuery lessOrEquals($value)
 * @method \Cms\Orm\CmsArticleQuery like($value)
 * @method \Cms\Orm\CmsArticleQuery ilike($value)
 * @method \Cms\Orm\CmsArticleQuery between($from, $to)
 * @method \Cms\Orm\CmsArticleQuery equalsColumnId()
 * @method \Cms\Orm\CmsArticleQuery notEqualsColumnId()
 * @method \Cms\Orm\CmsArticleQuery greaterThanColumnId()
 * @method \Cms\Orm\CmsArticleQuery lessThanColumnId()
 * @method \Cms\Orm\CmsArticleQuery greaterOrEqualsColumnId()
 * @method \Cms\Orm\CmsArticleQuery lessOrEqualsColumnId()
 * @method \Cms\Orm\CmsArticleQuery equalsColumnLang()
 * @method \Cms\Orm\CmsArticleQuery notEqualsColumnLang()
 * @method \Cms\Orm\CmsArticleQuery greaterThanColumnLang()
 * @method \Cms\Orm\CmsArticleQuery lessThanColumnLang()
 * @method \Cms\Orm\CmsArticleQuery greaterOrEqualsColumnLang()
 * @method \Cms\Orm\CmsArticleQuery lessOrEqualsColumnLang()
 * @method \Cms\Orm\CmsArticleQuery equalsColumnTitle()
 * @method \Cms\Orm\CmsArticleQuery notEqualsColumnTitle()
 * @method \Cms\Orm\CmsArticleQuery greaterThanColumnTitle()
 * @method \Cms\Orm\CmsArticleQuery lessThanColumnTitle()
 * @method \Cms\Orm\CmsArticleQuery greaterOrEqualsColumnTitle()
 * @method \Cms\Orm\CmsArticleQuery lessOrEqualsColumnTitle()
 * @method \Cms\Orm\CmsArticleQuery equalsColumnUri()
 * @method \Cms\Orm\CmsArticleQuery notEqualsColumnUri()
 * @method \Cms\Orm\CmsArticleQuery greaterThanColumnUri()
 * @method \Cms\Orm\CmsArticleQuery lessThanColumnUri()
 * @method \Cms\Orm\CmsArticleQuery greaterOrEqualsColumnUri()
 * @method \Cms\Orm\CmsArticleQuery lessOrEqualsColumnUri()
 * @method \Cms\Orm\CmsArticleQuery equalsColumnDateAdd()
 * @method \Cms\Orm\CmsArticleQuery notEqualsColumnDateAdd()
 * @method \Cms\Orm\CmsArticleQuery greaterThanColumnDateAdd()
 * @method \Cms\Orm\CmsArticleQuery lessThanColumnDateAdd()
 * @method \Cms\Orm\CmsArticleQuery greaterOrEqualsColumnDateAdd()
 * @method \Cms\Orm\CmsArticleQuery lessOrEqualsColumnDateAdd()
 * @method \Cms\Orm\CmsArticleQuery equalsColumnDateModify()
 * @method \Cms\Orm\CmsArticleQuery notEqualsColumnDateModify()
 * @method \Cms\Orm\CmsArticleQuery greaterThanColumnDateModify()
 * @method \Cms\Orm\CmsArticleQuery lessThanColumnDateModify()
 * @method \Cms\Orm\CmsArticleQuery greaterOrEqualsColumnDateModify()
 * @method \Cms\Orm\CmsArticleQuery lessOrEqualsColumnDateModify()
 * @method \Cms\Orm\CmsArticleQuery equalsColumnText()
 * @method \Cms\Orm\CmsArticleQuery notEqualsColumnText()
 * @method \Cms\Orm\CmsArticleQuery greaterThanColumnText()
 * @method \Cms\Orm\CmsArticleQuery lessThanColumnText()
 * @method \Cms\Orm\CmsArticleQuery greaterOrEqualsColumnText()
 * @method \Cms\Orm\CmsArticleQuery lessOrEqualsColumnText()
 * @method \Cms\Orm\CmsArticleQuery equalsColumnIndex()
 * @method \Cms\Orm\CmsArticleQuery notEqualsColumnIndex()
 * @method \Cms\Orm\CmsArticleQuery greaterThanColumnIndex()
 * @method \Cms\Orm\CmsArticleQuery lessThanColumnIndex()
 * @method \Cms\Orm\CmsArticleQuery greaterOrEqualsColumnIndex()
 * @method \Cms\Orm\CmsArticleQuery lessOrEqualsColumnIndex()
 * @method \Cms\Orm\CmsArticleQuery equalsColumnActive()
 * @method \Cms\Orm\CmsArticleQuery notEqualsColumnActive()
 * @method \Cms\Orm\CmsArticleQuery greaterThanColumnActive()
 * @method \Cms\Orm\CmsArticleQuery lessThanColumnActive()
 * @method \Cms\Orm\CmsArticleQuery greaterOrEqualsColumnActive()
 * @method \Cms\Orm\CmsArticleQuery lessOrEqualsColumnActive()
 */
class CmsArticleQueryField extends \Mmi\Orm\QueryHelper\QueryField {

}
