<?php

namespace Cms\Orm\QueryHelper;

/**
 * @method \Cms\Orm\CmsAttributeQuery equals($value)
 * @method \Cms\Orm\CmsAttributeQuery notEquals($value)
 * @method \Cms\Orm\CmsAttributeQuery greater($value)
 * @method \Cms\Orm\CmsAttributeQuery less($value)
 * @method \Cms\Orm\CmsAttributeQuery greaterOrEquals($value)
 * @method \Cms\Orm\CmsAttributeQuery lessOrEquals($value)
 * @method \Cms\Orm\CmsAttributeQuery like($value)
 * @method \Cms\Orm\CmsAttributeQuery ilike($value)
 * @method \Cms\Orm\CmsAttributeQuery between($from, $to)
 * @method \Cms\Orm\CmsAttributeQuery equalsColumnId()
 * @method \Cms\Orm\CmsAttributeQuery notEqualsColumnId()
 * @method \Cms\Orm\CmsAttributeQuery greaterThanColumnId()
 * @method \Cms\Orm\CmsAttributeQuery lessThanColumnId()
 * @method \Cms\Orm\CmsAttributeQuery greaterOrEqualsColumnId()
 * @method \Cms\Orm\CmsAttributeQuery lessOrEqualsColumnId()
 * @method \Cms\Orm\CmsAttributeQuery equalsColumnCmsAttributeTypeId()
 * @method \Cms\Orm\CmsAttributeQuery notEqualsColumnCmsAttributeTypeId()
 * @method \Cms\Orm\CmsAttributeQuery greaterThanColumnCmsAttributeTypeId()
 * @method \Cms\Orm\CmsAttributeQuery lessThanColumnCmsAttributeTypeId()
 * @method \Cms\Orm\CmsAttributeQuery greaterOrEqualsColumnCmsAttributeTypeId()
 * @method \Cms\Orm\CmsAttributeQuery lessOrEqualsColumnCmsAttributeTypeId()
 * @method \Cms\Orm\CmsAttributeQuery equalsColumnLang()
 * @method \Cms\Orm\CmsAttributeQuery notEqualsColumnLang()
 * @method \Cms\Orm\CmsAttributeQuery greaterThanColumnLang()
 * @method \Cms\Orm\CmsAttributeQuery lessThanColumnLang()
 * @method \Cms\Orm\CmsAttributeQuery greaterOrEqualsColumnLang()
 * @method \Cms\Orm\CmsAttributeQuery lessOrEqualsColumnLang()
 * @method \Cms\Orm\CmsAttributeQuery equalsColumnName()
 * @method \Cms\Orm\CmsAttributeQuery notEqualsColumnName()
 * @method \Cms\Orm\CmsAttributeQuery greaterThanColumnName()
 * @method \Cms\Orm\CmsAttributeQuery lessThanColumnName()
 * @method \Cms\Orm\CmsAttributeQuery greaterOrEqualsColumnName()
 * @method \Cms\Orm\CmsAttributeQuery lessOrEqualsColumnName()
 * @method \Cms\Orm\CmsAttributeQuery equalsColumnKey()
 * @method \Cms\Orm\CmsAttributeQuery notEqualsColumnKey()
 * @method \Cms\Orm\CmsAttributeQuery greaterThanColumnKey()
 * @method \Cms\Orm\CmsAttributeQuery lessThanColumnKey()
 * @method \Cms\Orm\CmsAttributeQuery greaterOrEqualsColumnKey()
 * @method \Cms\Orm\CmsAttributeQuery lessOrEqualsColumnKey()
 * @method \Cms\Orm\CmsAttributeQuery equalsColumnDescription()
 * @method \Cms\Orm\CmsAttributeQuery notEqualsColumnDescription()
 * @method \Cms\Orm\CmsAttributeQuery greaterThanColumnDescription()
 * @method \Cms\Orm\CmsAttributeQuery lessThanColumnDescription()
 * @method \Cms\Orm\CmsAttributeQuery greaterOrEqualsColumnDescription()
 * @method \Cms\Orm\CmsAttributeQuery lessOrEqualsColumnDescription()
 * @method \Cms\Orm\CmsAttributeQuery equalsColumnFieldOptions()
 * @method \Cms\Orm\CmsAttributeQuery notEqualsColumnFieldOptions()
 * @method \Cms\Orm\CmsAttributeQuery greaterThanColumnFieldOptions()
 * @method \Cms\Orm\CmsAttributeQuery lessThanColumnFieldOptions()
 * @method \Cms\Orm\CmsAttributeQuery greaterOrEqualsColumnFieldOptions()
 * @method \Cms\Orm\CmsAttributeQuery lessOrEqualsColumnFieldOptions()
 * @method \Cms\Orm\CmsAttributeQuery equalsColumnIndexWeight()
 * @method \Cms\Orm\CmsAttributeQuery notEqualsColumnIndexWeight()
 * @method \Cms\Orm\CmsAttributeQuery greaterThanColumnIndexWeight()
 * @method \Cms\Orm\CmsAttributeQuery lessThanColumnIndexWeight()
 * @method \Cms\Orm\CmsAttributeQuery greaterOrEqualsColumnIndexWeight()
 * @method \Cms\Orm\CmsAttributeQuery lessOrEqualsColumnIndexWeight()
 */
class CmsAttributeQueryField extends \Mmi\Orm\QueryHelper\QueryField {

}
