<?php

namespace Cms\Orm\QueryHelper;

/**
 * @method \Cms\Orm\CmsAuthQuery equals($value)
 * @method \Cms\Orm\CmsAuthQuery notEquals($value)
 * @method \Cms\Orm\CmsAuthQuery greater($value)
 * @method \Cms\Orm\CmsAuthQuery less($value)
 * @method \Cms\Orm\CmsAuthQuery greaterOrEquals($value)
 * @method \Cms\Orm\CmsAuthQuery lessOrEquals($value)
 * @method \Cms\Orm\CmsAuthQuery like($value)
 * @method \Cms\Orm\CmsAuthQuery notLike($value)
 * @method \Cms\Orm\CmsAuthQuery between($from, $to)
 * @method \Cms\Orm\CmsAuthQuery equalsColumnId()
 * @method \Cms\Orm\CmsAuthQuery notEqualsColumnId()
 * @method \Cms\Orm\CmsAuthQuery greaterThanColumnId()
 * @method \Cms\Orm\CmsAuthQuery lessThanColumnId()
 * @method \Cms\Orm\CmsAuthQuery greaterOrEqualsColumnId()
 * @method \Cms\Orm\CmsAuthQuery lessOrEqualsColumnId()
 * @method \Cms\Orm\CmsAuthQuery equalsColumnLang()
 * @method \Cms\Orm\CmsAuthQuery notEqualsColumnLang()
 * @method \Cms\Orm\CmsAuthQuery greaterThanColumnLang()
 * @method \Cms\Orm\CmsAuthQuery lessThanColumnLang()
 * @method \Cms\Orm\CmsAuthQuery greaterOrEqualsColumnLang()
 * @method \Cms\Orm\CmsAuthQuery lessOrEqualsColumnLang()
 * @method \Cms\Orm\CmsAuthQuery equalsColumnName()
 * @method \Cms\Orm\CmsAuthQuery notEqualsColumnName()
 * @method \Cms\Orm\CmsAuthQuery greaterThanColumnName()
 * @method \Cms\Orm\CmsAuthQuery lessThanColumnName()
 * @method \Cms\Orm\CmsAuthQuery greaterOrEqualsColumnName()
 * @method \Cms\Orm\CmsAuthQuery lessOrEqualsColumnName()
 * @method \Cms\Orm\CmsAuthQuery equalsColumnUsername()
 * @method \Cms\Orm\CmsAuthQuery notEqualsColumnUsername()
 * @method \Cms\Orm\CmsAuthQuery greaterThanColumnUsername()
 * @method \Cms\Orm\CmsAuthQuery lessThanColumnUsername()
 * @method \Cms\Orm\CmsAuthQuery greaterOrEqualsColumnUsername()
 * @method \Cms\Orm\CmsAuthQuery lessOrEqualsColumnUsername()
 * @method \Cms\Orm\CmsAuthQuery equalsColumnEmail()
 * @method \Cms\Orm\CmsAuthQuery notEqualsColumnEmail()
 * @method \Cms\Orm\CmsAuthQuery greaterThanColumnEmail()
 * @method \Cms\Orm\CmsAuthQuery lessThanColumnEmail()
 * @method \Cms\Orm\CmsAuthQuery greaterOrEqualsColumnEmail()
 * @method \Cms\Orm\CmsAuthQuery lessOrEqualsColumnEmail()
 * @method \Cms\Orm\CmsAuthQuery equalsColumnPassword()
 * @method \Cms\Orm\CmsAuthQuery notEqualsColumnPassword()
 * @method \Cms\Orm\CmsAuthQuery greaterThanColumnPassword()
 * @method \Cms\Orm\CmsAuthQuery lessThanColumnPassword()
 * @method \Cms\Orm\CmsAuthQuery greaterOrEqualsColumnPassword()
 * @method \Cms\Orm\CmsAuthQuery lessOrEqualsColumnPassword()
 * @method \Cms\Orm\CmsAuthQuery equalsColumnLastIp()
 * @method \Cms\Orm\CmsAuthQuery notEqualsColumnLastIp()
 * @method \Cms\Orm\CmsAuthQuery greaterThanColumnLastIp()
 * @method \Cms\Orm\CmsAuthQuery lessThanColumnLastIp()
 * @method \Cms\Orm\CmsAuthQuery greaterOrEqualsColumnLastIp()
 * @method \Cms\Orm\CmsAuthQuery lessOrEqualsColumnLastIp()
 * @method \Cms\Orm\CmsAuthQuery equalsColumnLastLog()
 * @method \Cms\Orm\CmsAuthQuery notEqualsColumnLastLog()
 * @method \Cms\Orm\CmsAuthQuery greaterThanColumnLastLog()
 * @method \Cms\Orm\CmsAuthQuery lessThanColumnLastLog()
 * @method \Cms\Orm\CmsAuthQuery greaterOrEqualsColumnLastLog()
 * @method \Cms\Orm\CmsAuthQuery lessOrEqualsColumnLastLog()
 * @method \Cms\Orm\CmsAuthQuery equalsColumnLastFailIp()
 * @method \Cms\Orm\CmsAuthQuery notEqualsColumnLastFailIp()
 * @method \Cms\Orm\CmsAuthQuery greaterThanColumnLastFailIp()
 * @method \Cms\Orm\CmsAuthQuery lessThanColumnLastFailIp()
 * @method \Cms\Orm\CmsAuthQuery greaterOrEqualsColumnLastFailIp()
 * @method \Cms\Orm\CmsAuthQuery lessOrEqualsColumnLastFailIp()
 * @method \Cms\Orm\CmsAuthQuery equalsColumnLastFailLog()
 * @method \Cms\Orm\CmsAuthQuery notEqualsColumnLastFailLog()
 * @method \Cms\Orm\CmsAuthQuery greaterThanColumnLastFailLog()
 * @method \Cms\Orm\CmsAuthQuery lessThanColumnLastFailLog()
 * @method \Cms\Orm\CmsAuthQuery greaterOrEqualsColumnLastFailLog()
 * @method \Cms\Orm\CmsAuthQuery lessOrEqualsColumnLastFailLog()
 * @method \Cms\Orm\CmsAuthQuery equalsColumnFailLogCount()
 * @method \Cms\Orm\CmsAuthQuery notEqualsColumnFailLogCount()
 * @method \Cms\Orm\CmsAuthQuery greaterThanColumnFailLogCount()
 * @method \Cms\Orm\CmsAuthQuery lessThanColumnFailLogCount()
 * @method \Cms\Orm\CmsAuthQuery greaterOrEqualsColumnFailLogCount()
 * @method \Cms\Orm\CmsAuthQuery lessOrEqualsColumnFailLogCount()
 * @method \Cms\Orm\CmsAuthQuery equalsColumnLogged()
 * @method \Cms\Orm\CmsAuthQuery notEqualsColumnLogged()
 * @method \Cms\Orm\CmsAuthQuery greaterThanColumnLogged()
 * @method \Cms\Orm\CmsAuthQuery lessThanColumnLogged()
 * @method \Cms\Orm\CmsAuthQuery greaterOrEqualsColumnLogged()
 * @method \Cms\Orm\CmsAuthQuery lessOrEqualsColumnLogged()
 * @method \Cms\Orm\CmsAuthQuery equalsColumnActive()
 * @method \Cms\Orm\CmsAuthQuery notEqualsColumnActive()
 * @method \Cms\Orm\CmsAuthQuery greaterThanColumnActive()
 * @method \Cms\Orm\CmsAuthQuery lessThanColumnActive()
 * @method \Cms\Orm\CmsAuthQuery greaterOrEqualsColumnActive()
 * @method \Cms\Orm\CmsAuthQuery lessOrEqualsColumnActive()
 */
class CmsAuthQueryField extends \Mmi\Orm\QueryHelper\QueryField
{

}
