<?php

namespace Cms\Orm\QueryHelper;

/**
 * @method \Cms\Orm\CmsAttributeTypeQuery equals($value)
 * @method \Cms\Orm\CmsAttributeTypeQuery notEquals($value)
 * @method \Cms\Orm\CmsAttributeTypeQuery greater($value)
 * @method \Cms\Orm\CmsAttributeTypeQuery less($value)
 * @method \Cms\Orm\CmsAttributeTypeQuery greaterOrEquals($value)
 * @method \Cms\Orm\CmsAttributeTypeQuery lessOrEquals($value)
 * @method \Cms\Orm\CmsAttributeTypeQuery like($value)
 * @method \Cms\Orm\CmsAttributeTypeQuery ilike($value)
 * @method \Cms\Orm\CmsAttributeTypeQuery between($from, $to)
 * @method \Cms\Orm\CmsAttributeTypeQuery equalsColumnId()
 * @method \Cms\Orm\CmsAttributeTypeQuery notEqualsColumnId()
 * @method \Cms\Orm\CmsAttributeTypeQuery greaterThanColumnId()
 * @method \Cms\Orm\CmsAttributeTypeQuery lessThanColumnId()
 * @method \Cms\Orm\CmsAttributeTypeQuery greaterOrEqualsColumnId()
 * @method \Cms\Orm\CmsAttributeTypeQuery lessOrEqualsColumnId()
 * @method \Cms\Orm\CmsAttributeTypeQuery equalsColumnName()
 * @method \Cms\Orm\CmsAttributeTypeQuery notEqualsColumnName()
 * @method \Cms\Orm\CmsAttributeTypeQuery greaterThanColumnName()
 * @method \Cms\Orm\CmsAttributeTypeQuery lessThanColumnName()
 * @method \Cms\Orm\CmsAttributeTypeQuery greaterOrEqualsColumnName()
 * @method \Cms\Orm\CmsAttributeTypeQuery lessOrEqualsColumnName()
 * @method \Cms\Orm\CmsAttributeTypeQuery equalsColumnFieldClass()
 * @method \Cms\Orm\CmsAttributeTypeQuery notEqualsColumnFieldClass()
 * @method \Cms\Orm\CmsAttributeTypeQuery greaterThanColumnFieldClass()
 * @method \Cms\Orm\CmsAttributeTypeQuery lessThanColumnFieldClass()
 * @method \Cms\Orm\CmsAttributeTypeQuery greaterOrEqualsColumnFieldClass()
 * @method \Cms\Orm\CmsAttributeTypeQuery lessOrEqualsColumnFieldClass()
 * @method \Cms\Orm\CmsAttributeTypeQuery equalsColumnRestricted()
 * @method \Cms\Orm\CmsAttributeTypeQuery notEqualsColumnRestricted()
 * @method \Cms\Orm\CmsAttributeTypeQuery greaterThanColumnRestricted()
 * @method \Cms\Orm\CmsAttributeTypeQuery lessThanColumnRestricted()
 * @method \Cms\Orm\CmsAttributeTypeQuery greaterOrEqualsColumnRestricted()
 * @method \Cms\Orm\CmsAttributeTypeQuery lessOrEqualsColumnRestricted()
 * @method \Cms\Orm\CmsAttributeTypeQuery equalsColumnMultiple()
 * @method \Cms\Orm\CmsAttributeTypeQuery notEqualsColumnMultiple()
 * @method \Cms\Orm\CmsAttributeTypeQuery greaterThanColumnMultiple()
 * @method \Cms\Orm\CmsAttributeTypeQuery lessThanColumnMultiple()
 * @method \Cms\Orm\CmsAttributeTypeQuery greaterOrEqualsColumnMultiple()
 * @method \Cms\Orm\CmsAttributeTypeQuery lessOrEqualsColumnMultiple()
 * @method \Cms\Orm\CmsAttributeTypeQuery equalsColumnUploader()
 * @method \Cms\Orm\CmsAttributeTypeQuery notEqualsColumnUploader()
 * @method \Cms\Orm\CmsAttributeTypeQuery greaterThanColumnUploader()
 * @method \Cms\Orm\CmsAttributeTypeQuery lessThanColumnUploader()
 * @method \Cms\Orm\CmsAttributeTypeQuery greaterOrEqualsColumnUploader()
 * @method \Cms\Orm\CmsAttributeTypeQuery lessOrEqualsColumnUploader()
 */
class CmsAttributeTypeQueryField extends \Mmi\Orm\QueryHelper\QueryField {

}
