<?php

namespace Cms\Orm\QueryHelper;

/**
 * @method \Cms\Orm\CmsAttributeQuery equals($value)
 * @method \Cms\Orm\CmsAttributeQuery notEquals($value)
 * @method \Cms\Orm\CmsAttributeQuery greater($value)
 * @method \Cms\Orm\CmsAttributeQuery less($value)
 * @method \Cms\Orm\CmsAttributeQuery greaterOrEquals($value)
 * @method \Cms\Orm\CmsAttributeQuery lessOrEquals($value)
 * @method \Cms\Orm\CmsAttributeQuery like($value)
 * @method \Cms\Orm\CmsAttributeQuery ilike($value)
 * @method \Cms\Orm\CmsAttributeQuery between($from, $to)
 * @method \Cms\Orm\CmsAttributeQuery equalsColumnId()
 * @method \Cms\Orm\CmsAttributeQuery notEqualsColumnId()
 * @method \Cms\Orm\CmsAttributeQuery greaterThanColumnId()
 * @method \Cms\Orm\CmsAttributeQuery lessThanColumnId()
 * @method \Cms\Orm\CmsAttributeQuery greaterOrEqualsColumnId()
 * @method \Cms\Orm\CmsAttributeQuery lessOrEqualsColumnId()
 * @method \Cms\Orm\CmsAttributeQuery equalsColumnLang()
 * @method \Cms\Orm\CmsAttributeQuery notEqualsColumnLang()
 * @method \Cms\Orm\CmsAttributeQuery greaterThanColumnLang()
 * @method \Cms\Orm\CmsAttributeQuery lessThanColumnLang()
 * @method \Cms\Orm\CmsAttributeQuery greaterOrEqualsColumnLang()
 * @method \Cms\Orm\CmsAttributeQuery lessOrEqualsColumnLang()
 * @method \Cms\Orm\CmsAttributeQuery equalsColumnName()
 * @method \Cms\Orm\CmsAttributeQuery notEqualsColumnName()
 * @method \Cms\Orm\CmsAttributeQuery greaterThanColumnName()
 * @method \Cms\Orm\CmsAttributeQuery lessThanColumnName()
 * @method \Cms\Orm\CmsAttributeQuery greaterOrEqualsColumnName()
 * @method \Cms\Orm\CmsAttributeQuery lessOrEqualsColumnName()
 * @method \Cms\Orm\CmsAttributeQuery equalsColumnKey()
 * @method \Cms\Orm\CmsAttributeQuery notEqualsColumnKey()
 * @method \Cms\Orm\CmsAttributeQuery greaterThanColumnKey()
 * @method \Cms\Orm\CmsAttributeQuery lessThanColumnKey()
 * @method \Cms\Orm\CmsAttributeQuery greaterOrEqualsColumnKey()
 * @method \Cms\Orm\CmsAttributeQuery lessOrEqualsColumnKey()
 * @method \Cms\Orm\CmsAttributeQuery equalsColumnDescription()
 * @method \Cms\Orm\CmsAttributeQuery notEqualsColumnDescription()
 * @method \Cms\Orm\CmsAttributeQuery greaterThanColumnDescription()
 * @method \Cms\Orm\CmsAttributeQuery lessThanColumnDescription()
 * @method \Cms\Orm\CmsAttributeQuery greaterOrEqualsColumnDescription()
 * @method \Cms\Orm\CmsAttributeQuery lessOrEqualsColumnDescription()
 * @method \Cms\Orm\CmsAttributeQuery equalsColumnFieldClass()
 * @method \Cms\Orm\CmsAttributeQuery notEqualsColumnFieldClass()
 * @method \Cms\Orm\CmsAttributeQuery greaterThanColumnFieldClass()
 * @method \Cms\Orm\CmsAttributeQuery lessThanColumnFieldClass()
 * @method \Cms\Orm\CmsAttributeQuery greaterOrEqualsColumnFieldClass()
 * @method \Cms\Orm\CmsAttributeQuery lessOrEqualsColumnFieldClass()
 * @method \Cms\Orm\CmsAttributeQuery equalsColumnFilterClasses()
 * @method \Cms\Orm\CmsAttributeQuery notEqualsColumnFilterClasses()
 * @method \Cms\Orm\CmsAttributeQuery greaterThanColumnFilterClasses()
 * @method \Cms\Orm\CmsAttributeQuery lessThanColumnFilterClasses()
 * @method \Cms\Orm\CmsAttributeQuery greaterOrEqualsColumnFilterClasses()
 * @method \Cms\Orm\CmsAttributeQuery lessOrEqualsColumnFilterClasses()
 * @method \Cms\Orm\CmsAttributeQuery equalsColumnValidatorClasses()
 * @method \Cms\Orm\CmsAttributeQuery notEqualsColumnValidatorClasses()
 * @method \Cms\Orm\CmsAttributeQuery greaterThanColumnValidatorClasses()
 * @method \Cms\Orm\CmsAttributeQuery lessThanColumnValidatorClasses()
 * @method \Cms\Orm\CmsAttributeQuery greaterOrEqualsColumnValidatorClasses()
 * @method \Cms\Orm\CmsAttributeQuery lessOrEqualsColumnValidatorClasses()
 * @method \Cms\Orm\CmsAttributeQuery equalsColumnIndexWeight()
 * @method \Cms\Orm\CmsAttributeQuery notEqualsColumnIndexWeight()
 * @method \Cms\Orm\CmsAttributeQuery greaterThanColumnIndexWeight()
 * @method \Cms\Orm\CmsAttributeQuery lessThanColumnIndexWeight()
 * @method \Cms\Orm\CmsAttributeQuery greaterOrEqualsColumnIndexWeight()
 * @method \Cms\Orm\CmsAttributeQuery lessOrEqualsColumnIndexWeight()
 * @method \Cms\Orm\CmsAttributeQuery equalsColumnRequired()
 * @method \Cms\Orm\CmsAttributeQuery notEqualsColumnRequired()
 * @method \Cms\Orm\CmsAttributeQuery greaterThanColumnRequired()
 * @method \Cms\Orm\CmsAttributeQuery lessThanColumnRequired()
 * @method \Cms\Orm\CmsAttributeQuery greaterOrEqualsColumnRequired()
 * @method \Cms\Orm\CmsAttributeQuery lessOrEqualsColumnRequired()
 * @method \Cms\Orm\CmsAttributeQuery equalsColumnUnique()
 * @method \Cms\Orm\CmsAttributeQuery notEqualsColumnUnique()
 * @method \Cms\Orm\CmsAttributeQuery greaterThanColumnUnique()
 * @method \Cms\Orm\CmsAttributeQuery lessThanColumnUnique()
 * @method \Cms\Orm\CmsAttributeQuery greaterOrEqualsColumnUnique()
 * @method \Cms\Orm\CmsAttributeQuery lessOrEqualsColumnUnique()
 * @method \Cms\Orm\CmsAttributeQuery equalsColumnMaterialized()
 * @method \Cms\Orm\CmsAttributeQuery notEqualsColumnMaterialized()
 * @method \Cms\Orm\CmsAttributeQuery greaterThanColumnMaterialized()
 * @method \Cms\Orm\CmsAttributeQuery lessThanColumnMaterialized()
 * @method \Cms\Orm\CmsAttributeQuery greaterOrEqualsColumnMaterialized()
 * @method \Cms\Orm\CmsAttributeQuery lessOrEqualsColumnMaterialized()
 */
class CmsAttributeQueryField extends \Mmi\Orm\QueryHelper\QueryField {

}
