<?php

namespace Cms\Orm\QueryHelper;

/**
 * @method \Cms\Orm\CmsAttributeRelationQuery equals($value)
 * @method \Cms\Orm\CmsAttributeRelationQuery notEquals($value)
 * @method \Cms\Orm\CmsAttributeRelationQuery greater($value)
 * @method \Cms\Orm\CmsAttributeRelationQuery less($value)
 * @method \Cms\Orm\CmsAttributeRelationQuery greaterOrEquals($value)
 * @method \Cms\Orm\CmsAttributeRelationQuery lessOrEquals($value)
 * @method \Cms\Orm\CmsAttributeRelationQuery like($value)
 * @method \Cms\Orm\CmsAttributeRelationQuery ilike($value)
 * @method \Cms\Orm\CmsAttributeRelationQuery between($from, $to)
 * @method \Cms\Orm\CmsAttributeRelationQuery equalsColumnId()
 * @method \Cms\Orm\CmsAttributeRelationQuery notEqualsColumnId()
 * @method \Cms\Orm\CmsAttributeRelationQuery greaterThanColumnId()
 * @method \Cms\Orm\CmsAttributeRelationQuery lessThanColumnId()
 * @method \Cms\Orm\CmsAttributeRelationQuery greaterOrEqualsColumnId()
 * @method \Cms\Orm\CmsAttributeRelationQuery lessOrEqualsColumnId()
 * @method \Cms\Orm\CmsAttributeRelationQuery equalsColumnCmsAttributeId()
 * @method \Cms\Orm\CmsAttributeRelationQuery notEqualsColumnCmsAttributeId()
 * @method \Cms\Orm\CmsAttributeRelationQuery greaterThanColumnCmsAttributeId()
 * @method \Cms\Orm\CmsAttributeRelationQuery lessThanColumnCmsAttributeId()
 * @method \Cms\Orm\CmsAttributeRelationQuery greaterOrEqualsColumnCmsAttributeId()
 * @method \Cms\Orm\CmsAttributeRelationQuery lessOrEqualsColumnCmsAttributeId()
 * @method \Cms\Orm\CmsAttributeRelationQuery equalsColumnCmsAttributeValueId()
 * @method \Cms\Orm\CmsAttributeRelationQuery notEqualsColumnCmsAttributeValueId()
 * @method \Cms\Orm\CmsAttributeRelationQuery greaterThanColumnCmsAttributeValueId()
 * @method \Cms\Orm\CmsAttributeRelationQuery lessThanColumnCmsAttributeValueId()
 * @method \Cms\Orm\CmsAttributeRelationQuery greaterOrEqualsColumnCmsAttributeValueId()
 * @method \Cms\Orm\CmsAttributeRelationQuery lessOrEqualsColumnCmsAttributeValueId()
 * @method \Cms\Orm\CmsAttributeRelationQuery equalsColumnObject()
 * @method \Cms\Orm\CmsAttributeRelationQuery notEqualsColumnObject()
 * @method \Cms\Orm\CmsAttributeRelationQuery greaterThanColumnObject()
 * @method \Cms\Orm\CmsAttributeRelationQuery lessThanColumnObject()
 * @method \Cms\Orm\CmsAttributeRelationQuery greaterOrEqualsColumnObject()
 * @method \Cms\Orm\CmsAttributeRelationQuery lessOrEqualsColumnObject()
 * @method \Cms\Orm\CmsAttributeRelationQuery equalsColumnObjectId()
 * @method \Cms\Orm\CmsAttributeRelationQuery notEqualsColumnObjectId()
 * @method \Cms\Orm\CmsAttributeRelationQuery greaterThanColumnObjectId()
 * @method \Cms\Orm\CmsAttributeRelationQuery lessThanColumnObjectId()
 * @method \Cms\Orm\CmsAttributeRelationQuery greaterOrEqualsColumnObjectId()
 * @method \Cms\Orm\CmsAttributeRelationQuery lessOrEqualsColumnObjectId()
 * @method \Cms\Orm\CmsAttributeRelationQuery equalsColumnOrder()
 * @method \Cms\Orm\CmsAttributeRelationQuery notEqualsColumnOrder()
 * @method \Cms\Orm\CmsAttributeRelationQuery greaterThanColumnOrder()
 * @method \Cms\Orm\CmsAttributeRelationQuery lessThanColumnOrder()
 * @method \Cms\Orm\CmsAttributeRelationQuery greaterOrEqualsColumnOrder()
 * @method \Cms\Orm\CmsAttributeRelationQuery lessOrEqualsColumnOrder()
 */
class CmsAttributeRelationQueryField extends \Mmi\Orm\QueryHelper\QueryField {

}
