<?php

namespace Cms\Orm\QueryHelper;

/**
 * @method \Cms\Orm\CmsAclQuery equals($value)
 * @method \Cms\Orm\CmsAclQuery notEquals($value)
 * @method \Cms\Orm\CmsAclQuery greater($value)
 * @method \Cms\Orm\CmsAclQuery less($value)
 * @method \Cms\Orm\CmsAclQuery greaterOrEquals($value)
 * @method \Cms\Orm\CmsAclQuery lessOrEquals($value)
 * @method \Cms\Orm\CmsAclQuery like($value)
 * @method \Cms\Orm\CmsAclQuery notLike($value)
 * @method \Cms\Orm\CmsAclQuery between($from, $to)
 * @method \Cms\Orm\CmsAclQuery equalsColumnId()
 * @method \Cms\Orm\CmsAclQuery notEqualsColumnId()
 * @method \Cms\Orm\CmsAclQuery greaterThanColumnId()
 * @method \Cms\Orm\CmsAclQuery lessThanColumnId()
 * @method \Cms\Orm\CmsAclQuery greaterOrEqualsColumnId()
 * @method \Cms\Orm\CmsAclQuery lessOrEqualsColumnId()
 * @method \Cms\Orm\CmsAclQuery equalsColumnCmsRoleId()
 * @method \Cms\Orm\CmsAclQuery notEqualsColumnCmsRoleId()
 * @method \Cms\Orm\CmsAclQuery greaterThanColumnCmsRoleId()
 * @method \Cms\Orm\CmsAclQuery lessThanColumnCmsRoleId()
 * @method \Cms\Orm\CmsAclQuery greaterOrEqualsColumnCmsRoleId()
 * @method \Cms\Orm\CmsAclQuery lessOrEqualsColumnCmsRoleId()
 * @method \Cms\Orm\CmsAclQuery equalsColumnModule()
 * @method \Cms\Orm\CmsAclQuery notEqualsColumnModule()
 * @method \Cms\Orm\CmsAclQuery greaterThanColumnModule()
 * @method \Cms\Orm\CmsAclQuery lessThanColumnModule()
 * @method \Cms\Orm\CmsAclQuery greaterOrEqualsColumnModule()
 * @method \Cms\Orm\CmsAclQuery lessOrEqualsColumnModule()
 * @method \Cms\Orm\CmsAclQuery equalsColumnController()
 * @method \Cms\Orm\CmsAclQuery notEqualsColumnController()
 * @method \Cms\Orm\CmsAclQuery greaterThanColumnController()
 * @method \Cms\Orm\CmsAclQuery lessThanColumnController()
 * @method \Cms\Orm\CmsAclQuery greaterOrEqualsColumnController()
 * @method \Cms\Orm\CmsAclQuery lessOrEqualsColumnController()
 * @method \Cms\Orm\CmsAclQuery equalsColumnAction()
 * @method \Cms\Orm\CmsAclQuery notEqualsColumnAction()
 * @method \Cms\Orm\CmsAclQuery greaterThanColumnAction()
 * @method \Cms\Orm\CmsAclQuery lessThanColumnAction()
 * @method \Cms\Orm\CmsAclQuery greaterOrEqualsColumnAction()
 * @method \Cms\Orm\CmsAclQuery lessOrEqualsColumnAction()
 * @method \Cms\Orm\CmsAclQuery equalsColumnAccess()
 * @method \Cms\Orm\CmsAclQuery notEqualsColumnAccess()
 * @method \Cms\Orm\CmsAclQuery greaterThanColumnAccess()
 * @method \Cms\Orm\CmsAclQuery lessThanColumnAccess()
 * @method \Cms\Orm\CmsAclQuery greaterOrEqualsColumnAccess()
 * @method \Cms\Orm\CmsAclQuery lessOrEqualsColumnAccess()
 */
class CmsAclQueryField extends \Mmi\Orm\QueryHelper\QueryField
{

}
