<?php

namespace Cms\Orm\QueryHelper;

/**
 * @method \Cms\Orm\CmsBlockQuery equals($value)
 * @method \Cms\Orm\CmsBlockQuery notEquals($value)
 * @method \Cms\Orm\CmsBlockQuery greater($value)
 * @method \Cms\Orm\CmsBlockQuery less($value)
 * @method \Cms\Orm\CmsBlockQuery greaterOrEquals($value)
 * @method \Cms\Orm\CmsBlockQuery lessOrEquals($value)
 * @method \Cms\Orm\CmsBlockQuery like($value)
 * @method \Cms\Orm\CmsBlockQuery ilike($value)
 * @method \Cms\Orm\CmsBlockQuery between($from, $to)
 * @method \Cms\Orm\CmsBlockQuery equalsColumnId()
 * @method \Cms\Orm\CmsBlockQuery notEqualsColumnId()
 * @method \Cms\Orm\CmsBlockQuery greaterThanColumnId()
 * @method \Cms\Orm\CmsBlockQuery lessThanColumnId()
 * @method \Cms\Orm\CmsBlockQuery greaterOrEqualsColumnId()
 * @method \Cms\Orm\CmsBlockQuery lessOrEqualsColumnId()
 * @method \Cms\Orm\CmsBlockQuery equalsColumnLang()
 * @method \Cms\Orm\CmsBlockQuery notEqualsColumnLang()
 * @method \Cms\Orm\CmsBlockQuery greaterThanColumnLang()
 * @method \Cms\Orm\CmsBlockQuery lessThanColumnLang()
 * @method \Cms\Orm\CmsBlockQuery greaterOrEqualsColumnLang()
 * @method \Cms\Orm\CmsBlockQuery lessOrEqualsColumnLang()
 * @method \Cms\Orm\CmsBlockQuery equalsColumnTitle()
 * @method \Cms\Orm\CmsBlockQuery notEqualsColumnTitle()
 * @method \Cms\Orm\CmsBlockQuery greaterThanColumnTitle()
 * @method \Cms\Orm\CmsBlockQuery lessThanColumnTitle()
 * @method \Cms\Orm\CmsBlockQuery greaterOrEqualsColumnTitle()
 * @method \Cms\Orm\CmsBlockQuery lessOrEqualsColumnTitle()
 * @method \Cms\Orm\CmsBlockQuery equalsColumnLead()
 * @method \Cms\Orm\CmsBlockQuery notEqualsColumnLead()
 * @method \Cms\Orm\CmsBlockQuery greaterThanColumnLead()
 * @method \Cms\Orm\CmsBlockQuery lessThanColumnLead()
 * @method \Cms\Orm\CmsBlockQuery greaterOrEqualsColumnLead()
 * @method \Cms\Orm\CmsBlockQuery lessOrEqualsColumnLead()
 * @method \Cms\Orm\CmsBlockQuery equalsColumnText()
 * @method \Cms\Orm\CmsBlockQuery notEqualsColumnText()
 * @method \Cms\Orm\CmsBlockQuery greaterThanColumnText()
 * @method \Cms\Orm\CmsBlockQuery lessThanColumnText()
 * @method \Cms\Orm\CmsBlockQuery greaterOrEqualsColumnText()
 * @method \Cms\Orm\CmsBlockQuery lessOrEqualsColumnText()
 * @method \Cms\Orm\CmsBlockQuery equalsColumnObject()
 * @method \Cms\Orm\CmsBlockQuery notEqualsColumnObject()
 * @method \Cms\Orm\CmsBlockQuery greaterThanColumnObject()
 * @method \Cms\Orm\CmsBlockQuery lessThanColumnObject()
 * @method \Cms\Orm\CmsBlockQuery greaterOrEqualsColumnObject()
 * @method \Cms\Orm\CmsBlockQuery lessOrEqualsColumnObject()
 * @method \Cms\Orm\CmsBlockQuery equalsColumnObjectId()
 * @method \Cms\Orm\CmsBlockQuery notEqualsColumnObjectId()
 * @method \Cms\Orm\CmsBlockQuery greaterThanColumnObjectId()
 * @method \Cms\Orm\CmsBlockQuery lessThanColumnObjectId()
 * @method \Cms\Orm\CmsBlockQuery greaterOrEqualsColumnObjectId()
 * @method \Cms\Orm\CmsBlockQuery lessOrEqualsColumnObjectId()
 * @method \Cms\Orm\CmsBlockQuery equalsColumnDateAdd()
 * @method \Cms\Orm\CmsBlockQuery notEqualsColumnDateAdd()
 * @method \Cms\Orm\CmsBlockQuery greaterThanColumnDateAdd()
 * @method \Cms\Orm\CmsBlockQuery lessThanColumnDateAdd()
 * @method \Cms\Orm\CmsBlockQuery greaterOrEqualsColumnDateAdd()
 * @method \Cms\Orm\CmsBlockQuery lessOrEqualsColumnDateAdd()
 * @method \Cms\Orm\CmsBlockQuery equalsColumnDateModify()
 * @method \Cms\Orm\CmsBlockQuery notEqualsColumnDateModify()
 * @method \Cms\Orm\CmsBlockQuery greaterThanColumnDateModify()
 * @method \Cms\Orm\CmsBlockQuery lessThanColumnDateModify()
 * @method \Cms\Orm\CmsBlockQuery greaterOrEqualsColumnDateModify()
 * @method \Cms\Orm\CmsBlockQuery lessOrEqualsColumnDateModify()
 */
class CmsBlockQueryField extends \Mmi\Orm\QueryHelper\QueryField {

}
