<?php

namespace Cms\Orm\QueryHelper;

/**
 * @method \Cms\Orm\CmsContactQuery equals($value)
 * @method \Cms\Orm\CmsContactQuery notEquals($value)
 * @method \Cms\Orm\CmsContactQuery greater($value)
 * @method \Cms\Orm\CmsContactQuery less($value)
 * @method \Cms\Orm\CmsContactQuery greaterOrEquals($value)
 * @method \Cms\Orm\CmsContactQuery lessOrEquals($value)
 * @method \Cms\Orm\CmsContactQuery like($value)
 * @method \Cms\Orm\CmsContactQuery ilike($value)
 * @method \Cms\Orm\CmsContactQuery equalsColumnId()
 * @method \Cms\Orm\CmsContactQuery notEqualsColumnId()
 * @method \Cms\Orm\CmsContactQuery greaterThanColumnId()
 * @method \Cms\Orm\CmsContactQuery lessThanColumnId()
 * @method \Cms\Orm\CmsContactQuery greaterOrEqualsColumnId()
 * @method \Cms\Orm\CmsContactQuery lessOrEqualsColumnId()
 * @method \Cms\Orm\CmsContactQuery equalsColumnCmsContactOptionId()
 * @method \Cms\Orm\CmsContactQuery notEqualsColumnCmsContactOptionId()
 * @method \Cms\Orm\CmsContactQuery greaterThanColumnCmsContactOptionId()
 * @method \Cms\Orm\CmsContactQuery lessThanColumnCmsContactOptionId()
 * @method \Cms\Orm\CmsContactQuery greaterOrEqualsColumnCmsContactOptionId()
 * @method \Cms\Orm\CmsContactQuery lessOrEqualsColumnCmsContactOptionId()
 * @method \Cms\Orm\CmsContactQuery equalsColumnDateAdd()
 * @method \Cms\Orm\CmsContactQuery notEqualsColumnDateAdd()
 * @method \Cms\Orm\CmsContactQuery greaterThanColumnDateAdd()
 * @method \Cms\Orm\CmsContactQuery lessThanColumnDateAdd()
 * @method \Cms\Orm\CmsContactQuery greaterOrEqualsColumnDateAdd()
 * @method \Cms\Orm\CmsContactQuery lessOrEqualsColumnDateAdd()
 * @method \Cms\Orm\CmsContactQuery equalsColumnText()
 * @method \Cms\Orm\CmsContactQuery notEqualsColumnText()
 * @method \Cms\Orm\CmsContactQuery greaterThanColumnText()
 * @method \Cms\Orm\CmsContactQuery lessThanColumnText()
 * @method \Cms\Orm\CmsContactQuery greaterOrEqualsColumnText()
 * @method \Cms\Orm\CmsContactQuery lessOrEqualsColumnText()
 * @method \Cms\Orm\CmsContactQuery equalsColumnReply()
 * @method \Cms\Orm\CmsContactQuery notEqualsColumnReply()
 * @method \Cms\Orm\CmsContactQuery greaterThanColumnReply()
 * @method \Cms\Orm\CmsContactQuery lessThanColumnReply()
 * @method \Cms\Orm\CmsContactQuery greaterOrEqualsColumnReply()
 * @method \Cms\Orm\CmsContactQuery lessOrEqualsColumnReply()
 * @method \Cms\Orm\CmsContactQuery equalsColumnCmsAuthIdReply()
 * @method \Cms\Orm\CmsContactQuery notEqualsColumnCmsAuthIdReply()
 * @method \Cms\Orm\CmsContactQuery greaterThanColumnCmsAuthIdReply()
 * @method \Cms\Orm\CmsContactQuery lessThanColumnCmsAuthIdReply()
 * @method \Cms\Orm\CmsContactQuery greaterOrEqualsColumnCmsAuthIdReply()
 * @method \Cms\Orm\CmsContactQuery lessOrEqualsColumnCmsAuthIdReply()
 * @method \Cms\Orm\CmsContactQuery equalsColumnUri()
 * @method \Cms\Orm\CmsContactQuery notEqualsColumnUri()
 * @method \Cms\Orm\CmsContactQuery greaterThanColumnUri()
 * @method \Cms\Orm\CmsContactQuery lessThanColumnUri()
 * @method \Cms\Orm\CmsContactQuery greaterOrEqualsColumnUri()
 * @method \Cms\Orm\CmsContactQuery lessOrEqualsColumnUri()
 * @method \Cms\Orm\CmsContactQuery equalsColumnName()
 * @method \Cms\Orm\CmsContactQuery notEqualsColumnName()
 * @method \Cms\Orm\CmsContactQuery greaterThanColumnName()
 * @method \Cms\Orm\CmsContactQuery lessThanColumnName()
 * @method \Cms\Orm\CmsContactQuery greaterOrEqualsColumnName()
 * @method \Cms\Orm\CmsContactQuery lessOrEqualsColumnName()
 * @method \Cms\Orm\CmsContactQuery equalsColumnPhone()
 * @method \Cms\Orm\CmsContactQuery notEqualsColumnPhone()
 * @method \Cms\Orm\CmsContactQuery greaterThanColumnPhone()
 * @method \Cms\Orm\CmsContactQuery lessThanColumnPhone()
 * @method \Cms\Orm\CmsContactQuery greaterOrEqualsColumnPhone()
 * @method \Cms\Orm\CmsContactQuery lessOrEqualsColumnPhone()
 * @method \Cms\Orm\CmsContactQuery equalsColumnEmail()
 * @method \Cms\Orm\CmsContactQuery notEqualsColumnEmail()
 * @method \Cms\Orm\CmsContactQuery greaterThanColumnEmail()
 * @method \Cms\Orm\CmsContactQuery lessThanColumnEmail()
 * @method \Cms\Orm\CmsContactQuery greaterOrEqualsColumnEmail()
 * @method \Cms\Orm\CmsContactQuery lessOrEqualsColumnEmail()
 * @method \Cms\Orm\CmsContactQuery equalsColumnIp()
 * @method \Cms\Orm\CmsContactQuery notEqualsColumnIp()
 * @method \Cms\Orm\CmsContactQuery greaterThanColumnIp()
 * @method \Cms\Orm\CmsContactQuery lessThanColumnIp()
 * @method \Cms\Orm\CmsContactQuery greaterOrEqualsColumnIp()
 * @method \Cms\Orm\CmsContactQuery lessOrEqualsColumnIp()
 * @method \Cms\Orm\CmsContactQuery equalsColumnCmsAuthId()
 * @method \Cms\Orm\CmsContactQuery notEqualsColumnCmsAuthId()
 * @method \Cms\Orm\CmsContactQuery greaterThanColumnCmsAuthId()
 * @method \Cms\Orm\CmsContactQuery lessThanColumnCmsAuthId()
 * @method \Cms\Orm\CmsContactQuery greaterOrEqualsColumnCmsAuthId()
 * @method \Cms\Orm\CmsContactQuery lessOrEqualsColumnCmsAuthId()
 * @method \Cms\Orm\CmsContactQuery equalsColumnActive()
 * @method \Cms\Orm\CmsContactQuery notEqualsColumnActive()
 * @method \Cms\Orm\CmsContactQuery greaterThanColumnActive()
 * @method \Cms\Orm\CmsContactQuery lessThanColumnActive()
 * @method \Cms\Orm\CmsContactQuery greaterOrEqualsColumnActive()
 * @method \Cms\Orm\CmsContactQuery lessOrEqualsColumnActive()
 */
class CmsContactQueryField extends \Mmi\Orm\QueryHelper\QueryField {

}
