<?php

namespace Cms\Orm\QueryHelper;

/**
 * @method \Cms\Orm\CmsCategoryQuery equals($value)
 * @method \Cms\Orm\CmsCategoryQuery notEquals($value)
 * @method \Cms\Orm\CmsCategoryQuery greater($value)
 * @method \Cms\Orm\CmsCategoryQuery less($value)
 * @method \Cms\Orm\CmsCategoryQuery greaterOrEquals($value)
 * @method \Cms\Orm\CmsCategoryQuery lessOrEquals($value)
 * @method \Cms\Orm\CmsCategoryQuery like($value)
 * @method \Cms\Orm\CmsCategoryQuery ilike($value)
 * @method \Cms\Orm\CmsCategoryQuery between($from, $to)
 * @method \Cms\Orm\CmsCategoryQuery equalsColumnId()
 * @method \Cms\Orm\CmsCategoryQuery notEqualsColumnId()
 * @method \Cms\Orm\CmsCategoryQuery greaterThanColumnId()
 * @method \Cms\Orm\CmsCategoryQuery lessThanColumnId()
 * @method \Cms\Orm\CmsCategoryQuery greaterOrEqualsColumnId()
 * @method \Cms\Orm\CmsCategoryQuery lessOrEqualsColumnId()
 * @method \Cms\Orm\CmsCategoryQuery equalsColumnLang()
 * @method \Cms\Orm\CmsCategoryQuery notEqualsColumnLang()
 * @method \Cms\Orm\CmsCategoryQuery greaterThanColumnLang()
 * @method \Cms\Orm\CmsCategoryQuery lessThanColumnLang()
 * @method \Cms\Orm\CmsCategoryQuery greaterOrEqualsColumnLang()
 * @method \Cms\Orm\CmsCategoryQuery lessOrEqualsColumnLang()
 * @method \Cms\Orm\CmsCategoryQuery equalsColumnName()
 * @method \Cms\Orm\CmsCategoryQuery notEqualsColumnName()
 * @method \Cms\Orm\CmsCategoryQuery greaterThanColumnName()
 * @method \Cms\Orm\CmsCategoryQuery lessThanColumnName()
 * @method \Cms\Orm\CmsCategoryQuery greaterOrEqualsColumnName()
 * @method \Cms\Orm\CmsCategoryQuery lessOrEqualsColumnName()
 * @method \Cms\Orm\CmsCategoryQuery equalsColumnDescription()
 * @method \Cms\Orm\CmsCategoryQuery notEqualsColumnDescription()
 * @method \Cms\Orm\CmsCategoryQuery greaterThanColumnDescription()
 * @method \Cms\Orm\CmsCategoryQuery lessThanColumnDescription()
 * @method \Cms\Orm\CmsCategoryQuery greaterOrEqualsColumnDescription()
 * @method \Cms\Orm\CmsCategoryQuery lessOrEqualsColumnDescription()
 * @method \Cms\Orm\CmsCategoryQuery equalsColumnUri()
 * @method \Cms\Orm\CmsCategoryQuery notEqualsColumnUri()
 * @method \Cms\Orm\CmsCategoryQuery greaterThanColumnUri()
 * @method \Cms\Orm\CmsCategoryQuery lessThanColumnUri()
 * @method \Cms\Orm\CmsCategoryQuery greaterOrEqualsColumnUri()
 * @method \Cms\Orm\CmsCategoryQuery lessOrEqualsColumnUri()
 * @method \Cms\Orm\CmsCategoryQuery equalsColumnCode()
 * @method \Cms\Orm\CmsCategoryQuery notEqualsColumnCode()
 * @method \Cms\Orm\CmsCategoryQuery greaterThanColumnCode()
 * @method \Cms\Orm\CmsCategoryQuery lessThanColumnCode()
 * @method \Cms\Orm\CmsCategoryQuery greaterOrEqualsColumnCode()
 * @method \Cms\Orm\CmsCategoryQuery lessOrEqualsColumnCode()
 * @method \Cms\Orm\CmsCategoryQuery equalsColumnParentId()
 * @method \Cms\Orm\CmsCategoryQuery notEqualsColumnParentId()
 * @method \Cms\Orm\CmsCategoryQuery greaterThanColumnParentId()
 * @method \Cms\Orm\CmsCategoryQuery lessThanColumnParentId()
 * @method \Cms\Orm\CmsCategoryQuery greaterOrEqualsColumnParentId()
 * @method \Cms\Orm\CmsCategoryQuery lessOrEqualsColumnParentId()
 * @method \Cms\Orm\CmsCategoryQuery equalsColumnOrder()
 * @method \Cms\Orm\CmsCategoryQuery notEqualsColumnOrder()
 * @method \Cms\Orm\CmsCategoryQuery greaterThanColumnOrder()
 * @method \Cms\Orm\CmsCategoryQuery lessThanColumnOrder()
 * @method \Cms\Orm\CmsCategoryQuery greaterOrEqualsColumnOrder()
 * @method \Cms\Orm\CmsCategoryQuery lessOrEqualsColumnOrder()
 * @method \Cms\Orm\CmsCategoryQuery equalsColumnDateAdd()
 * @method \Cms\Orm\CmsCategoryQuery notEqualsColumnDateAdd()
 * @method \Cms\Orm\CmsCategoryQuery greaterThanColumnDateAdd()
 * @method \Cms\Orm\CmsCategoryQuery lessThanColumnDateAdd()
 * @method \Cms\Orm\CmsCategoryQuery greaterOrEqualsColumnDateAdd()
 * @method \Cms\Orm\CmsCategoryQuery lessOrEqualsColumnDateAdd()
 * @method \Cms\Orm\CmsCategoryQuery equalsColumnDateModify()
 * @method \Cms\Orm\CmsCategoryQuery notEqualsColumnDateModify()
 * @method \Cms\Orm\CmsCategoryQuery greaterThanColumnDateModify()
 * @method \Cms\Orm\CmsCategoryQuery lessThanColumnDateModify()
 * @method \Cms\Orm\CmsCategoryQuery greaterOrEqualsColumnDateModify()
 * @method \Cms\Orm\CmsCategoryQuery lessOrEqualsColumnDateModify()
 * @method \Cms\Orm\CmsCategoryQuery equalsColumnActive()
 * @method \Cms\Orm\CmsCategoryQuery notEqualsColumnActive()
 * @method \Cms\Orm\CmsCategoryQuery greaterThanColumnActive()
 * @method \Cms\Orm\CmsCategoryQuery lessThanColumnActive()
 * @method \Cms\Orm\CmsCategoryQuery greaterOrEqualsColumnActive()
 * @method \Cms\Orm\CmsCategoryQuery lessOrEqualsColumnActive()
 */
class CmsCategoryQueryField extends \Mmi\Orm\QueryHelper\QueryField {

}
