<?php

namespace Cms\Orm\QueryHelper;

/**
 * @method \Cms\Orm\CmsCommentQuery equals($value)
 * @method \Cms\Orm\CmsCommentQuery notEquals($value)
 * @method \Cms\Orm\CmsCommentQuery greater($value)
 * @method \Cms\Orm\CmsCommentQuery less($value)
 * @method \Cms\Orm\CmsCommentQuery greaterOrEquals($value)
 * @method \Cms\Orm\CmsCommentQuery lessOrEquals($value)
 * @method \Cms\Orm\CmsCommentQuery like($value)
 * @method \Cms\Orm\CmsCommentQuery ilike($value)
 * @method \Cms\Orm\CmsCommentQuery between($from, $to)
 * @method \Cms\Orm\CmsCommentQuery equalsColumnId()
 * @method \Cms\Orm\CmsCommentQuery notEqualsColumnId()
 * @method \Cms\Orm\CmsCommentQuery greaterThanColumnId()
 * @method \Cms\Orm\CmsCommentQuery lessThanColumnId()
 * @method \Cms\Orm\CmsCommentQuery greaterOrEqualsColumnId()
 * @method \Cms\Orm\CmsCommentQuery lessOrEqualsColumnId()
 * @method \Cms\Orm\CmsCommentQuery equalsColumnCmsAuthId()
 * @method \Cms\Orm\CmsCommentQuery notEqualsColumnCmsAuthId()
 * @method \Cms\Orm\CmsCommentQuery greaterThanColumnCmsAuthId()
 * @method \Cms\Orm\CmsCommentQuery lessThanColumnCmsAuthId()
 * @method \Cms\Orm\CmsCommentQuery greaterOrEqualsColumnCmsAuthId()
 * @method \Cms\Orm\CmsCommentQuery lessOrEqualsColumnCmsAuthId()
 * @method \Cms\Orm\CmsCommentQuery equalsColumnParentId()
 * @method \Cms\Orm\CmsCommentQuery notEqualsColumnParentId()
 * @method \Cms\Orm\CmsCommentQuery greaterThanColumnParentId()
 * @method \Cms\Orm\CmsCommentQuery lessThanColumnParentId()
 * @method \Cms\Orm\CmsCommentQuery greaterOrEqualsColumnParentId()
 * @method \Cms\Orm\CmsCommentQuery lessOrEqualsColumnParentId()
 * @method \Cms\Orm\CmsCommentQuery equalsColumnDateAdd()
 * @method \Cms\Orm\CmsCommentQuery notEqualsColumnDateAdd()
 * @method \Cms\Orm\CmsCommentQuery greaterThanColumnDateAdd()
 * @method \Cms\Orm\CmsCommentQuery lessThanColumnDateAdd()
 * @method \Cms\Orm\CmsCommentQuery greaterOrEqualsColumnDateAdd()
 * @method \Cms\Orm\CmsCommentQuery lessOrEqualsColumnDateAdd()
 * @method \Cms\Orm\CmsCommentQuery equalsColumnTitle()
 * @method \Cms\Orm\CmsCommentQuery notEqualsColumnTitle()
 * @method \Cms\Orm\CmsCommentQuery greaterThanColumnTitle()
 * @method \Cms\Orm\CmsCommentQuery lessThanColumnTitle()
 * @method \Cms\Orm\CmsCommentQuery greaterOrEqualsColumnTitle()
 * @method \Cms\Orm\CmsCommentQuery lessOrEqualsColumnTitle()
 * @method \Cms\Orm\CmsCommentQuery equalsColumnText()
 * @method \Cms\Orm\CmsCommentQuery notEqualsColumnText()
 * @method \Cms\Orm\CmsCommentQuery greaterThanColumnText()
 * @method \Cms\Orm\CmsCommentQuery lessThanColumnText()
 * @method \Cms\Orm\CmsCommentQuery greaterOrEqualsColumnText()
 * @method \Cms\Orm\CmsCommentQuery lessOrEqualsColumnText()
 * @method \Cms\Orm\CmsCommentQuery equalsColumnSignature()
 * @method \Cms\Orm\CmsCommentQuery notEqualsColumnSignature()
 * @method \Cms\Orm\CmsCommentQuery greaterThanColumnSignature()
 * @method \Cms\Orm\CmsCommentQuery lessThanColumnSignature()
 * @method \Cms\Orm\CmsCommentQuery greaterOrEqualsColumnSignature()
 * @method \Cms\Orm\CmsCommentQuery lessOrEqualsColumnSignature()
 * @method \Cms\Orm\CmsCommentQuery equalsColumnIp()
 * @method \Cms\Orm\CmsCommentQuery notEqualsColumnIp()
 * @method \Cms\Orm\CmsCommentQuery greaterThanColumnIp()
 * @method \Cms\Orm\CmsCommentQuery lessThanColumnIp()
 * @method \Cms\Orm\CmsCommentQuery greaterOrEqualsColumnIp()
 * @method \Cms\Orm\CmsCommentQuery lessOrEqualsColumnIp()
 * @method \Cms\Orm\CmsCommentQuery equalsColumnStars()
 * @method \Cms\Orm\CmsCommentQuery notEqualsColumnStars()
 * @method \Cms\Orm\CmsCommentQuery greaterThanColumnStars()
 * @method \Cms\Orm\CmsCommentQuery lessThanColumnStars()
 * @method \Cms\Orm\CmsCommentQuery greaterOrEqualsColumnStars()
 * @method \Cms\Orm\CmsCommentQuery lessOrEqualsColumnStars()
 * @method \Cms\Orm\CmsCommentQuery equalsColumnObject()
 * @method \Cms\Orm\CmsCommentQuery notEqualsColumnObject()
 * @method \Cms\Orm\CmsCommentQuery greaterThanColumnObject()
 * @method \Cms\Orm\CmsCommentQuery lessThanColumnObject()
 * @method \Cms\Orm\CmsCommentQuery greaterOrEqualsColumnObject()
 * @method \Cms\Orm\CmsCommentQuery lessOrEqualsColumnObject()
 * @method \Cms\Orm\CmsCommentQuery equalsColumnObjectId()
 * @method \Cms\Orm\CmsCommentQuery notEqualsColumnObjectId()
 * @method \Cms\Orm\CmsCommentQuery greaterThanColumnObjectId()
 * @method \Cms\Orm\CmsCommentQuery lessThanColumnObjectId()
 * @method \Cms\Orm\CmsCommentQuery greaterOrEqualsColumnObjectId()
 * @method \Cms\Orm\CmsCommentQuery lessOrEqualsColumnObjectId()
 */
class CmsCommentQueryField extends \Mmi\Orm\QueryHelper\QueryField
{
    
}
