<?php

namespace Cms\Orm\QueryHelper;

/**
 * @method \Cms\Orm\CmsCategoryWidgetCategoryQuery equals($value)
 * @method \Cms\Orm\CmsCategoryWidgetCategoryQuery notEquals($value)
 * @method \Cms\Orm\CmsCategoryWidgetCategoryQuery greater($value)
 * @method \Cms\Orm\CmsCategoryWidgetCategoryQuery less($value)
 * @method \Cms\Orm\CmsCategoryWidgetCategoryQuery greaterOrEquals($value)
 * @method \Cms\Orm\CmsCategoryWidgetCategoryQuery lessOrEquals($value)
 * @method \Cms\Orm\CmsCategoryWidgetCategoryQuery like($value)
 * @method \Cms\Orm\CmsCategoryWidgetCategoryQuery notLike($value)
 * @method \Cms\Orm\CmsCategoryWidgetCategoryQuery between($from, $to)
 * @method \Cms\Orm\CmsCategoryWidgetCategoryQuery equalsColumnId()
 * @method \Cms\Orm\CmsCategoryWidgetCategoryQuery notEqualsColumnId()
 * @method \Cms\Orm\CmsCategoryWidgetCategoryQuery greaterThanColumnId()
 * @method \Cms\Orm\CmsCategoryWidgetCategoryQuery lessThanColumnId()
 * @method \Cms\Orm\CmsCategoryWidgetCategoryQuery greaterOrEqualsColumnId()
 * @method \Cms\Orm\CmsCategoryWidgetCategoryQuery lessOrEqualsColumnId()
 * @method \Cms\Orm\CmsCategoryWidgetCategoryQuery equalsColumnUuid()
 * @method \Cms\Orm\CmsCategoryWidgetCategoryQuery notEqualsColumnUuid()
 * @method \Cms\Orm\CmsCategoryWidgetCategoryQuery greaterThanColumnUuid()
 * @method \Cms\Orm\CmsCategoryWidgetCategoryQuery lessThanColumnUuid()
 * @method \Cms\Orm\CmsCategoryWidgetCategoryQuery greaterOrEqualsColumnUuid()
 * @method \Cms\Orm\CmsCategoryWidgetCategoryQuery lessOrEqualsColumnUuid()
 * @method \Cms\Orm\CmsCategoryWidgetCategoryQuery equalsColumnWidget()
 * @method \Cms\Orm\CmsCategoryWidgetCategoryQuery notEqualsColumnWidget()
 * @method \Cms\Orm\CmsCategoryWidgetCategoryQuery greaterThanColumnWidget()
 * @method \Cms\Orm\CmsCategoryWidgetCategoryQuery lessThanColumnWidget()
 * @method \Cms\Orm\CmsCategoryWidgetCategoryQuery greaterOrEqualsColumnWidget()
 * @method \Cms\Orm\CmsCategoryWidgetCategoryQuery lessOrEqualsColumnWidget()
 * @method \Cms\Orm\CmsCategoryWidgetCategoryQuery equalsColumnCmsCategoryId()
 * @method \Cms\Orm\CmsCategoryWidgetCategoryQuery notEqualsColumnCmsCategoryId()
 * @method \Cms\Orm\CmsCategoryWidgetCategoryQuery greaterThanColumnCmsCategoryId()
 * @method \Cms\Orm\CmsCategoryWidgetCategoryQuery lessThanColumnCmsCategoryId()
 * @method \Cms\Orm\CmsCategoryWidgetCategoryQuery greaterOrEqualsColumnCmsCategoryId()
 * @method \Cms\Orm\CmsCategoryWidgetCategoryQuery lessOrEqualsColumnCmsCategoryId()
 * @method \Cms\Orm\CmsCategoryWidgetCategoryQuery equalsColumnConfigJson()
 * @method \Cms\Orm\CmsCategoryWidgetCategoryQuery notEqualsColumnConfigJson()
 * @method \Cms\Orm\CmsCategoryWidgetCategoryQuery greaterThanColumnConfigJson()
 * @method \Cms\Orm\CmsCategoryWidgetCategoryQuery lessThanColumnConfigJson()
 * @method \Cms\Orm\CmsCategoryWidgetCategoryQuery greaterOrEqualsColumnConfigJson()
 * @method \Cms\Orm\CmsCategoryWidgetCategoryQuery lessOrEqualsColumnConfigJson()
 * @method \Cms\Orm\CmsCategoryWidgetCategoryQuery equalsColumnOrder()
 * @method \Cms\Orm\CmsCategoryWidgetCategoryQuery notEqualsColumnOrder()
 * @method \Cms\Orm\CmsCategoryWidgetCategoryQuery greaterThanColumnOrder()
 * @method \Cms\Orm\CmsCategoryWidgetCategoryQuery lessThanColumnOrder()
 * @method \Cms\Orm\CmsCategoryWidgetCategoryQuery greaterOrEqualsColumnOrder()
 * @method \Cms\Orm\CmsCategoryWidgetCategoryQuery lessOrEqualsColumnOrder()
 * @method \Cms\Orm\CmsCategoryWidgetCategoryQuery equalsColumnActive()
 * @method \Cms\Orm\CmsCategoryWidgetCategoryQuery notEqualsColumnActive()
 * @method \Cms\Orm\CmsCategoryWidgetCategoryQuery greaterThanColumnActive()
 * @method \Cms\Orm\CmsCategoryWidgetCategoryQuery lessThanColumnActive()
 * @method \Cms\Orm\CmsCategoryWidgetCategoryQuery greaterOrEqualsColumnActive()
 * @method \Cms\Orm\CmsCategoryWidgetCategoryQuery lessOrEqualsColumnActive()
 */
class CmsCategoryWidgetCategoryQueryField extends \Mmi\Orm\QueryHelper\QueryField
{

}
