<?php

namespace Cms\Orm\QueryHelper;

/**
 * @method \Cms\Orm\CmsCategorySectionQuery equals($value)
 * @method \Cms\Orm\CmsCategorySectionQuery notEquals($value)
 * @method \Cms\Orm\CmsCategorySectionQuery greater($value)
 * @method \Cms\Orm\CmsCategorySectionQuery less($value)
 * @method \Cms\Orm\CmsCategorySectionQuery greaterOrEquals($value)
 * @method \Cms\Orm\CmsCategorySectionQuery lessOrEquals($value)
 * @method \Cms\Orm\CmsCategorySectionQuery like($value)
 * @method \Cms\Orm\CmsCategorySectionQuery notLike($value)
 * @method \Cms\Orm\CmsCategorySectionQuery between($from, $to)
 * @method \Cms\Orm\CmsCategorySectionQuery equalsColumnId()
 * @method \Cms\Orm\CmsCategorySectionQuery notEqualsColumnId()
 * @method \Cms\Orm\CmsCategorySectionQuery greaterThanColumnId()
 * @method \Cms\Orm\CmsCategorySectionQuery lessThanColumnId()
 * @method \Cms\Orm\CmsCategorySectionQuery greaterOrEqualsColumnId()
 * @method \Cms\Orm\CmsCategorySectionQuery lessOrEqualsColumnId()
 * @method \Cms\Orm\CmsCategorySectionQuery equalsColumnCategoryTypeId()
 * @method \Cms\Orm\CmsCategorySectionQuery notEqualsColumnCategoryTypeId()
 * @method \Cms\Orm\CmsCategorySectionQuery greaterThanColumnCategoryTypeId()
 * @method \Cms\Orm\CmsCategorySectionQuery lessThanColumnCategoryTypeId()
 * @method \Cms\Orm\CmsCategorySectionQuery greaterOrEqualsColumnCategoryTypeId()
 * @method \Cms\Orm\CmsCategorySectionQuery lessOrEqualsColumnCategoryTypeId()
 * @method \Cms\Orm\CmsCategorySectionQuery equalsColumnKey()
 * @method \Cms\Orm\CmsCategorySectionQuery notEqualsColumnKey()
 * @method \Cms\Orm\CmsCategorySectionQuery greaterThanColumnKey()
 * @method \Cms\Orm\CmsCategorySectionQuery lessThanColumnKey()
 * @method \Cms\Orm\CmsCategorySectionQuery greaterOrEqualsColumnKey()
 * @method \Cms\Orm\CmsCategorySectionQuery lessOrEqualsColumnKey()
 * @method \Cms\Orm\CmsCategorySectionQuery equalsColumnName()
 * @method \Cms\Orm\CmsCategorySectionQuery notEqualsColumnName()
 * @method \Cms\Orm\CmsCategorySectionQuery greaterThanColumnName()
 * @method \Cms\Orm\CmsCategorySectionQuery lessThanColumnName()
 * @method \Cms\Orm\CmsCategorySectionQuery greaterOrEqualsColumnName()
 * @method \Cms\Orm\CmsCategorySectionQuery lessOrEqualsColumnName()
 * @method \Cms\Orm\CmsCategorySectionQuery equalsColumnOrder()
 * @method \Cms\Orm\CmsCategorySectionQuery notEqualsColumnOrder()
 * @method \Cms\Orm\CmsCategorySectionQuery greaterThanColumnOrder()
 * @method \Cms\Orm\CmsCategorySectionQuery lessThanColumnOrder()
 * @method \Cms\Orm\CmsCategorySectionQuery greaterOrEqualsColumnOrder()
 * @method \Cms\Orm\CmsCategorySectionQuery lessOrEqualsColumnOrder()
 * @method \Cms\Orm\CmsCategorySectionQuery equalsColumnRequired()
 * @method \Cms\Orm\CmsCategorySectionQuery notEqualsColumnRequired()
 * @method \Cms\Orm\CmsCategorySectionQuery greaterThanColumnRequired()
 * @method \Cms\Orm\CmsCategorySectionQuery lessThanColumnRequired()
 * @method \Cms\Orm\CmsCategorySectionQuery greaterOrEqualsColumnRequired()
 * @method \Cms\Orm\CmsCategorySectionQuery lessOrEqualsColumnRequired()
 */
class CmsCategorySectionQueryField extends \Mmi\Orm\QueryHelper\QueryField
{

}
