<?php

namespace Cms\Orm\QueryHelper;

/**
 * @method \Cms\Orm\CmsCategoryWidgetQuery equals($value)
 * @method \Cms\Orm\CmsCategoryWidgetQuery notEquals($value)
 * @method \Cms\Orm\CmsCategoryWidgetQuery greater($value)
 * @method \Cms\Orm\CmsCategoryWidgetQuery less($value)
 * @method \Cms\Orm\CmsCategoryWidgetQuery greaterOrEquals($value)
 * @method \Cms\Orm\CmsCategoryWidgetQuery lessOrEquals($value)
 * @method \Cms\Orm\CmsCategoryWidgetQuery like($value)
 * @method \Cms\Orm\CmsCategoryWidgetQuery ilike($value)
 * @method \Cms\Orm\CmsCategoryWidgetQuery between($from, $to)
 * @method \Cms\Orm\CmsCategoryWidgetQuery equalsColumnId()
 * @method \Cms\Orm\CmsCategoryWidgetQuery notEqualsColumnId()
 * @method \Cms\Orm\CmsCategoryWidgetQuery greaterThanColumnId()
 * @method \Cms\Orm\CmsCategoryWidgetQuery lessThanColumnId()
 * @method \Cms\Orm\CmsCategoryWidgetQuery greaterOrEqualsColumnId()
 * @method \Cms\Orm\CmsCategoryWidgetQuery lessOrEqualsColumnId()
 * @method \Cms\Orm\CmsCategoryWidgetQuery equalsColumnName()
 * @method \Cms\Orm\CmsCategoryWidgetQuery notEqualsColumnName()
 * @method \Cms\Orm\CmsCategoryWidgetQuery greaterThanColumnName()
 * @method \Cms\Orm\CmsCategoryWidgetQuery lessThanColumnName()
 * @method \Cms\Orm\CmsCategoryWidgetQuery greaterOrEqualsColumnName()
 * @method \Cms\Orm\CmsCategoryWidgetQuery lessOrEqualsColumnName()
 * @method \Cms\Orm\CmsCategoryWidgetQuery equalsColumnRecordClass()
 * @method \Cms\Orm\CmsCategoryWidgetQuery notEqualsColumnRecordClass()
 * @method \Cms\Orm\CmsCategoryWidgetQuery greaterThanColumnRecordClass()
 * @method \Cms\Orm\CmsCategoryWidgetQuery lessThanColumnRecordClass()
 * @method \Cms\Orm\CmsCategoryWidgetQuery greaterOrEqualsColumnRecordClass()
 * @method \Cms\Orm\CmsCategoryWidgetQuery lessOrEqualsColumnRecordClass()
 * @method \Cms\Orm\CmsCategoryWidgetQuery equalsColumnFormClass()
 * @method \Cms\Orm\CmsCategoryWidgetQuery notEqualsColumnFormClass()
 * @method \Cms\Orm\CmsCategoryWidgetQuery greaterThanColumnFormClass()
 * @method \Cms\Orm\CmsCategoryWidgetQuery lessThanColumnFormClass()
 * @method \Cms\Orm\CmsCategoryWidgetQuery greaterOrEqualsColumnFormClass()
 * @method \Cms\Orm\CmsCategoryWidgetQuery lessOrEqualsColumnFormClass()
 * @method \Cms\Orm\CmsCategoryWidgetQuery equalsColumnMvcParams()
 * @method \Cms\Orm\CmsCategoryWidgetQuery notEqualsColumnMvcParams()
 * @method \Cms\Orm\CmsCategoryWidgetQuery greaterThanColumnMvcParams()
 * @method \Cms\Orm\CmsCategoryWidgetQuery lessThanColumnMvcParams()
 * @method \Cms\Orm\CmsCategoryWidgetQuery greaterOrEqualsColumnMvcParams()
 * @method \Cms\Orm\CmsCategoryWidgetQuery lessOrEqualsColumnMvcParams()
 * @method \Cms\Orm\CmsCategoryWidgetQuery equalsColumnMvcPreviewParams()
 * @method \Cms\Orm\CmsCategoryWidgetQuery notEqualsColumnMvcPreviewParams()
 * @method \Cms\Orm\CmsCategoryWidgetQuery greaterThanColumnMvcPreviewParams()
 * @method \Cms\Orm\CmsCategoryWidgetQuery lessThanColumnMvcPreviewParams()
 * @method \Cms\Orm\CmsCategoryWidgetQuery greaterOrEqualsColumnMvcPreviewParams()
 * @method \Cms\Orm\CmsCategoryWidgetQuery lessOrEqualsColumnMvcPreviewParams()
 */
class CmsCategoryWidgetQueryField extends \Mmi\Orm\QueryHelper\QueryField {

}
