<?php

namespace Cms\Orm\QueryHelper;

/**
 * @method \Cms\Orm\CmsFileQuery equals($value)
 * @method \Cms\Orm\CmsFileQuery notEquals($value)
 * @method \Cms\Orm\CmsFileQuery greater($value)
 * @method \Cms\Orm\CmsFileQuery less($value)
 * @method \Cms\Orm\CmsFileQuery greaterOrEquals($value)
 * @method \Cms\Orm\CmsFileQuery lessOrEquals($value)
 * @method \Cms\Orm\CmsFileQuery like($value)
 * @method \Cms\Orm\CmsFileQuery ilike($value)
 * @method \Cms\Orm\CmsFileQuery between($from, $to)
 * @method \Cms\Orm\CmsFileQuery equalsColumnId()
 * @method \Cms\Orm\CmsFileQuery notEqualsColumnId()
 * @method \Cms\Orm\CmsFileQuery greaterThanColumnId()
 * @method \Cms\Orm\CmsFileQuery lessThanColumnId()
 * @method \Cms\Orm\CmsFileQuery greaterOrEqualsColumnId()
 * @method \Cms\Orm\CmsFileQuery lessOrEqualsColumnId()
 * @method \Cms\Orm\CmsFileQuery equalsColumnClass()
 * @method \Cms\Orm\CmsFileQuery notEqualsColumnClass()
 * @method \Cms\Orm\CmsFileQuery greaterThanColumnClass()
 * @method \Cms\Orm\CmsFileQuery lessThanColumnClass()
 * @method \Cms\Orm\CmsFileQuery greaterOrEqualsColumnClass()
 * @method \Cms\Orm\CmsFileQuery lessOrEqualsColumnClass()
 * @method \Cms\Orm\CmsFileQuery equalsColumnMimeType()
 * @method \Cms\Orm\CmsFileQuery notEqualsColumnMimeType()
 * @method \Cms\Orm\CmsFileQuery greaterThanColumnMimeType()
 * @method \Cms\Orm\CmsFileQuery lessThanColumnMimeType()
 * @method \Cms\Orm\CmsFileQuery greaterOrEqualsColumnMimeType()
 * @method \Cms\Orm\CmsFileQuery lessOrEqualsColumnMimeType()
 * @method \Cms\Orm\CmsFileQuery equalsColumnName()
 * @method \Cms\Orm\CmsFileQuery notEqualsColumnName()
 * @method \Cms\Orm\CmsFileQuery greaterThanColumnName()
 * @method \Cms\Orm\CmsFileQuery lessThanColumnName()
 * @method \Cms\Orm\CmsFileQuery greaterOrEqualsColumnName()
 * @method \Cms\Orm\CmsFileQuery lessOrEqualsColumnName()
 * @method \Cms\Orm\CmsFileQuery equalsColumnOriginal()
 * @method \Cms\Orm\CmsFileQuery notEqualsColumnOriginal()
 * @method \Cms\Orm\CmsFileQuery greaterThanColumnOriginal()
 * @method \Cms\Orm\CmsFileQuery lessThanColumnOriginal()
 * @method \Cms\Orm\CmsFileQuery greaterOrEqualsColumnOriginal()
 * @method \Cms\Orm\CmsFileQuery lessOrEqualsColumnOriginal()
 * @method \Cms\Orm\CmsFileQuery equalsColumnData()
 * @method \Cms\Orm\CmsFileQuery notEqualsColumnData()
 * @method \Cms\Orm\CmsFileQuery greaterThanColumnData()
 * @method \Cms\Orm\CmsFileQuery lessThanColumnData()
 * @method \Cms\Orm\CmsFileQuery greaterOrEqualsColumnData()
 * @method \Cms\Orm\CmsFileQuery lessOrEqualsColumnData()
 * @method \Cms\Orm\CmsFileQuery equalsColumnSize()
 * @method \Cms\Orm\CmsFileQuery notEqualsColumnSize()
 * @method \Cms\Orm\CmsFileQuery greaterThanColumnSize()
 * @method \Cms\Orm\CmsFileQuery lessThanColumnSize()
 * @method \Cms\Orm\CmsFileQuery greaterOrEqualsColumnSize()
 * @method \Cms\Orm\CmsFileQuery lessOrEqualsColumnSize()
 * @method \Cms\Orm\CmsFileQuery equalsColumnDateAdd()
 * @method \Cms\Orm\CmsFileQuery notEqualsColumnDateAdd()
 * @method \Cms\Orm\CmsFileQuery greaterThanColumnDateAdd()
 * @method \Cms\Orm\CmsFileQuery lessThanColumnDateAdd()
 * @method \Cms\Orm\CmsFileQuery greaterOrEqualsColumnDateAdd()
 * @method \Cms\Orm\CmsFileQuery lessOrEqualsColumnDateAdd()
 * @method \Cms\Orm\CmsFileQuery equalsColumnDateModify()
 * @method \Cms\Orm\CmsFileQuery notEqualsColumnDateModify()
 * @method \Cms\Orm\CmsFileQuery greaterThanColumnDateModify()
 * @method \Cms\Orm\CmsFileQuery lessThanColumnDateModify()
 * @method \Cms\Orm\CmsFileQuery greaterOrEqualsColumnDateModify()
 * @method \Cms\Orm\CmsFileQuery lessOrEqualsColumnDateModify()
 * @method \Cms\Orm\CmsFileQuery equalsColumnOrder()
 * @method \Cms\Orm\CmsFileQuery notEqualsColumnOrder()
 * @method \Cms\Orm\CmsFileQuery greaterThanColumnOrder()
 * @method \Cms\Orm\CmsFileQuery lessThanColumnOrder()
 * @method \Cms\Orm\CmsFileQuery greaterOrEqualsColumnOrder()
 * @method \Cms\Orm\CmsFileQuery lessOrEqualsColumnOrder()
 * @method \Cms\Orm\CmsFileQuery equalsColumnSticky()
 * @method \Cms\Orm\CmsFileQuery notEqualsColumnSticky()
 * @method \Cms\Orm\CmsFileQuery greaterThanColumnSticky()
 * @method \Cms\Orm\CmsFileQuery lessThanColumnSticky()
 * @method \Cms\Orm\CmsFileQuery greaterOrEqualsColumnSticky()
 * @method \Cms\Orm\CmsFileQuery lessOrEqualsColumnSticky()
 * @method \Cms\Orm\CmsFileQuery equalsColumnObject()
 * @method \Cms\Orm\CmsFileQuery notEqualsColumnObject()
 * @method \Cms\Orm\CmsFileQuery greaterThanColumnObject()
 * @method \Cms\Orm\CmsFileQuery lessThanColumnObject()
 * @method \Cms\Orm\CmsFileQuery greaterOrEqualsColumnObject()
 * @method \Cms\Orm\CmsFileQuery lessOrEqualsColumnObject()
 * @method \Cms\Orm\CmsFileQuery equalsColumnObjectId()
 * @method \Cms\Orm\CmsFileQuery notEqualsColumnObjectId()
 * @method \Cms\Orm\CmsFileQuery greaterThanColumnObjectId()
 * @method \Cms\Orm\CmsFileQuery lessThanColumnObjectId()
 * @method \Cms\Orm\CmsFileQuery greaterOrEqualsColumnObjectId()
 * @method \Cms\Orm\CmsFileQuery lessOrEqualsColumnObjectId()
 * @method \Cms\Orm\CmsFileQuery equalsColumnCmsAuthId()
 * @method \Cms\Orm\CmsFileQuery notEqualsColumnCmsAuthId()
 * @method \Cms\Orm\CmsFileQuery greaterThanColumnCmsAuthId()
 * @method \Cms\Orm\CmsFileQuery lessThanColumnCmsAuthId()
 * @method \Cms\Orm\CmsFileQuery greaterOrEqualsColumnCmsAuthId()
 * @method \Cms\Orm\CmsFileQuery lessOrEqualsColumnCmsAuthId()
 * @method \Cms\Orm\CmsFileQuery equalsColumnActive()
 * @method \Cms\Orm\CmsFileQuery notEqualsColumnActive()
 * @method \Cms\Orm\CmsFileQuery greaterThanColumnActive()
 * @method \Cms\Orm\CmsFileQuery lessThanColumnActive()
 * @method \Cms\Orm\CmsFileQuery greaterOrEqualsColumnActive()
 * @method \Cms\Orm\CmsFileQuery lessOrEqualsColumnActive()
 */
class CmsFileQueryField extends \Mmi\Orm\QueryHelper\QueryField {

}
