<?php

namespace Cms\Orm\QueryHelper;

/**
 * @method \Cms\Orm\CmsLogQuery equals($value)
 * @method \Cms\Orm\CmsLogQuery notEquals($value)
 * @method \Cms\Orm\CmsLogQuery greater($value)
 * @method \Cms\Orm\CmsLogQuery less($value)
 * @method \Cms\Orm\CmsLogQuery greaterOrEquals($value)
 * @method \Cms\Orm\CmsLogQuery lessOrEquals($value)
 * @method \Cms\Orm\CmsLogQuery like($value)
 * @method \Cms\Orm\CmsLogQuery ilike($value)
 * @method \Cms\Orm\CmsLogQuery between($from, $to)
 * @method \Cms\Orm\CmsLogQuery equalsColumnId()
 * @method \Cms\Orm\CmsLogQuery notEqualsColumnId()
 * @method \Cms\Orm\CmsLogQuery greaterThanColumnId()
 * @method \Cms\Orm\CmsLogQuery lessThanColumnId()
 * @method \Cms\Orm\CmsLogQuery greaterOrEqualsColumnId()
 * @method \Cms\Orm\CmsLogQuery lessOrEqualsColumnId()
 * @method \Cms\Orm\CmsLogQuery equalsColumnUrl()
 * @method \Cms\Orm\CmsLogQuery notEqualsColumnUrl()
 * @method \Cms\Orm\CmsLogQuery greaterThanColumnUrl()
 * @method \Cms\Orm\CmsLogQuery lessThanColumnUrl()
 * @method \Cms\Orm\CmsLogQuery greaterOrEqualsColumnUrl()
 * @method \Cms\Orm\CmsLogQuery lessOrEqualsColumnUrl()
 * @method \Cms\Orm\CmsLogQuery equalsColumnIp()
 * @method \Cms\Orm\CmsLogQuery notEqualsColumnIp()
 * @method \Cms\Orm\CmsLogQuery greaterThanColumnIp()
 * @method \Cms\Orm\CmsLogQuery lessThanColumnIp()
 * @method \Cms\Orm\CmsLogQuery greaterOrEqualsColumnIp()
 * @method \Cms\Orm\CmsLogQuery lessOrEqualsColumnIp()
 * @method \Cms\Orm\CmsLogQuery equalsColumnBrowser()
 * @method \Cms\Orm\CmsLogQuery notEqualsColumnBrowser()
 * @method \Cms\Orm\CmsLogQuery greaterThanColumnBrowser()
 * @method \Cms\Orm\CmsLogQuery lessThanColumnBrowser()
 * @method \Cms\Orm\CmsLogQuery greaterOrEqualsColumnBrowser()
 * @method \Cms\Orm\CmsLogQuery lessOrEqualsColumnBrowser()
 * @method \Cms\Orm\CmsLogQuery equalsColumnOperation()
 * @method \Cms\Orm\CmsLogQuery notEqualsColumnOperation()
 * @method \Cms\Orm\CmsLogQuery greaterThanColumnOperation()
 * @method \Cms\Orm\CmsLogQuery lessThanColumnOperation()
 * @method \Cms\Orm\CmsLogQuery greaterOrEqualsColumnOperation()
 * @method \Cms\Orm\CmsLogQuery lessOrEqualsColumnOperation()
 * @method \Cms\Orm\CmsLogQuery equalsColumnObject()
 * @method \Cms\Orm\CmsLogQuery notEqualsColumnObject()
 * @method \Cms\Orm\CmsLogQuery greaterThanColumnObject()
 * @method \Cms\Orm\CmsLogQuery lessThanColumnObject()
 * @method \Cms\Orm\CmsLogQuery greaterOrEqualsColumnObject()
 * @method \Cms\Orm\CmsLogQuery lessOrEqualsColumnObject()
 * @method \Cms\Orm\CmsLogQuery equalsColumnObjectId()
 * @method \Cms\Orm\CmsLogQuery notEqualsColumnObjectId()
 * @method \Cms\Orm\CmsLogQuery greaterThanColumnObjectId()
 * @method \Cms\Orm\CmsLogQuery lessThanColumnObjectId()
 * @method \Cms\Orm\CmsLogQuery greaterOrEqualsColumnObjectId()
 * @method \Cms\Orm\CmsLogQuery lessOrEqualsColumnObjectId()
 * @method \Cms\Orm\CmsLogQuery equalsColumnData()
 * @method \Cms\Orm\CmsLogQuery notEqualsColumnData()
 * @method \Cms\Orm\CmsLogQuery greaterThanColumnData()
 * @method \Cms\Orm\CmsLogQuery lessThanColumnData()
 * @method \Cms\Orm\CmsLogQuery greaterOrEqualsColumnData()
 * @method \Cms\Orm\CmsLogQuery lessOrEqualsColumnData()
 * @method \Cms\Orm\CmsLogQuery equalsColumnSuccess()
 * @method \Cms\Orm\CmsLogQuery notEqualsColumnSuccess()
 * @method \Cms\Orm\CmsLogQuery greaterThanColumnSuccess()
 * @method \Cms\Orm\CmsLogQuery lessThanColumnSuccess()
 * @method \Cms\Orm\CmsLogQuery greaterOrEqualsColumnSuccess()
 * @method \Cms\Orm\CmsLogQuery lessOrEqualsColumnSuccess()
 * @method \Cms\Orm\CmsLogQuery equalsColumnCmsAuthId()
 * @method \Cms\Orm\CmsLogQuery notEqualsColumnCmsAuthId()
 * @method \Cms\Orm\CmsLogQuery greaterThanColumnCmsAuthId()
 * @method \Cms\Orm\CmsLogQuery lessThanColumnCmsAuthId()
 * @method \Cms\Orm\CmsLogQuery greaterOrEqualsColumnCmsAuthId()
 * @method \Cms\Orm\CmsLogQuery lessOrEqualsColumnCmsAuthId()
 * @method \Cms\Orm\CmsLogQuery equalsColumnDateTime()
 * @method \Cms\Orm\CmsLogQuery notEqualsColumnDateTime()
 * @method \Cms\Orm\CmsLogQuery greaterThanColumnDateTime()
 * @method \Cms\Orm\CmsLogQuery lessThanColumnDateTime()
 * @method \Cms\Orm\CmsLogQuery greaterOrEqualsColumnDateTime()
 * @method \Cms\Orm\CmsLogQuery lessOrEqualsColumnDateTime()
 */
class CmsLogQueryField extends \Mmi\Orm\QueryHelper\QueryField {

}
