<?php

namespace Cms\Orm\QueryHelper;

/**
 * @method \Cms\Orm\CmsMailServerQuery equals($value)
 * @method \Cms\Orm\CmsMailServerQuery notEquals($value)
 * @method \Cms\Orm\CmsMailServerQuery greater($value)
 * @method \Cms\Orm\CmsMailServerQuery less($value)
 * @method \Cms\Orm\CmsMailServerQuery greaterOrEquals($value)
 * @method \Cms\Orm\CmsMailServerQuery lessOrEquals($value)
 * @method \Cms\Orm\CmsMailServerQuery like($value)
 * @method \Cms\Orm\CmsMailServerQuery ilike($value)
 * @method \Cms\Orm\CmsMailServerQuery between($from, $to)
 * @method \Cms\Orm\CmsMailServerQuery equalsColumnId()
 * @method \Cms\Orm\CmsMailServerQuery notEqualsColumnId()
 * @method \Cms\Orm\CmsMailServerQuery greaterThanColumnId()
 * @method \Cms\Orm\CmsMailServerQuery lessThanColumnId()
 * @method \Cms\Orm\CmsMailServerQuery greaterOrEqualsColumnId()
 * @method \Cms\Orm\CmsMailServerQuery lessOrEqualsColumnId()
 * @method \Cms\Orm\CmsMailServerQuery equalsColumnAddress()
 * @method \Cms\Orm\CmsMailServerQuery notEqualsColumnAddress()
 * @method \Cms\Orm\CmsMailServerQuery greaterThanColumnAddress()
 * @method \Cms\Orm\CmsMailServerQuery lessThanColumnAddress()
 * @method \Cms\Orm\CmsMailServerQuery greaterOrEqualsColumnAddress()
 * @method \Cms\Orm\CmsMailServerQuery lessOrEqualsColumnAddress()
 * @method \Cms\Orm\CmsMailServerQuery equalsColumnPort()
 * @method \Cms\Orm\CmsMailServerQuery notEqualsColumnPort()
 * @method \Cms\Orm\CmsMailServerQuery greaterThanColumnPort()
 * @method \Cms\Orm\CmsMailServerQuery lessThanColumnPort()
 * @method \Cms\Orm\CmsMailServerQuery greaterOrEqualsColumnPort()
 * @method \Cms\Orm\CmsMailServerQuery lessOrEqualsColumnPort()
 * @method \Cms\Orm\CmsMailServerQuery equalsColumnUsername()
 * @method \Cms\Orm\CmsMailServerQuery notEqualsColumnUsername()
 * @method \Cms\Orm\CmsMailServerQuery greaterThanColumnUsername()
 * @method \Cms\Orm\CmsMailServerQuery lessThanColumnUsername()
 * @method \Cms\Orm\CmsMailServerQuery greaterOrEqualsColumnUsername()
 * @method \Cms\Orm\CmsMailServerQuery lessOrEqualsColumnUsername()
 * @method \Cms\Orm\CmsMailServerQuery equalsColumnPassword()
 * @method \Cms\Orm\CmsMailServerQuery notEqualsColumnPassword()
 * @method \Cms\Orm\CmsMailServerQuery greaterThanColumnPassword()
 * @method \Cms\Orm\CmsMailServerQuery lessThanColumnPassword()
 * @method \Cms\Orm\CmsMailServerQuery greaterOrEqualsColumnPassword()
 * @method \Cms\Orm\CmsMailServerQuery lessOrEqualsColumnPassword()
 * @method \Cms\Orm\CmsMailServerQuery equalsColumnFrom()
 * @method \Cms\Orm\CmsMailServerQuery notEqualsColumnFrom()
 * @method \Cms\Orm\CmsMailServerQuery greaterThanColumnFrom()
 * @method \Cms\Orm\CmsMailServerQuery lessThanColumnFrom()
 * @method \Cms\Orm\CmsMailServerQuery greaterOrEqualsColumnFrom()
 * @method \Cms\Orm\CmsMailServerQuery lessOrEqualsColumnFrom()
 * @method \Cms\Orm\CmsMailServerQuery equalsColumnDateAdd()
 * @method \Cms\Orm\CmsMailServerQuery notEqualsColumnDateAdd()
 * @method \Cms\Orm\CmsMailServerQuery greaterThanColumnDateAdd()
 * @method \Cms\Orm\CmsMailServerQuery lessThanColumnDateAdd()
 * @method \Cms\Orm\CmsMailServerQuery greaterOrEqualsColumnDateAdd()
 * @method \Cms\Orm\CmsMailServerQuery lessOrEqualsColumnDateAdd()
 * @method \Cms\Orm\CmsMailServerQuery equalsColumnDateModify()
 * @method \Cms\Orm\CmsMailServerQuery notEqualsColumnDateModify()
 * @method \Cms\Orm\CmsMailServerQuery greaterThanColumnDateModify()
 * @method \Cms\Orm\CmsMailServerQuery lessThanColumnDateModify()
 * @method \Cms\Orm\CmsMailServerQuery greaterOrEqualsColumnDateModify()
 * @method \Cms\Orm\CmsMailServerQuery lessOrEqualsColumnDateModify()
 * @method \Cms\Orm\CmsMailServerQuery equalsColumnActive()
 * @method \Cms\Orm\CmsMailServerQuery notEqualsColumnActive()
 * @method \Cms\Orm\CmsMailServerQuery greaterThanColumnActive()
 * @method \Cms\Orm\CmsMailServerQuery lessThanColumnActive()
 * @method \Cms\Orm\CmsMailServerQuery greaterOrEqualsColumnActive()
 * @method \Cms\Orm\CmsMailServerQuery lessOrEqualsColumnActive()
 * @method \Cms\Orm\CmsMailServerQuery equalsColumnSsl()
 * @method \Cms\Orm\CmsMailServerQuery notEqualsColumnSsl()
 * @method \Cms\Orm\CmsMailServerQuery greaterThanColumnSsl()
 * @method \Cms\Orm\CmsMailServerQuery lessThanColumnSsl()
 * @method \Cms\Orm\CmsMailServerQuery greaterOrEqualsColumnSsl()
 * @method \Cms\Orm\CmsMailServerQuery lessOrEqualsColumnSsl()
 */
class CmsMailServerQueryField extends \Mmi\Orm\QueryHelper\QueryField {

}
