<?php

namespace Cms\Orm\QueryHelper;

/**
 * @method \Cms\Orm\CmsMailQuery equals($value)
 * @method \Cms\Orm\CmsMailQuery notEquals($value)
 * @method \Cms\Orm\CmsMailQuery greater($value)
 * @method \Cms\Orm\CmsMailQuery less($value)
 * @method \Cms\Orm\CmsMailQuery greaterOrEquals($value)
 * @method \Cms\Orm\CmsMailQuery lessOrEquals($value)
 * @method \Cms\Orm\CmsMailQuery like($value)
 * @method \Cms\Orm\CmsMailQuery notLike($value)
 * @method \Cms\Orm\CmsMailQuery between($from, $to)
 * @method \Cms\Orm\CmsMailQuery equalsColumnId()
 * @method \Cms\Orm\CmsMailQuery notEqualsColumnId()
 * @method \Cms\Orm\CmsMailQuery greaterThanColumnId()
 * @method \Cms\Orm\CmsMailQuery lessThanColumnId()
 * @method \Cms\Orm\CmsMailQuery greaterOrEqualsColumnId()
 * @method \Cms\Orm\CmsMailQuery lessOrEqualsColumnId()
 * @method \Cms\Orm\CmsMailQuery equalsColumnCmsMailDefinitionId()
 * @method \Cms\Orm\CmsMailQuery notEqualsColumnCmsMailDefinitionId()
 * @method \Cms\Orm\CmsMailQuery greaterThanColumnCmsMailDefinitionId()
 * @method \Cms\Orm\CmsMailQuery lessThanColumnCmsMailDefinitionId()
 * @method \Cms\Orm\CmsMailQuery greaterOrEqualsColumnCmsMailDefinitionId()
 * @method \Cms\Orm\CmsMailQuery lessOrEqualsColumnCmsMailDefinitionId()
 * @method \Cms\Orm\CmsMailQuery equalsColumnFromName()
 * @method \Cms\Orm\CmsMailQuery notEqualsColumnFromName()
 * @method \Cms\Orm\CmsMailQuery greaterThanColumnFromName()
 * @method \Cms\Orm\CmsMailQuery lessThanColumnFromName()
 * @method \Cms\Orm\CmsMailQuery greaterOrEqualsColumnFromName()
 * @method \Cms\Orm\CmsMailQuery lessOrEqualsColumnFromName()
 * @method \Cms\Orm\CmsMailQuery equalsColumnTo()
 * @method \Cms\Orm\CmsMailQuery notEqualsColumnTo()
 * @method \Cms\Orm\CmsMailQuery greaterThanColumnTo()
 * @method \Cms\Orm\CmsMailQuery lessThanColumnTo()
 * @method \Cms\Orm\CmsMailQuery greaterOrEqualsColumnTo()
 * @method \Cms\Orm\CmsMailQuery lessOrEqualsColumnTo()
 * @method \Cms\Orm\CmsMailQuery equalsColumnReplyTo()
 * @method \Cms\Orm\CmsMailQuery notEqualsColumnReplyTo()
 * @method \Cms\Orm\CmsMailQuery greaterThanColumnReplyTo()
 * @method \Cms\Orm\CmsMailQuery lessThanColumnReplyTo()
 * @method \Cms\Orm\CmsMailQuery greaterOrEqualsColumnReplyTo()
 * @method \Cms\Orm\CmsMailQuery lessOrEqualsColumnReplyTo()
 * @method \Cms\Orm\CmsMailQuery equalsColumnSubject()
 * @method \Cms\Orm\CmsMailQuery notEqualsColumnSubject()
 * @method \Cms\Orm\CmsMailQuery greaterThanColumnSubject()
 * @method \Cms\Orm\CmsMailQuery lessThanColumnSubject()
 * @method \Cms\Orm\CmsMailQuery greaterOrEqualsColumnSubject()
 * @method \Cms\Orm\CmsMailQuery lessOrEqualsColumnSubject()
 * @method \Cms\Orm\CmsMailQuery equalsColumnMessage()
 * @method \Cms\Orm\CmsMailQuery notEqualsColumnMessage()
 * @method \Cms\Orm\CmsMailQuery greaterThanColumnMessage()
 * @method \Cms\Orm\CmsMailQuery lessThanColumnMessage()
 * @method \Cms\Orm\CmsMailQuery greaterOrEqualsColumnMessage()
 * @method \Cms\Orm\CmsMailQuery lessOrEqualsColumnMessage()
 * @method \Cms\Orm\CmsMailQuery equalsColumnAttachements()
 * @method \Cms\Orm\CmsMailQuery notEqualsColumnAttachements()
 * @method \Cms\Orm\CmsMailQuery greaterThanColumnAttachements()
 * @method \Cms\Orm\CmsMailQuery lessThanColumnAttachements()
 * @method \Cms\Orm\CmsMailQuery greaterOrEqualsColumnAttachements()
 * @method \Cms\Orm\CmsMailQuery lessOrEqualsColumnAttachements()
 * @method \Cms\Orm\CmsMailQuery equalsColumnType()
 * @method \Cms\Orm\CmsMailQuery notEqualsColumnType()
 * @method \Cms\Orm\CmsMailQuery greaterThanColumnType()
 * @method \Cms\Orm\CmsMailQuery lessThanColumnType()
 * @method \Cms\Orm\CmsMailQuery greaterOrEqualsColumnType()
 * @method \Cms\Orm\CmsMailQuery lessOrEqualsColumnType()
 * @method \Cms\Orm\CmsMailQuery equalsColumnDateAdd()
 * @method \Cms\Orm\CmsMailQuery notEqualsColumnDateAdd()
 * @method \Cms\Orm\CmsMailQuery greaterThanColumnDateAdd()
 * @method \Cms\Orm\CmsMailQuery lessThanColumnDateAdd()
 * @method \Cms\Orm\CmsMailQuery greaterOrEqualsColumnDateAdd()
 * @method \Cms\Orm\CmsMailQuery lessOrEqualsColumnDateAdd()
 * @method \Cms\Orm\CmsMailQuery equalsColumnDateSent()
 * @method \Cms\Orm\CmsMailQuery notEqualsColumnDateSent()
 * @method \Cms\Orm\CmsMailQuery greaterThanColumnDateSent()
 * @method \Cms\Orm\CmsMailQuery lessThanColumnDateSent()
 * @method \Cms\Orm\CmsMailQuery greaterOrEqualsColumnDateSent()
 * @method \Cms\Orm\CmsMailQuery lessOrEqualsColumnDateSent()
 * @method \Cms\Orm\CmsMailQuery equalsColumnDateSendAfter()
 * @method \Cms\Orm\CmsMailQuery notEqualsColumnDateSendAfter()
 * @method \Cms\Orm\CmsMailQuery greaterThanColumnDateSendAfter()
 * @method \Cms\Orm\CmsMailQuery lessThanColumnDateSendAfter()
 * @method \Cms\Orm\CmsMailQuery greaterOrEqualsColumnDateSendAfter()
 * @method \Cms\Orm\CmsMailQuery lessOrEqualsColumnDateSendAfter()
 * @method \Cms\Orm\CmsMailQuery equalsColumnActive()
 * @method \Cms\Orm\CmsMailQuery notEqualsColumnActive()
 * @method \Cms\Orm\CmsMailQuery greaterThanColumnActive()
 * @method \Cms\Orm\CmsMailQuery lessThanColumnActive()
 * @method \Cms\Orm\CmsMailQuery greaterOrEqualsColumnActive()
 * @method \Cms\Orm\CmsMailQuery lessOrEqualsColumnActive()
 */
class CmsMailQueryField extends \Mmi\Orm\QueryHelper\QueryField
{

}
