<?php

namespace Cms\Orm\QueryHelper;

/**
 * @method \Cms\Orm\CmsMailDefinitionQuery equals($value)
 * @method \Cms\Orm\CmsMailDefinitionQuery notEquals($value)
 * @method \Cms\Orm\CmsMailDefinitionQuery greater($value)
 * @method \Cms\Orm\CmsMailDefinitionQuery less($value)
 * @method \Cms\Orm\CmsMailDefinitionQuery greaterOrEquals($value)
 * @method \Cms\Orm\CmsMailDefinitionQuery lessOrEquals($value)
 * @method \Cms\Orm\CmsMailDefinitionQuery like($value)
 * @method \Cms\Orm\CmsMailDefinitionQuery notLike($value)
 * @method \Cms\Orm\CmsMailDefinitionQuery between($from, $to)
 * @method \Cms\Orm\CmsMailDefinitionQuery equalsColumnId()
 * @method \Cms\Orm\CmsMailDefinitionQuery notEqualsColumnId()
 * @method \Cms\Orm\CmsMailDefinitionQuery greaterThanColumnId()
 * @method \Cms\Orm\CmsMailDefinitionQuery lessThanColumnId()
 * @method \Cms\Orm\CmsMailDefinitionQuery greaterOrEqualsColumnId()
 * @method \Cms\Orm\CmsMailDefinitionQuery lessOrEqualsColumnId()
 * @method \Cms\Orm\CmsMailDefinitionQuery equalsColumnLang()
 * @method \Cms\Orm\CmsMailDefinitionQuery notEqualsColumnLang()
 * @method \Cms\Orm\CmsMailDefinitionQuery greaterThanColumnLang()
 * @method \Cms\Orm\CmsMailDefinitionQuery lessThanColumnLang()
 * @method \Cms\Orm\CmsMailDefinitionQuery greaterOrEqualsColumnLang()
 * @method \Cms\Orm\CmsMailDefinitionQuery lessOrEqualsColumnLang()
 * @method \Cms\Orm\CmsMailDefinitionQuery equalsColumnCmsMailServerId()
 * @method \Cms\Orm\CmsMailDefinitionQuery notEqualsColumnCmsMailServerId()
 * @method \Cms\Orm\CmsMailDefinitionQuery greaterThanColumnCmsMailServerId()
 * @method \Cms\Orm\CmsMailDefinitionQuery lessThanColumnCmsMailServerId()
 * @method \Cms\Orm\CmsMailDefinitionQuery greaterOrEqualsColumnCmsMailServerId()
 * @method \Cms\Orm\CmsMailDefinitionQuery lessOrEqualsColumnCmsMailServerId()
 * @method \Cms\Orm\CmsMailDefinitionQuery equalsColumnName()
 * @method \Cms\Orm\CmsMailDefinitionQuery notEqualsColumnName()
 * @method \Cms\Orm\CmsMailDefinitionQuery greaterThanColumnName()
 * @method \Cms\Orm\CmsMailDefinitionQuery lessThanColumnName()
 * @method \Cms\Orm\CmsMailDefinitionQuery greaterOrEqualsColumnName()
 * @method \Cms\Orm\CmsMailDefinitionQuery lessOrEqualsColumnName()
 * @method \Cms\Orm\CmsMailDefinitionQuery equalsColumnReplyTo()
 * @method \Cms\Orm\CmsMailDefinitionQuery notEqualsColumnReplyTo()
 * @method \Cms\Orm\CmsMailDefinitionQuery greaterThanColumnReplyTo()
 * @method \Cms\Orm\CmsMailDefinitionQuery lessThanColumnReplyTo()
 * @method \Cms\Orm\CmsMailDefinitionQuery greaterOrEqualsColumnReplyTo()
 * @method \Cms\Orm\CmsMailDefinitionQuery lessOrEqualsColumnReplyTo()
 * @method \Cms\Orm\CmsMailDefinitionQuery equalsColumnFromName()
 * @method \Cms\Orm\CmsMailDefinitionQuery notEqualsColumnFromName()
 * @method \Cms\Orm\CmsMailDefinitionQuery greaterThanColumnFromName()
 * @method \Cms\Orm\CmsMailDefinitionQuery lessThanColumnFromName()
 * @method \Cms\Orm\CmsMailDefinitionQuery greaterOrEqualsColumnFromName()
 * @method \Cms\Orm\CmsMailDefinitionQuery lessOrEqualsColumnFromName()
 * @method \Cms\Orm\CmsMailDefinitionQuery equalsColumnSubject()
 * @method \Cms\Orm\CmsMailDefinitionQuery notEqualsColumnSubject()
 * @method \Cms\Orm\CmsMailDefinitionQuery greaterThanColumnSubject()
 * @method \Cms\Orm\CmsMailDefinitionQuery lessThanColumnSubject()
 * @method \Cms\Orm\CmsMailDefinitionQuery greaterOrEqualsColumnSubject()
 * @method \Cms\Orm\CmsMailDefinitionQuery lessOrEqualsColumnSubject()
 * @method \Cms\Orm\CmsMailDefinitionQuery equalsColumnMessage()
 * @method \Cms\Orm\CmsMailDefinitionQuery notEqualsColumnMessage()
 * @method \Cms\Orm\CmsMailDefinitionQuery greaterThanColumnMessage()
 * @method \Cms\Orm\CmsMailDefinitionQuery lessThanColumnMessage()
 * @method \Cms\Orm\CmsMailDefinitionQuery greaterOrEqualsColumnMessage()
 * @method \Cms\Orm\CmsMailDefinitionQuery lessOrEqualsColumnMessage()
 * @method \Cms\Orm\CmsMailDefinitionQuery equalsColumnHtml()
 * @method \Cms\Orm\CmsMailDefinitionQuery notEqualsColumnHtml()
 * @method \Cms\Orm\CmsMailDefinitionQuery greaterThanColumnHtml()
 * @method \Cms\Orm\CmsMailDefinitionQuery lessThanColumnHtml()
 * @method \Cms\Orm\CmsMailDefinitionQuery greaterOrEqualsColumnHtml()
 * @method \Cms\Orm\CmsMailDefinitionQuery lessOrEqualsColumnHtml()
 * @method \Cms\Orm\CmsMailDefinitionQuery equalsColumnDateAdd()
 * @method \Cms\Orm\CmsMailDefinitionQuery notEqualsColumnDateAdd()
 * @method \Cms\Orm\CmsMailDefinitionQuery greaterThanColumnDateAdd()
 * @method \Cms\Orm\CmsMailDefinitionQuery lessThanColumnDateAdd()
 * @method \Cms\Orm\CmsMailDefinitionQuery greaterOrEqualsColumnDateAdd()
 * @method \Cms\Orm\CmsMailDefinitionQuery lessOrEqualsColumnDateAdd()
 * @method \Cms\Orm\CmsMailDefinitionQuery equalsColumnDateModify()
 * @method \Cms\Orm\CmsMailDefinitionQuery notEqualsColumnDateModify()
 * @method \Cms\Orm\CmsMailDefinitionQuery greaterThanColumnDateModify()
 * @method \Cms\Orm\CmsMailDefinitionQuery lessThanColumnDateModify()
 * @method \Cms\Orm\CmsMailDefinitionQuery greaterOrEqualsColumnDateModify()
 * @method \Cms\Orm\CmsMailDefinitionQuery lessOrEqualsColumnDateModify()
 * @method \Cms\Orm\CmsMailDefinitionQuery equalsColumnActive()
 * @method \Cms\Orm\CmsMailDefinitionQuery notEqualsColumnActive()
 * @method \Cms\Orm\CmsMailDefinitionQuery greaterThanColumnActive()
 * @method \Cms\Orm\CmsMailDefinitionQuery lessThanColumnActive()
 * @method \Cms\Orm\CmsMailDefinitionQuery greaterOrEqualsColumnActive()
 * @method \Cms\Orm\CmsMailDefinitionQuery lessOrEqualsColumnActive()
 */
class CmsMailDefinitionQueryField extends \Mmi\Orm\QueryHelper\QueryField
{
}
