<?php

namespace Cms\Orm\QueryHelper;

/**
 * @method \Cms\Orm\CmsNewsQuery equals($value)
 * @method \Cms\Orm\CmsNewsQuery notEquals($value)
 * @method \Cms\Orm\CmsNewsQuery greater($value)
 * @method \Cms\Orm\CmsNewsQuery less($value)
 * @method \Cms\Orm\CmsNewsQuery greaterOrEquals($value)
 * @method \Cms\Orm\CmsNewsQuery lessOrEquals($value)
 * @method \Cms\Orm\CmsNewsQuery like($value)
 * @method \Cms\Orm\CmsNewsQuery ilike($value)
 * @method \Cms\Orm\CmsNewsQuery equalsColumnId()
 * @method \Cms\Orm\CmsNewsQuery notEqualsColumnId()
 * @method \Cms\Orm\CmsNewsQuery greaterThanColumnId()
 * @method \Cms\Orm\CmsNewsQuery lessThanColumnId()
 * @method \Cms\Orm\CmsNewsQuery greaterOrEqualsColumnId()
 * @method \Cms\Orm\CmsNewsQuery lessOrEqualsColumnId()
 * @method \Cms\Orm\CmsNewsQuery equalsColumnLang()
 * @method \Cms\Orm\CmsNewsQuery notEqualsColumnLang()
 * @method \Cms\Orm\CmsNewsQuery greaterThanColumnLang()
 * @method \Cms\Orm\CmsNewsQuery lessThanColumnLang()
 * @method \Cms\Orm\CmsNewsQuery greaterOrEqualsColumnLang()
 * @method \Cms\Orm\CmsNewsQuery lessOrEqualsColumnLang()
 * @method \Cms\Orm\CmsNewsQuery equalsColumnTitle()
 * @method \Cms\Orm\CmsNewsQuery notEqualsColumnTitle()
 * @method \Cms\Orm\CmsNewsQuery greaterThanColumnTitle()
 * @method \Cms\Orm\CmsNewsQuery lessThanColumnTitle()
 * @method \Cms\Orm\CmsNewsQuery greaterOrEqualsColumnTitle()
 * @method \Cms\Orm\CmsNewsQuery lessOrEqualsColumnTitle()
 * @method \Cms\Orm\CmsNewsQuery equalsColumnLead()
 * @method \Cms\Orm\CmsNewsQuery notEqualsColumnLead()
 * @method \Cms\Orm\CmsNewsQuery greaterThanColumnLead()
 * @method \Cms\Orm\CmsNewsQuery lessThanColumnLead()
 * @method \Cms\Orm\CmsNewsQuery greaterOrEqualsColumnLead()
 * @method \Cms\Orm\CmsNewsQuery lessOrEqualsColumnLead()
 * @method \Cms\Orm\CmsNewsQuery equalsColumnText()
 * @method \Cms\Orm\CmsNewsQuery notEqualsColumnText()
 * @method \Cms\Orm\CmsNewsQuery greaterThanColumnText()
 * @method \Cms\Orm\CmsNewsQuery lessThanColumnText()
 * @method \Cms\Orm\CmsNewsQuery greaterOrEqualsColumnText()
 * @method \Cms\Orm\CmsNewsQuery lessOrEqualsColumnText()
 * @method \Cms\Orm\CmsNewsQuery equalsColumnDateAdd()
 * @method \Cms\Orm\CmsNewsQuery notEqualsColumnDateAdd()
 * @method \Cms\Orm\CmsNewsQuery greaterThanColumnDateAdd()
 * @method \Cms\Orm\CmsNewsQuery lessThanColumnDateAdd()
 * @method \Cms\Orm\CmsNewsQuery greaterOrEqualsColumnDateAdd()
 * @method \Cms\Orm\CmsNewsQuery lessOrEqualsColumnDateAdd()
 * @method \Cms\Orm\CmsNewsQuery equalsColumnDateModify()
 * @method \Cms\Orm\CmsNewsQuery notEqualsColumnDateModify()
 * @method \Cms\Orm\CmsNewsQuery greaterThanColumnDateModify()
 * @method \Cms\Orm\CmsNewsQuery lessThanColumnDateModify()
 * @method \Cms\Orm\CmsNewsQuery greaterOrEqualsColumnDateModify()
 * @method \Cms\Orm\CmsNewsQuery lessOrEqualsColumnDateModify()
 * @method \Cms\Orm\CmsNewsQuery equalsColumnUri()
 * @method \Cms\Orm\CmsNewsQuery notEqualsColumnUri()
 * @method \Cms\Orm\CmsNewsQuery greaterThanColumnUri()
 * @method \Cms\Orm\CmsNewsQuery lessThanColumnUri()
 * @method \Cms\Orm\CmsNewsQuery greaterOrEqualsColumnUri()
 * @method \Cms\Orm\CmsNewsQuery lessOrEqualsColumnUri()
 * @method \Cms\Orm\CmsNewsQuery equalsColumnInternal()
 * @method \Cms\Orm\CmsNewsQuery notEqualsColumnInternal()
 * @method \Cms\Orm\CmsNewsQuery greaterThanColumnInternal()
 * @method \Cms\Orm\CmsNewsQuery lessThanColumnInternal()
 * @method \Cms\Orm\CmsNewsQuery greaterOrEqualsColumnInternal()
 * @method \Cms\Orm\CmsNewsQuery lessOrEqualsColumnInternal()
 * @method \Cms\Orm\CmsNewsQuery equalsColumnVisible()
 * @method \Cms\Orm\CmsNewsQuery notEqualsColumnVisible()
 * @method \Cms\Orm\CmsNewsQuery greaterThanColumnVisible()
 * @method \Cms\Orm\CmsNewsQuery lessThanColumnVisible()
 * @method \Cms\Orm\CmsNewsQuery greaterOrEqualsColumnVisible()
 * @method \Cms\Orm\CmsNewsQuery lessOrEqualsColumnVisible()
 */
class CmsNewsQueryField extends \Mmi\Orm\QueryHelper\QueryField {

}
