<?php

namespace Cms\Orm\QueryHelper;

/**
 * @method \Cms\Orm\CmsPageQuery equals($value)
 * @method \Cms\Orm\CmsPageQuery notEquals($value)
 * @method \Cms\Orm\CmsPageQuery greater($value)
 * @method \Cms\Orm\CmsPageQuery less($value)
 * @method \Cms\Orm\CmsPageQuery greaterOrEquals($value)
 * @method \Cms\Orm\CmsPageQuery lessOrEquals($value)
 * @method \Cms\Orm\CmsPageQuery like($value)
 * @method \Cms\Orm\CmsPageQuery ilike($value)
 * @method \Cms\Orm\CmsPageQuery equalsColumnId()
 * @method \Cms\Orm\CmsPageQuery notEqualsColumnId()
 * @method \Cms\Orm\CmsPageQuery greaterThanColumnId()
 * @method \Cms\Orm\CmsPageQuery lessThanColumnId()
 * @method \Cms\Orm\CmsPageQuery greaterOrEqualsColumnId()
 * @method \Cms\Orm\CmsPageQuery lessOrEqualsColumnId()
 * @method \Cms\Orm\CmsPageQuery equalsColumnName()
 * @method \Cms\Orm\CmsPageQuery notEqualsColumnName()
 * @method \Cms\Orm\CmsPageQuery greaterThanColumnName()
 * @method \Cms\Orm\CmsPageQuery lessThanColumnName()
 * @method \Cms\Orm\CmsPageQuery greaterOrEqualsColumnName()
 * @method \Cms\Orm\CmsPageQuery lessOrEqualsColumnName()
 * @method \Cms\Orm\CmsPageQuery equalsColumnCmsNavigationId()
 * @method \Cms\Orm\CmsPageQuery notEqualsColumnCmsNavigationId()
 * @method \Cms\Orm\CmsPageQuery greaterThanColumnCmsNavigationId()
 * @method \Cms\Orm\CmsPageQuery lessThanColumnCmsNavigationId()
 * @method \Cms\Orm\CmsPageQuery greaterOrEqualsColumnCmsNavigationId()
 * @method \Cms\Orm\CmsPageQuery lessOrEqualsColumnCmsNavigationId()
 * @method \Cms\Orm\CmsPageQuery equalsColumnCmsRouteId()
 * @method \Cms\Orm\CmsPageQuery notEqualsColumnCmsRouteId()
 * @method \Cms\Orm\CmsPageQuery greaterThanColumnCmsRouteId()
 * @method \Cms\Orm\CmsPageQuery lessThanColumnCmsRouteId()
 * @method \Cms\Orm\CmsPageQuery greaterOrEqualsColumnCmsRouteId()
 * @method \Cms\Orm\CmsPageQuery lessOrEqualsColumnCmsRouteId()
 * @method \Cms\Orm\CmsPageQuery equalsColumnText()
 * @method \Cms\Orm\CmsPageQuery notEqualsColumnText()
 * @method \Cms\Orm\CmsPageQuery greaterThanColumnText()
 * @method \Cms\Orm\CmsPageQuery lessThanColumnText()
 * @method \Cms\Orm\CmsPageQuery greaterOrEqualsColumnText()
 * @method \Cms\Orm\CmsPageQuery lessOrEqualsColumnText()
 * @method \Cms\Orm\CmsPageQuery equalsColumnActive()
 * @method \Cms\Orm\CmsPageQuery notEqualsColumnActive()
 * @method \Cms\Orm\CmsPageQuery greaterThanColumnActive()
 * @method \Cms\Orm\CmsPageQuery lessThanColumnActive()
 * @method \Cms\Orm\CmsPageQuery greaterOrEqualsColumnActive()
 * @method \Cms\Orm\CmsPageQuery lessOrEqualsColumnActive()
 * @method \Cms\Orm\CmsPageQuery equalsColumnDateAdd()
 * @method \Cms\Orm\CmsPageQuery notEqualsColumnDateAdd()
 * @method \Cms\Orm\CmsPageQuery greaterThanColumnDateAdd()
 * @method \Cms\Orm\CmsPageQuery lessThanColumnDateAdd()
 * @method \Cms\Orm\CmsPageQuery greaterOrEqualsColumnDateAdd()
 * @method \Cms\Orm\CmsPageQuery lessOrEqualsColumnDateAdd()
 * @method \Cms\Orm\CmsPageQuery equalsColumnDateModify()
 * @method \Cms\Orm\CmsPageQuery notEqualsColumnDateModify()
 * @method \Cms\Orm\CmsPageQuery greaterThanColumnDateModify()
 * @method \Cms\Orm\CmsPageQuery lessThanColumnDateModify()
 * @method \Cms\Orm\CmsPageQuery greaterOrEqualsColumnDateModify()
 * @method \Cms\Orm\CmsPageQuery lessOrEqualsColumnDateModify()
 * @method \Cms\Orm\CmsPageQuery equalsColumnCmsAuthId()
 * @method \Cms\Orm\CmsPageQuery notEqualsColumnCmsAuthId()
 * @method \Cms\Orm\CmsPageQuery greaterThanColumnCmsAuthId()
 * @method \Cms\Orm\CmsPageQuery lessThanColumnCmsAuthId()
 * @method \Cms\Orm\CmsPageQuery greaterOrEqualsColumnCmsAuthId()
 * @method \Cms\Orm\CmsPageQuery lessOrEqualsColumnCmsAuthId()
 */
class CmsPageQueryField extends \Mmi\Orm\QueryHelper\QueryField {

}
