<?php

namespace Cms\Orm\QueryHelper;

/**
 * @method \Cms\Orm\CmsPageWidgetQuery equals($value)
 * @method \Cms\Orm\CmsPageWidgetQuery notEquals($value)
 * @method \Cms\Orm\CmsPageWidgetQuery greater($value)
 * @method \Cms\Orm\CmsPageWidgetQuery less($value)
 * @method \Cms\Orm\CmsPageWidgetQuery greaterOrEquals($value)
 * @method \Cms\Orm\CmsPageWidgetQuery lessOrEquals($value)
 * @method \Cms\Orm\CmsPageWidgetQuery like($value)
 * @method \Cms\Orm\CmsPageWidgetQuery ilike($value)
 * @method \Cms\Orm\CmsPageWidgetQuery equalsColumnId()
 * @method \Cms\Orm\CmsPageWidgetQuery notEqualsColumnId()
 * @method \Cms\Orm\CmsPageWidgetQuery greaterThanColumnId()
 * @method \Cms\Orm\CmsPageWidgetQuery lessThanColumnId()
 * @method \Cms\Orm\CmsPageWidgetQuery greaterOrEqualsColumnId()
 * @method \Cms\Orm\CmsPageWidgetQuery lessOrEqualsColumnId()
 * @method \Cms\Orm\CmsPageWidgetQuery equalsColumnName()
 * @method \Cms\Orm\CmsPageWidgetQuery notEqualsColumnName()
 * @method \Cms\Orm\CmsPageWidgetQuery greaterThanColumnName()
 * @method \Cms\Orm\CmsPageWidgetQuery lessThanColumnName()
 * @method \Cms\Orm\CmsPageWidgetQuery greaterOrEqualsColumnName()
 * @method \Cms\Orm\CmsPageWidgetQuery lessOrEqualsColumnName()
 * @method \Cms\Orm\CmsPageWidgetQuery equalsColumnModule()
 * @method \Cms\Orm\CmsPageWidgetQuery notEqualsColumnModule()
 * @method \Cms\Orm\CmsPageWidgetQuery greaterThanColumnModule()
 * @method \Cms\Orm\CmsPageWidgetQuery lessThanColumnModule()
 * @method \Cms\Orm\CmsPageWidgetQuery greaterOrEqualsColumnModule()
 * @method \Cms\Orm\CmsPageWidgetQuery lessOrEqualsColumnModule()
 * @method \Cms\Orm\CmsPageWidgetQuery equalsColumnController()
 * @method \Cms\Orm\CmsPageWidgetQuery notEqualsColumnController()
 * @method \Cms\Orm\CmsPageWidgetQuery greaterThanColumnController()
 * @method \Cms\Orm\CmsPageWidgetQuery lessThanColumnController()
 * @method \Cms\Orm\CmsPageWidgetQuery greaterOrEqualsColumnController()
 * @method \Cms\Orm\CmsPageWidgetQuery lessOrEqualsColumnController()
 * @method \Cms\Orm\CmsPageWidgetQuery equalsColumnAction()
 * @method \Cms\Orm\CmsPageWidgetQuery notEqualsColumnAction()
 * @method \Cms\Orm\CmsPageWidgetQuery greaterThanColumnAction()
 * @method \Cms\Orm\CmsPageWidgetQuery lessThanColumnAction()
 * @method \Cms\Orm\CmsPageWidgetQuery greaterOrEqualsColumnAction()
 * @method \Cms\Orm\CmsPageWidgetQuery lessOrEqualsColumnAction()
 * @method \Cms\Orm\CmsPageWidgetQuery equalsColumnParams()
 * @method \Cms\Orm\CmsPageWidgetQuery notEqualsColumnParams()
 * @method \Cms\Orm\CmsPageWidgetQuery greaterThanColumnParams()
 * @method \Cms\Orm\CmsPageWidgetQuery lessThanColumnParams()
 * @method \Cms\Orm\CmsPageWidgetQuery greaterOrEqualsColumnParams()
 * @method \Cms\Orm\CmsPageWidgetQuery lessOrEqualsColumnParams()
 * @method \Cms\Orm\CmsPageWidgetQuery equalsColumnActive()
 * @method \Cms\Orm\CmsPageWidgetQuery notEqualsColumnActive()
 * @method \Cms\Orm\CmsPageWidgetQuery greaterThanColumnActive()
 * @method \Cms\Orm\CmsPageWidgetQuery lessThanColumnActive()
 * @method \Cms\Orm\CmsPageWidgetQuery greaterOrEqualsColumnActive()
 * @method \Cms\Orm\CmsPageWidgetQuery lessOrEqualsColumnActive()
 */
class CmsPageWidgetQueryField extends \Mmi\Orm\QueryHelper\QueryField {

}
