<?php

namespace Cms\Orm\QueryHelper;

/**
 * @method \Cms\Orm\CmsRouteQuery equals($value)
 * @method \Cms\Orm\CmsRouteQuery notEquals($value)
 * @method \Cms\Orm\CmsRouteQuery greater($value)
 * @method \Cms\Orm\CmsRouteQuery less($value)
 * @method \Cms\Orm\CmsRouteQuery greaterOrEquals($value)
 * @method \Cms\Orm\CmsRouteQuery lessOrEquals($value)
 * @method \Cms\Orm\CmsRouteQuery like($value)
 * @method \Cms\Orm\CmsRouteQuery ilike($value)
 * @method \Cms\Orm\CmsRouteQuery between($from, $to)
 * @method \Cms\Orm\CmsRouteQuery equalsColumnId()
 * @method \Cms\Orm\CmsRouteQuery notEqualsColumnId()
 * @method \Cms\Orm\CmsRouteQuery greaterThanColumnId()
 * @method \Cms\Orm\CmsRouteQuery lessThanColumnId()
 * @method \Cms\Orm\CmsRouteQuery greaterOrEqualsColumnId()
 * @method \Cms\Orm\CmsRouteQuery lessOrEqualsColumnId()
 * @method \Cms\Orm\CmsRouteQuery equalsColumnPattern()
 * @method \Cms\Orm\CmsRouteQuery notEqualsColumnPattern()
 * @method \Cms\Orm\CmsRouteQuery greaterThanColumnPattern()
 * @method \Cms\Orm\CmsRouteQuery lessThanColumnPattern()
 * @method \Cms\Orm\CmsRouteQuery greaterOrEqualsColumnPattern()
 * @method \Cms\Orm\CmsRouteQuery lessOrEqualsColumnPattern()
 * @method \Cms\Orm\CmsRouteQuery equalsColumnReplace()
 * @method \Cms\Orm\CmsRouteQuery notEqualsColumnReplace()
 * @method \Cms\Orm\CmsRouteQuery greaterThanColumnReplace()
 * @method \Cms\Orm\CmsRouteQuery lessThanColumnReplace()
 * @method \Cms\Orm\CmsRouteQuery greaterOrEqualsColumnReplace()
 * @method \Cms\Orm\CmsRouteQuery lessOrEqualsColumnReplace()
 * @method \Cms\Orm\CmsRouteQuery equalsColumnDefault()
 * @method \Cms\Orm\CmsRouteQuery notEqualsColumnDefault()
 * @method \Cms\Orm\CmsRouteQuery greaterThanColumnDefault()
 * @method \Cms\Orm\CmsRouteQuery lessThanColumnDefault()
 * @method \Cms\Orm\CmsRouteQuery greaterOrEqualsColumnDefault()
 * @method \Cms\Orm\CmsRouteQuery lessOrEqualsColumnDefault()
 * @method \Cms\Orm\CmsRouteQuery equalsColumnOrder()
 * @method \Cms\Orm\CmsRouteQuery notEqualsColumnOrder()
 * @method \Cms\Orm\CmsRouteQuery greaterThanColumnOrder()
 * @method \Cms\Orm\CmsRouteQuery lessThanColumnOrder()
 * @method \Cms\Orm\CmsRouteQuery greaterOrEqualsColumnOrder()
 * @method \Cms\Orm\CmsRouteQuery lessOrEqualsColumnOrder()
 * @method \Cms\Orm\CmsRouteQuery equalsColumnActive()
 * @method \Cms\Orm\CmsRouteQuery notEqualsColumnActive()
 * @method \Cms\Orm\CmsRouteQuery greaterThanColumnActive()
 * @method \Cms\Orm\CmsRouteQuery lessThanColumnActive()
 * @method \Cms\Orm\CmsRouteQuery greaterOrEqualsColumnActive()
 * @method \Cms\Orm\CmsRouteQuery lessOrEqualsColumnActive()
 */
class CmsRouteQueryField extends \Mmi\Orm\QueryHelper\QueryField {

}
