<?php

namespace Cms\Orm\QueryHelper;

/**
 * @method \Cms\Orm\CmsStatDateQuery equals($value)
 * @method \Cms\Orm\CmsStatDateQuery notEquals($value)
 * @method \Cms\Orm\CmsStatDateQuery greater($value)
 * @method \Cms\Orm\CmsStatDateQuery less($value)
 * @method \Cms\Orm\CmsStatDateQuery greaterOrEquals($value)
 * @method \Cms\Orm\CmsStatDateQuery lessOrEquals($value)
 * @method \Cms\Orm\CmsStatDateQuery like($value)
 * @method \Cms\Orm\CmsStatDateQuery notLike($value)
 * @method \Cms\Orm\CmsStatDateQuery between($from, $to)
 * @method \Cms\Orm\CmsStatDateQuery equalsColumnId()
 * @method \Cms\Orm\CmsStatDateQuery notEqualsColumnId()
 * @method \Cms\Orm\CmsStatDateQuery greaterThanColumnId()
 * @method \Cms\Orm\CmsStatDateQuery lessThanColumnId()
 * @method \Cms\Orm\CmsStatDateQuery greaterOrEqualsColumnId()
 * @method \Cms\Orm\CmsStatDateQuery lessOrEqualsColumnId()
 * @method \Cms\Orm\CmsStatDateQuery equalsColumnHour()
 * @method \Cms\Orm\CmsStatDateQuery notEqualsColumnHour()
 * @method \Cms\Orm\CmsStatDateQuery greaterThanColumnHour()
 * @method \Cms\Orm\CmsStatDateQuery lessThanColumnHour()
 * @method \Cms\Orm\CmsStatDateQuery greaterOrEqualsColumnHour()
 * @method \Cms\Orm\CmsStatDateQuery lessOrEqualsColumnHour()
 * @method \Cms\Orm\CmsStatDateQuery equalsColumnDay()
 * @method \Cms\Orm\CmsStatDateQuery notEqualsColumnDay()
 * @method \Cms\Orm\CmsStatDateQuery greaterThanColumnDay()
 * @method \Cms\Orm\CmsStatDateQuery lessThanColumnDay()
 * @method \Cms\Orm\CmsStatDateQuery greaterOrEqualsColumnDay()
 * @method \Cms\Orm\CmsStatDateQuery lessOrEqualsColumnDay()
 * @method \Cms\Orm\CmsStatDateQuery equalsColumnMonth()
 * @method \Cms\Orm\CmsStatDateQuery notEqualsColumnMonth()
 * @method \Cms\Orm\CmsStatDateQuery greaterThanColumnMonth()
 * @method \Cms\Orm\CmsStatDateQuery lessThanColumnMonth()
 * @method \Cms\Orm\CmsStatDateQuery greaterOrEqualsColumnMonth()
 * @method \Cms\Orm\CmsStatDateQuery lessOrEqualsColumnMonth()
 * @method \Cms\Orm\CmsStatDateQuery equalsColumnYear()
 * @method \Cms\Orm\CmsStatDateQuery notEqualsColumnYear()
 * @method \Cms\Orm\CmsStatDateQuery greaterThanColumnYear()
 * @method \Cms\Orm\CmsStatDateQuery lessThanColumnYear()
 * @method \Cms\Orm\CmsStatDateQuery greaterOrEqualsColumnYear()
 * @method \Cms\Orm\CmsStatDateQuery lessOrEqualsColumnYear()
 * @method \Cms\Orm\CmsStatDateQuery equalsColumnObject()
 * @method \Cms\Orm\CmsStatDateQuery notEqualsColumnObject()
 * @method \Cms\Orm\CmsStatDateQuery greaterThanColumnObject()
 * @method \Cms\Orm\CmsStatDateQuery lessThanColumnObject()
 * @method \Cms\Orm\CmsStatDateQuery greaterOrEqualsColumnObject()
 * @method \Cms\Orm\CmsStatDateQuery lessOrEqualsColumnObject()
 * @method \Cms\Orm\CmsStatDateQuery equalsColumnObjectId()
 * @method \Cms\Orm\CmsStatDateQuery notEqualsColumnObjectId()
 * @method \Cms\Orm\CmsStatDateQuery greaterThanColumnObjectId()
 * @method \Cms\Orm\CmsStatDateQuery lessThanColumnObjectId()
 * @method \Cms\Orm\CmsStatDateQuery greaterOrEqualsColumnObjectId()
 * @method \Cms\Orm\CmsStatDateQuery lessOrEqualsColumnObjectId()
 * @method \Cms\Orm\CmsStatDateQuery equalsColumnCount()
 * @method \Cms\Orm\CmsStatDateQuery notEqualsColumnCount()
 * @method \Cms\Orm\CmsStatDateQuery greaterThanColumnCount()
 * @method \Cms\Orm\CmsStatDateQuery lessThanColumnCount()
 * @method \Cms\Orm\CmsStatDateQuery greaterOrEqualsColumnCount()
 * @method \Cms\Orm\CmsStatDateQuery lessOrEqualsColumnCount()
 */
class CmsStatDateQueryField extends \Mmi\Orm\QueryHelper\QueryField
{

}
