<?php

namespace Cms\Orm\Route;

/**
 * @method \Cms\Orm\Route\Query equals($value)
 * @method \Cms\Orm\Route\Query notEquals($value)
 * @method \Cms\Orm\Route\Query greater($value)
 * @method \Cms\Orm\Route\Query less($value)
 * @method \Cms\Orm\Route\Query greaterOrEquals($value)
 * @method \Cms\Orm\Route\Query lessOrEquals($value)
 * @method \Cms\Orm\Route\Query like($value)
 * @method \Cms\Orm\Route\Query ilike($value)
 * @method \Cms\Orm\Route\Query equalsColumnId()
 * @method \Cms\Orm\Route\Query notEqualsColumnId()
 * @method \Cms\Orm\Route\Query greaterThanColumnId()
 * @method \Cms\Orm\Route\Query lessThanColumnId()
 * @method \Cms\Orm\Route\Query greaterOrEqualsColumnId()
 * @method \Cms\Orm\Route\Query lessOrEqualsColumnId()
 * @method \Cms\Orm\Route\Query equalsColumnPattern()
 * @method \Cms\Orm\Route\Query notEqualsColumnPattern()
 * @method \Cms\Orm\Route\Query greaterThanColumnPattern()
 * @method \Cms\Orm\Route\Query lessThanColumnPattern()
 * @method \Cms\Orm\Route\Query greaterOrEqualsColumnPattern()
 * @method \Cms\Orm\Route\Query lessOrEqualsColumnPattern()
 * @method \Cms\Orm\Route\Query equalsColumnReplace()
 * @method \Cms\Orm\Route\Query notEqualsColumnReplace()
 * @method \Cms\Orm\Route\Query greaterThanColumnReplace()
 * @method \Cms\Orm\Route\Query lessThanColumnReplace()
 * @method \Cms\Orm\Route\Query greaterOrEqualsColumnReplace()
 * @method \Cms\Orm\Route\Query lessOrEqualsColumnReplace()
 * @method \Cms\Orm\Route\Query equalsColumnDefault()
 * @method \Cms\Orm\Route\Query notEqualsColumnDefault()
 * @method \Cms\Orm\Route\Query greaterThanColumnDefault()
 * @method \Cms\Orm\Route\Query lessThanColumnDefault()
 * @method \Cms\Orm\Route\Query greaterOrEqualsColumnDefault()
 * @method \Cms\Orm\Route\Query lessOrEqualsColumnDefault()
 * @method \Cms\Orm\Route\Query equalsColumnOrder()
 * @method \Cms\Orm\Route\Query notEqualsColumnOrder()
 * @method \Cms\Orm\Route\Query greaterThanColumnOrder()
 * @method \Cms\Orm\Route\Query lessThanColumnOrder()
 * @method \Cms\Orm\Route\Query greaterOrEqualsColumnOrder()
 * @method \Cms\Orm\Route\Query lessOrEqualsColumnOrder()
 * @method \Cms\Orm\Route\Query equalsColumnActive()
 * @method \Cms\Orm\Route\Query notEqualsColumnActive()
 * @method \Cms\Orm\Route\Query greaterThanColumnActive()
 * @method \Cms\Orm\Route\Query lessThanColumnActive()
 * @method \Cms\Orm\Route\Query greaterOrEqualsColumnActive()
 * @method \Cms\Orm\Route\Query lessOrEqualsColumnActive()
 */
class QueryField extends \Mmi\Orm\QueryField {

}
