<?php

namespace Cms\Orm\News\Query;

/**
 * @method \Cms\Orm\News\Query equals($value)
 * @method \Cms\Orm\News\Query notEquals($value)
 * @method \Cms\Orm\News\Query greater($value)
 * @method \Cms\Orm\News\Query less($value)
 * @method \Cms\Orm\News\Query greaterOrEquals($value)
 * @method \Cms\Orm\News\Query lessOrEquals($value)
 * @method \Cms\Orm\News\Query like($value)
 * @method \Cms\Orm\News\Query ilike($value)
 * @method \Cms\Orm\News\Query equalsColumnId()
 * @method \Cms\Orm\News\Query notEqualsColumnId()
 * @method \Cms\Orm\News\Query greaterThanColumnId()
 * @method \Cms\Orm\News\Query lessThanColumnId()
 * @method \Cms\Orm\News\Query greaterOrEqualsColumnId()
 * @method \Cms\Orm\News\Query lessOrEqualsColumnId()
 * @method \Cms\Orm\News\Query equalsColumnLang()
 * @method \Cms\Orm\News\Query notEqualsColumnLang()
 * @method \Cms\Orm\News\Query greaterThanColumnLang()
 * @method \Cms\Orm\News\Query lessThanColumnLang()
 * @method \Cms\Orm\News\Query greaterOrEqualsColumnLang()
 * @method \Cms\Orm\News\Query lessOrEqualsColumnLang()
 * @method \Cms\Orm\News\Query equalsColumnTitle()
 * @method \Cms\Orm\News\Query notEqualsColumnTitle()
 * @method \Cms\Orm\News\Query greaterThanColumnTitle()
 * @method \Cms\Orm\News\Query lessThanColumnTitle()
 * @method \Cms\Orm\News\Query greaterOrEqualsColumnTitle()
 * @method \Cms\Orm\News\Query lessOrEqualsColumnTitle()
 * @method \Cms\Orm\News\Query equalsColumnLead()
 * @method \Cms\Orm\News\Query notEqualsColumnLead()
 * @method \Cms\Orm\News\Query greaterThanColumnLead()
 * @method \Cms\Orm\News\Query lessThanColumnLead()
 * @method \Cms\Orm\News\Query greaterOrEqualsColumnLead()
 * @method \Cms\Orm\News\Query lessOrEqualsColumnLead()
 * @method \Cms\Orm\News\Query equalsColumnText()
 * @method \Cms\Orm\News\Query notEqualsColumnText()
 * @method \Cms\Orm\News\Query greaterThanColumnText()
 * @method \Cms\Orm\News\Query lessThanColumnText()
 * @method \Cms\Orm\News\Query greaterOrEqualsColumnText()
 * @method \Cms\Orm\News\Query lessOrEqualsColumnText()
 * @method \Cms\Orm\News\Query equalsColumnDateAdd()
 * @method \Cms\Orm\News\Query notEqualsColumnDateAdd()
 * @method \Cms\Orm\News\Query greaterThanColumnDateAdd()
 * @method \Cms\Orm\News\Query lessThanColumnDateAdd()
 * @method \Cms\Orm\News\Query greaterOrEqualsColumnDateAdd()
 * @method \Cms\Orm\News\Query lessOrEqualsColumnDateAdd()
 * @method \Cms\Orm\News\Query equalsColumnDateModify()
 * @method \Cms\Orm\News\Query notEqualsColumnDateModify()
 * @method \Cms\Orm\News\Query greaterThanColumnDateModify()
 * @method \Cms\Orm\News\Query lessThanColumnDateModify()
 * @method \Cms\Orm\News\Query greaterOrEqualsColumnDateModify()
 * @method \Cms\Orm\News\Query lessOrEqualsColumnDateModify()
 * @method \Cms\Orm\News\Query equalsColumnUri()
 * @method \Cms\Orm\News\Query notEqualsColumnUri()
 * @method \Cms\Orm\News\Query greaterThanColumnUri()
 * @method \Cms\Orm\News\Query lessThanColumnUri()
 * @method \Cms\Orm\News\Query greaterOrEqualsColumnUri()
 * @method \Cms\Orm\News\Query lessOrEqualsColumnUri()
 * @method \Cms\Orm\News\Query equalsColumnInternal()
 * @method \Cms\Orm\News\Query notEqualsColumnInternal()
 * @method \Cms\Orm\News\Query greaterThanColumnInternal()
 * @method \Cms\Orm\News\Query lessThanColumnInternal()
 * @method \Cms\Orm\News\Query greaterOrEqualsColumnInternal()
 * @method \Cms\Orm\News\Query lessOrEqualsColumnInternal()
 * @method \Cms\Orm\News\Query equalsColumnVisible()
 * @method \Cms\Orm\News\Query notEqualsColumnVisible()
 * @method \Cms\Orm\News\Query greaterThanColumnVisible()
 * @method \Cms\Orm\News\Query lessThanColumnVisible()
 * @method \Cms\Orm\News\Query greaterOrEqualsColumnVisible()
 * @method \Cms\Orm\News\Query lessOrEqualsColumnVisible()
 */
class Field extends \Mmi\Orm\Query\Field {

}
