{headScript()->appendFile('/resource/cmsAdmin/vendors/js/popper.min.js')}
{headScript()->appendFile('/resource/cmsAdmin/vendors/js/bootstrap.min.js')}
{headScript()->appendFile('/resource/cmsAdmin/vendors/js/pace.min.js')}
{headScript()->appendFile('/resource/cmsAdmin/js/form.js')}
{headScript()->appendFile('/resource/cmsAdmin/js/default.js')}
{headScript()->appendFile('/resource/cmsAdmin/js/app.js')}
{headScript()}
</body>
</html>