{headScript()->prependFile('/resource/cmsAdmin/vendors/js/jquery.min.js')}
{headScript()->appendFile('/resource/cmsAdmin/js/jquery-ui/jquery-ui.min.js')}
{headScript()->appendFile('/resource/cmsAdmin/vendors/js/popper.min.js')}
{headScript()->appendFile('/resource/cmsAdmin/vendors/js/bootstrap.min.js')}
{headScript()->appendFile('/resource/cmsAdmin/vendors/js/pace.min.js')}
{headScript()->appendFile('/resource/cmsAdmin/js/jquery/datetimepicker.js')}
{headScript()->appendFile('/resource/cmsAdmin/js/form.js')}
{headScript()->appendFile('/resource/cmsAdmin/js/default.js')}
{headScript()->appendFile('/resource/cmsAdmin/js/app.js')}
{headScript()}
</body>
</html>