<?php

namespace Cms\Orm\Page\Query;

/**
 * @method \Cms\Orm\Page\Query equals($value)
 * @method \Cms\Orm\Page\Query notEquals($value)
 * @method \Cms\Orm\Page\Query greater($value)
 * @method \Cms\Orm\Page\Query less($value)
 * @method \Cms\Orm\Page\Query greaterOrEquals($value)
 * @method \Cms\Orm\Page\Query lessOrEquals($value)
 * @method \Cms\Orm\Page\Query like($value)
 * @method \Cms\Orm\Page\Query ilike($value)
 * @method \Cms\Orm\Page\Query equalsColumnId()
 * @method \Cms\Orm\Page\Query notEqualsColumnId()
 * @method \Cms\Orm\Page\Query greaterThanColumnId()
 * @method \Cms\Orm\Page\Query lessThanColumnId()
 * @method \Cms\Orm\Page\Query greaterOrEqualsColumnId()
 * @method \Cms\Orm\Page\Query lessOrEqualsColumnId()
 * @method \Cms\Orm\Page\Query equalsColumnName()
 * @method \Cms\Orm\Page\Query notEqualsColumnName()
 * @method \Cms\Orm\Page\Query greaterThanColumnName()
 * @method \Cms\Orm\Page\Query lessThanColumnName()
 * @method \Cms\Orm\Page\Query greaterOrEqualsColumnName()
 * @method \Cms\Orm\Page\Query lessOrEqualsColumnName()
 * @method \Cms\Orm\Page\Query equalsColumnCmsNavigationId()
 * @method \Cms\Orm\Page\Query notEqualsColumnCmsNavigationId()
 * @method \Cms\Orm\Page\Query greaterThanColumnCmsNavigationId()
 * @method \Cms\Orm\Page\Query lessThanColumnCmsNavigationId()
 * @method \Cms\Orm\Page\Query greaterOrEqualsColumnCmsNavigationId()
 * @method \Cms\Orm\Page\Query lessOrEqualsColumnCmsNavigationId()
 * @method \Cms\Orm\Page\Query equalsColumnCmsRouteId()
 * @method \Cms\Orm\Page\Query notEqualsColumnCmsRouteId()
 * @method \Cms\Orm\Page\Query greaterThanColumnCmsRouteId()
 * @method \Cms\Orm\Page\Query lessThanColumnCmsRouteId()
 * @method \Cms\Orm\Page\Query greaterOrEqualsColumnCmsRouteId()
 * @method \Cms\Orm\Page\Query lessOrEqualsColumnCmsRouteId()
 * @method \Cms\Orm\Page\Query equalsColumnText()
 * @method \Cms\Orm\Page\Query notEqualsColumnText()
 * @method \Cms\Orm\Page\Query greaterThanColumnText()
 * @method \Cms\Orm\Page\Query lessThanColumnText()
 * @method \Cms\Orm\Page\Query greaterOrEqualsColumnText()
 * @method \Cms\Orm\Page\Query lessOrEqualsColumnText()
 * @method \Cms\Orm\Page\Query equalsColumnActive()
 * @method \Cms\Orm\Page\Query notEqualsColumnActive()
 * @method \Cms\Orm\Page\Query greaterThanColumnActive()
 * @method \Cms\Orm\Page\Query lessThanColumnActive()
 * @method \Cms\Orm\Page\Query greaterOrEqualsColumnActive()
 * @method \Cms\Orm\Page\Query lessOrEqualsColumnActive()
 * @method \Cms\Orm\Page\Query equalsColumnCmsAuthId()
 * @method \Cms\Orm\Page\Query notEqualsColumnCmsAuthId()
 * @method \Cms\Orm\Page\Query greaterThanColumnCmsAuthId()
 * @method \Cms\Orm\Page\Query lessThanColumnCmsAuthId()
 * @method \Cms\Orm\Page\Query greaterOrEqualsColumnCmsAuthId()
 * @method \Cms\Orm\Page\Query lessOrEqualsColumnCmsAuthId()
 * @method \Cms\Orm\Page\Query equalsColumnDateAdd()
 * @method \Cms\Orm\Page\Query notEqualsColumnDateAdd()
 * @method \Cms\Orm\Page\Query greaterThanColumnDateAdd()
 * @method \Cms\Orm\Page\Query lessThanColumnDateAdd()
 * @method \Cms\Orm\Page\Query greaterOrEqualsColumnDateAdd()
 * @method \Cms\Orm\Page\Query lessOrEqualsColumnDateAdd()
 * @method \Cms\Orm\Page\Query equalsColumnDateModify()
 * @method \Cms\Orm\Page\Query notEqualsColumnDateModify()
 * @method \Cms\Orm\Page\Query greaterThanColumnDateModify()
 * @method \Cms\Orm\Page\Query lessThanColumnDateModify()
 * @method \Cms\Orm\Page\Query greaterOrEqualsColumnDateModify()
 * @method \Cms\Orm\Page\Query lessOrEqualsColumnDateModify()
 */
class Field extends \Mmi\Orm\Query\Field {

}
