<?php

namespace Cms\Orm\Contact;

//<editor-fold defaultstate="collapsed" desc="cms_contact Query">
/**
 * @method \Cms\Orm\Contact\Query limit($limit = null)
 * @method \Cms\Orm\Contact\Query offset($offset = null)
 * @method \Cms\Orm\Contact\Query orderAsc($fieldName, $tableName = null)
 * @method \Cms\Orm\Contact\Query orderDesc($fieldName, $tableName = null)
 * @method \Cms\Orm\Contact\Query andQuery(\Mmi\Orm\Query $query)
 * @method \Cms\Orm\Contact\Query whereQuery(\Mmi\Orm\Query $query)
 * @method \Cms\Orm\Contact\Query orQuery(\Mmi\Orm\Query $query)
 * @method \Cms\Orm\Contact\Query resetOrder()
 * @method \Cms\Orm\Contact\Query resetWhere()
 * @method \Cms\Orm\Contact\QueryField whereId()
 * @method \Cms\Orm\Contact\QueryField andFieldId()
 * @method \Cms\Orm\Contact\QueryField orFieldId()
 * @method \Cms\Orm\Contact\Query orderAscId()
 * @method \Cms\Orm\Contact\Query orderDescId()
 * @method \Cms\Orm\Contact\Query groupById()
 * @method \Cms\Orm\Contact\QueryField whereCmsContactOptionId()
 * @method \Cms\Orm\Contact\QueryField andFieldCmsContactOptionId()
 * @method \Cms\Orm\Contact\QueryField orFieldCmsContactOptionId()
 * @method \Cms\Orm\Contact\Query orderAscCmsContactOptionId()
 * @method \Cms\Orm\Contact\Query orderDescCmsContactOptionId()
 * @method \Cms\Orm\Contact\Query groupByCmsContactOptionId()
 * @method \Cms\Orm\Contact\QueryField whereDateAdd()
 * @method \Cms\Orm\Contact\QueryField andFieldDateAdd()
 * @method \Cms\Orm\Contact\QueryField orFieldDateAdd()
 * @method \Cms\Orm\Contact\Query orderAscDateAdd()
 * @method \Cms\Orm\Contact\Query orderDescDateAdd()
 * @method \Cms\Orm\Contact\Query groupByDateAdd()
 * @method \Cms\Orm\Contact\QueryField whereText()
 * @method \Cms\Orm\Contact\QueryField andFieldText()
 * @method \Cms\Orm\Contact\QueryField orFieldText()
 * @method \Cms\Orm\Contact\Query orderAscText()
 * @method \Cms\Orm\Contact\Query orderDescText()
 * @method \Cms\Orm\Contact\Query groupByText()
 * @method \Cms\Orm\Contact\QueryField whereReply()
 * @method \Cms\Orm\Contact\QueryField andFieldReply()
 * @method \Cms\Orm\Contact\QueryField orFieldReply()
 * @method \Cms\Orm\Contact\Query orderAscReply()
 * @method \Cms\Orm\Contact\Query orderDescReply()
 * @method \Cms\Orm\Contact\Query groupByReply()
 * @method \Cms\Orm\Contact\QueryField whereCmsAuthIdReply()
 * @method \Cms\Orm\Contact\QueryField andFieldCmsAuthIdReply()
 * @method \Cms\Orm\Contact\QueryField orFieldCmsAuthIdReply()
 * @method \Cms\Orm\Contact\Query orderAscCmsAuthIdReply()
 * @method \Cms\Orm\Contact\Query orderDescCmsAuthIdReply()
 * @method \Cms\Orm\Contact\Query groupByCmsAuthIdReply()
 * @method \Cms\Orm\Contact\QueryField whereUri()
 * @method \Cms\Orm\Contact\QueryField andFieldUri()
 * @method \Cms\Orm\Contact\QueryField orFieldUri()
 * @method \Cms\Orm\Contact\Query orderAscUri()
 * @method \Cms\Orm\Contact\Query orderDescUri()
 * @method \Cms\Orm\Contact\Query groupByUri()
 * @method \Cms\Orm\Contact\QueryField whereName()
 * @method \Cms\Orm\Contact\QueryField andFieldName()
 * @method \Cms\Orm\Contact\QueryField orFieldName()
 * @method \Cms\Orm\Contact\Query orderAscName()
 * @method \Cms\Orm\Contact\Query orderDescName()
 * @method \Cms\Orm\Contact\Query groupByName()
 * @method \Cms\Orm\Contact\QueryField wherePhone()
 * @method \Cms\Orm\Contact\QueryField andFieldPhone()
 * @method \Cms\Orm\Contact\QueryField orFieldPhone()
 * @method \Cms\Orm\Contact\Query orderAscPhone()
 * @method \Cms\Orm\Contact\Query orderDescPhone()
 * @method \Cms\Orm\Contact\Query groupByPhone()
 * @method \Cms\Orm\Contact\QueryField whereEmail()
 * @method \Cms\Orm\Contact\QueryField andFieldEmail()
 * @method \Cms\Orm\Contact\QueryField orFieldEmail()
 * @method \Cms\Orm\Contact\Query orderAscEmail()
 * @method \Cms\Orm\Contact\Query orderDescEmail()
 * @method \Cms\Orm\Contact\Query groupByEmail()
 * @method \Cms\Orm\Contact\QueryField whereIp()
 * @method \Cms\Orm\Contact\QueryField andFieldIp()
 * @method \Cms\Orm\Contact\QueryField orFieldIp()
 * @method \Cms\Orm\Contact\Query orderAscIp()
 * @method \Cms\Orm\Contact\Query orderDescIp()
 * @method \Cms\Orm\Contact\Query groupByIp()
 * @method \Cms\Orm\Contact\QueryField whereCmsAuthId()
 * @method \Cms\Orm\Contact\QueryField andFieldCmsAuthId()
 * @method \Cms\Orm\Contact\QueryField orFieldCmsAuthId()
 * @method \Cms\Orm\Contact\Query orderAscCmsAuthId()
 * @method \Cms\Orm\Contact\Query orderDescCmsAuthId()
 * @method \Cms\Orm\Contact\Query groupByCmsAuthId()
 * @method \Cms\Orm\Contact\QueryField whereActive()
 * @method \Cms\Orm\Contact\QueryField andFieldActive()
 * @method \Cms\Orm\Contact\QueryField orFieldActive()
 * @method \Cms\Orm\Contact\Query orderAscActive()
 * @method \Cms\Orm\Contact\Query orderDescActive()
 * @method \Cms\Orm\Contact\Query groupByActive()
 * @method \Cms\Orm\Contact\QueryField andField($fieldName, $tableName = null)
 * @method \Cms\Orm\Contact\QueryField where($fieldName, $tableName = null)
 * @method \Cms\Orm\Contact\QueryField orField($fieldName, $tableName = null)
 * @method \Cms\Orm\Contact\QueryJoin join($tableName, $targetTableName = null)
 * @method \Cms\Orm\Contact\QueryJoin joinLeft($tableName, $targetTableName = null)
 * @method \Cms\Orm\Contact\Record[] find()
 * @method \Cms\Orm\Contact\Record findFirst()
 * @method \Cms\Orm\Contact\Record findPk($value)
 */
//</editor-fold>
class Query extends \Mmi\Orm\Query {

	protected $_tableName = 'cms_contact';

	/**
	 * @return \Cms\Orm\Contact\Query
	 */
	public static function factory($daoClassName = null) {
		return new self($daoClassName);
	}

}
