<?php

namespace Cms\Orm\Contact;

//<editor-fold defaultstate="collapsed" desc="cms_contact Query">
/**
 * @method \Cms\Orm\Contact\Query limit($limit = null)
 * @method \Cms\Orm\Contact\Query offset($offset = null)
 * @method \Cms\Orm\Contact\Query orderAsc($fieldName, $tableName = null)
 * @method \Cms\Orm\Contact\Query orderDesc($fieldName, $tableName = null)
 * @method \Cms\Orm\Contact\Query andQuery(\Mmi\Orm\Query $query)
 * @method \Cms\Orm\Contact\Query whereQuery(\Mmi\Orm\Query $query)
 * @method \Cms\Orm\Contact\Query orQuery(\Mmi\Orm\Query $query)
 * @method \Cms\Orm\Contact\Query resetOrder()
 * @method \Cms\Orm\Contact\Query resetWhere()
 * @method \Cms\Orm\Contact\Query\Field whereId()
 * @method \Cms\Orm\Contact\Query\Field andFieldId()
 * @method \Cms\Orm\Contact\Query\Field orFieldId()
 * @method \Cms\Orm\Contact\Query orderAscId()
 * @method \Cms\Orm\Contact\Query orderDescId()
 * @method \Cms\Orm\Contact\Query groupById()
 * @method \Cms\Orm\Contact\Query\Field whereCmsContactOptionId()
 * @method \Cms\Orm\Contact\Query\Field andFieldCmsContactOptionId()
 * @method \Cms\Orm\Contact\Query\Field orFieldCmsContactOptionId()
 * @method \Cms\Orm\Contact\Query orderAscCmsContactOptionId()
 * @method \Cms\Orm\Contact\Query orderDescCmsContactOptionId()
 * @method \Cms\Orm\Contact\Query groupByCmsContactOptionId()
 * @method \Cms\Orm\Contact\Query\Field whereDateAdd()
 * @method \Cms\Orm\Contact\Query\Field andFieldDateAdd()
 * @method \Cms\Orm\Contact\Query\Field orFieldDateAdd()
 * @method \Cms\Orm\Contact\Query orderAscDateAdd()
 * @method \Cms\Orm\Contact\Query orderDescDateAdd()
 * @method \Cms\Orm\Contact\Query groupByDateAdd()
 * @method \Cms\Orm\Contact\Query\Field whereText()
 * @method \Cms\Orm\Contact\Query\Field andFieldText()
 * @method \Cms\Orm\Contact\Query\Field orFieldText()
 * @method \Cms\Orm\Contact\Query orderAscText()
 * @method \Cms\Orm\Contact\Query orderDescText()
 * @method \Cms\Orm\Contact\Query groupByText()
 * @method \Cms\Orm\Contact\Query\Field whereReply()
 * @method \Cms\Orm\Contact\Query\Field andFieldReply()
 * @method \Cms\Orm\Contact\Query\Field orFieldReply()
 * @method \Cms\Orm\Contact\Query orderAscReply()
 * @method \Cms\Orm\Contact\Query orderDescReply()
 * @method \Cms\Orm\Contact\Query groupByReply()
 * @method \Cms\Orm\Contact\Query\Field whereCmsAuthIdReply()
 * @method \Cms\Orm\Contact\Query\Field andFieldCmsAuthIdReply()
 * @method \Cms\Orm\Contact\Query\Field orFieldCmsAuthIdReply()
 * @method \Cms\Orm\Contact\Query orderAscCmsAuthIdReply()
 * @method \Cms\Orm\Contact\Query orderDescCmsAuthIdReply()
 * @method \Cms\Orm\Contact\Query groupByCmsAuthIdReply()
 * @method \Cms\Orm\Contact\Query\Field whereUri()
 * @method \Cms\Orm\Contact\Query\Field andFieldUri()
 * @method \Cms\Orm\Contact\Query\Field orFieldUri()
 * @method \Cms\Orm\Contact\Query orderAscUri()
 * @method \Cms\Orm\Contact\Query orderDescUri()
 * @method \Cms\Orm\Contact\Query groupByUri()
 * @method \Cms\Orm\Contact\Query\Field whereName()
 * @method \Cms\Orm\Contact\Query\Field andFieldName()
 * @method \Cms\Orm\Contact\Query\Field orFieldName()
 * @method \Cms\Orm\Contact\Query orderAscName()
 * @method \Cms\Orm\Contact\Query orderDescName()
 * @method \Cms\Orm\Contact\Query groupByName()
 * @method \Cms\Orm\Contact\Query\Field wherePhone()
 * @method \Cms\Orm\Contact\Query\Field andFieldPhone()
 * @method \Cms\Orm\Contact\Query\Field orFieldPhone()
 * @method \Cms\Orm\Contact\Query orderAscPhone()
 * @method \Cms\Orm\Contact\Query orderDescPhone()
 * @method \Cms\Orm\Contact\Query groupByPhone()
 * @method \Cms\Orm\Contact\Query\Field whereEmail()
 * @method \Cms\Orm\Contact\Query\Field andFieldEmail()
 * @method \Cms\Orm\Contact\Query\Field orFieldEmail()
 * @method \Cms\Orm\Contact\Query orderAscEmail()
 * @method \Cms\Orm\Contact\Query orderDescEmail()
 * @method \Cms\Orm\Contact\Query groupByEmail()
 * @method \Cms\Orm\Contact\Query\Field whereIp()
 * @method \Cms\Orm\Contact\Query\Field andFieldIp()
 * @method \Cms\Orm\Contact\Query\Field orFieldIp()
 * @method \Cms\Orm\Contact\Query orderAscIp()
 * @method \Cms\Orm\Contact\Query orderDescIp()
 * @method \Cms\Orm\Contact\Query groupByIp()
 * @method \Cms\Orm\Contact\Query\Field whereCmsAuthId()
 * @method \Cms\Orm\Contact\Query\Field andFieldCmsAuthId()
 * @method \Cms\Orm\Contact\Query\Field orFieldCmsAuthId()
 * @method \Cms\Orm\Contact\Query orderAscCmsAuthId()
 * @method \Cms\Orm\Contact\Query orderDescCmsAuthId()
 * @method \Cms\Orm\Contact\Query groupByCmsAuthId()
 * @method \Cms\Orm\Contact\Query\Field whereActive()
 * @method \Cms\Orm\Contact\Query\Field andFieldActive()
 * @method \Cms\Orm\Contact\Query\Field orFieldActive()
 * @method \Cms\Orm\Contact\Query orderAscActive()
 * @method \Cms\Orm\Contact\Query orderDescActive()
 * @method \Cms\Orm\Contact\Query groupByActive()
 * @method \Cms\Orm\Contact\Query\Field andField($fieldName, $tableName = null)
 * @method \Cms\Orm\Contact\Query\Field where($fieldName, $tableName = null)
 * @method \Cms\Orm\Contact\Query\Field orField($fieldName, $tableName = null)
 * @method \Cms\Orm\Contact\Query\Join join($tableName, $targetTableName = null)
 * @method \Cms\Orm\Contact\Query\Join joinLeft($tableName, $targetTableName = null)
 * @method \Cms\Orm\Contact\Record[] find()
 * @method \Cms\Orm\Contact\Record findFirst()
 * @method \Cms\Orm\Contact\Record findPk($value)
 */
//</editor-fold>
class Query extends \Mmi\Orm\Query {

	protected $_tableName = 'cms_contact';

	/**
	 * @return \Cms\Orm\Contact\Query
	 */
	public static function factory($daoClassName = null) {
		return new self($daoClassName);
	}

}
