<?php

namespace Cms\Orm\Contact;

/**
 * @method \Cms\Orm\Contact\Query equals($value)
 * @method \Cms\Orm\Contact\Query notEquals($value)
 * @method \Cms\Orm\Contact\Query greater($value)
 * @method \Cms\Orm\Contact\Query less($value)
 * @method \Cms\Orm\Contact\Query greaterOrEquals($value)
 * @method \Cms\Orm\Contact\Query lessOrEquals($value)
 * @method \Cms\Orm\Contact\Query like($value)
 * @method \Cms\Orm\Contact\Query ilike($value)
 * @method \Cms\Orm\Contact\Query equalsColumnId()
 * @method \Cms\Orm\Contact\Query notEqualsColumnId()
 * @method \Cms\Orm\Contact\Query greaterThanColumnId()
 * @method \Cms\Orm\Contact\Query lessThanColumnId()
 * @method \Cms\Orm\Contact\Query greaterOrEqualsColumnId()
 * @method \Cms\Orm\Contact\Query lessOrEqualsColumnId()
 * @method \Cms\Orm\Contact\Query equalsColumnCmsContactOptionId()
 * @method \Cms\Orm\Contact\Query notEqualsColumnCmsContactOptionId()
 * @method \Cms\Orm\Contact\Query greaterThanColumnCmsContactOptionId()
 * @method \Cms\Orm\Contact\Query lessThanColumnCmsContactOptionId()
 * @method \Cms\Orm\Contact\Query greaterOrEqualsColumnCmsContactOptionId()
 * @method \Cms\Orm\Contact\Query lessOrEqualsColumnCmsContactOptionId()
 * @method \Cms\Orm\Contact\Query equalsColumnDateAdd()
 * @method \Cms\Orm\Contact\Query notEqualsColumnDateAdd()
 * @method \Cms\Orm\Contact\Query greaterThanColumnDateAdd()
 * @method \Cms\Orm\Contact\Query lessThanColumnDateAdd()
 * @method \Cms\Orm\Contact\Query greaterOrEqualsColumnDateAdd()
 * @method \Cms\Orm\Contact\Query lessOrEqualsColumnDateAdd()
 * @method \Cms\Orm\Contact\Query equalsColumnText()
 * @method \Cms\Orm\Contact\Query notEqualsColumnText()
 * @method \Cms\Orm\Contact\Query greaterThanColumnText()
 * @method \Cms\Orm\Contact\Query lessThanColumnText()
 * @method \Cms\Orm\Contact\Query greaterOrEqualsColumnText()
 * @method \Cms\Orm\Contact\Query lessOrEqualsColumnText()
 * @method \Cms\Orm\Contact\Query equalsColumnReply()
 * @method \Cms\Orm\Contact\Query notEqualsColumnReply()
 * @method \Cms\Orm\Contact\Query greaterThanColumnReply()
 * @method \Cms\Orm\Contact\Query lessThanColumnReply()
 * @method \Cms\Orm\Contact\Query greaterOrEqualsColumnReply()
 * @method \Cms\Orm\Contact\Query lessOrEqualsColumnReply()
 * @method \Cms\Orm\Contact\Query equalsColumnCmsAuthIdReply()
 * @method \Cms\Orm\Contact\Query notEqualsColumnCmsAuthIdReply()
 * @method \Cms\Orm\Contact\Query greaterThanColumnCmsAuthIdReply()
 * @method \Cms\Orm\Contact\Query lessThanColumnCmsAuthIdReply()
 * @method \Cms\Orm\Contact\Query greaterOrEqualsColumnCmsAuthIdReply()
 * @method \Cms\Orm\Contact\Query lessOrEqualsColumnCmsAuthIdReply()
 * @method \Cms\Orm\Contact\Query equalsColumnUri()
 * @method \Cms\Orm\Contact\Query notEqualsColumnUri()
 * @method \Cms\Orm\Contact\Query greaterThanColumnUri()
 * @method \Cms\Orm\Contact\Query lessThanColumnUri()
 * @method \Cms\Orm\Contact\Query greaterOrEqualsColumnUri()
 * @method \Cms\Orm\Contact\Query lessOrEqualsColumnUri()
 * @method \Cms\Orm\Contact\Query equalsColumnName()
 * @method \Cms\Orm\Contact\Query notEqualsColumnName()
 * @method \Cms\Orm\Contact\Query greaterThanColumnName()
 * @method \Cms\Orm\Contact\Query lessThanColumnName()
 * @method \Cms\Orm\Contact\Query greaterOrEqualsColumnName()
 * @method \Cms\Orm\Contact\Query lessOrEqualsColumnName()
 * @method \Cms\Orm\Contact\Query equalsColumnPhone()
 * @method \Cms\Orm\Contact\Query notEqualsColumnPhone()
 * @method \Cms\Orm\Contact\Query greaterThanColumnPhone()
 * @method \Cms\Orm\Contact\Query lessThanColumnPhone()
 * @method \Cms\Orm\Contact\Query greaterOrEqualsColumnPhone()
 * @method \Cms\Orm\Contact\Query lessOrEqualsColumnPhone()
 * @method \Cms\Orm\Contact\Query equalsColumnEmail()
 * @method \Cms\Orm\Contact\Query notEqualsColumnEmail()
 * @method \Cms\Orm\Contact\Query greaterThanColumnEmail()
 * @method \Cms\Orm\Contact\Query lessThanColumnEmail()
 * @method \Cms\Orm\Contact\Query greaterOrEqualsColumnEmail()
 * @method \Cms\Orm\Contact\Query lessOrEqualsColumnEmail()
 * @method \Cms\Orm\Contact\Query equalsColumnIp()
 * @method \Cms\Orm\Contact\Query notEqualsColumnIp()
 * @method \Cms\Orm\Contact\Query greaterThanColumnIp()
 * @method \Cms\Orm\Contact\Query lessThanColumnIp()
 * @method \Cms\Orm\Contact\Query greaterOrEqualsColumnIp()
 * @method \Cms\Orm\Contact\Query lessOrEqualsColumnIp()
 * @method \Cms\Orm\Contact\Query equalsColumnCmsAuthId()
 * @method \Cms\Orm\Contact\Query notEqualsColumnCmsAuthId()
 * @method \Cms\Orm\Contact\Query greaterThanColumnCmsAuthId()
 * @method \Cms\Orm\Contact\Query lessThanColumnCmsAuthId()
 * @method \Cms\Orm\Contact\Query greaterOrEqualsColumnCmsAuthId()
 * @method \Cms\Orm\Contact\Query lessOrEqualsColumnCmsAuthId()
 * @method \Cms\Orm\Contact\Query equalsColumnActive()
 * @method \Cms\Orm\Contact\Query notEqualsColumnActive()
 * @method \Cms\Orm\Contact\Query greaterThanColumnActive()
 * @method \Cms\Orm\Contact\Query lessThanColumnActive()
 * @method \Cms\Orm\Contact\Query greaterOrEqualsColumnActive()
 * @method \Cms\Orm\Contact\Query lessOrEqualsColumnActive()
 */
class QueryField extends \Mmi\Orm\QueryField {

}
