name: "Code analysis and tests"
on:
  pull_request:
  push:
jobs:
  mmi-build-toolkit:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v3
    - name: Build docker image
      run: docker build -t mmi-cms .
    - name: Run tests
      run: docker run mmi-cms composer test:phpunit