name: "Code analysis and checks"

on:

  pull_request:
  push:

jobs:

  php8-checks:
    strategy:
      matrix:
        version: ['8.1', '8.2']
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Build docker image
      uses: docker/build-push-action@v5
      with:
        push: false
        tags: php${{ matrix.version }}-checks
        build-args: PHP_VERSION=${{ matrix.version }}
    - name: Run tests
      run: docker run php${{ matrix.version }}-checks composer test:all