name: "Code analysis and checks"

on:

  pull_request:
  push:

jobs:

  php81-checks:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Build docker image
      uses: docker/build-push-action@v5
      with:
        push: false
        tags: php81-checks
        build-args: PHP_VERSION=8.1
    - name: Run tests
      run: docker run php81-checks sh -c "composer install && composer test:all"

  php82-checks:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Build docker image
      uses: docker/build-push-action@v5
      with:
        push: false
        tags: php82-checks
    - name: Run tests
      run: docker run php82-checks sh -c "composer install && composer test:all"