name: "Code analysis and tests"
on:
  pull_request:
  push:
jobs:
  mmi-build-toolkit:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Build docker image
      uses: docker/build-push-action@v5
      with:
        push: false
        tags: mmi-cms:latest
    - name: Run tests
      run: docker run mmi-cms composer test:phpunit