name: "Code analysis and tests using PHP 8.2"
on:
  pull_request:
  push:
jobs:
  php82-testing:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Build docker image
      uses: docker/build-push-action@v5
      with:
        push: false
        tags: mmi-cms:latest
    - name: Run tests      
      run: docker run mmi-cms composer test:phpunit