<?php

namespace Cms\Orm\Stat\Date;

/**
 * @method \Cms\Orm\Stat\Date\Query equals($value)
 * @method \Cms\Orm\Stat\Date\Query notEquals($value)
 * @method \Cms\Orm\Stat\Date\Query greater($value)
 * @method \Cms\Orm\Stat\Date\Query less($value)
 * @method \Cms\Orm\Stat\Date\Query greaterOrEquals($value)
 * @method \Cms\Orm\Stat\Date\Query lessOrEquals($value)
 * @method \Cms\Orm\Stat\Date\Query like($value)
 * @method \Cms\Orm\Stat\Date\Query ilike($value)
 * @method \Cms\Orm\Stat\Date\Query equalsColumnId()
 * @method \Cms\Orm\Stat\Date\Query notEqualsColumnId()
 * @method \Cms\Orm\Stat\Date\Query greaterThanColumnId()
 * @method \Cms\Orm\Stat\Date\Query lessThanColumnId()
 * @method \Cms\Orm\Stat\Date\Query greaterOrEqualsColumnId()
 * @method \Cms\Orm\Stat\Date\Query lessOrEqualsColumnId()
 * @method \Cms\Orm\Stat\Date\Query equalsColumnHour()
 * @method \Cms\Orm\Stat\Date\Query notEqualsColumnHour()
 * @method \Cms\Orm\Stat\Date\Query greaterThanColumnHour()
 * @method \Cms\Orm\Stat\Date\Query lessThanColumnHour()
 * @method \Cms\Orm\Stat\Date\Query greaterOrEqualsColumnHour()
 * @method \Cms\Orm\Stat\Date\Query lessOrEqualsColumnHour()
 * @method \Cms\Orm\Stat\Date\Query equalsColumnDay()
 * @method \Cms\Orm\Stat\Date\Query notEqualsColumnDay()
 * @method \Cms\Orm\Stat\Date\Query greaterThanColumnDay()
 * @method \Cms\Orm\Stat\Date\Query lessThanColumnDay()
 * @method \Cms\Orm\Stat\Date\Query greaterOrEqualsColumnDay()
 * @method \Cms\Orm\Stat\Date\Query lessOrEqualsColumnDay()
 * @method \Cms\Orm\Stat\Date\Query equalsColumnMonth()
 * @method \Cms\Orm\Stat\Date\Query notEqualsColumnMonth()
 * @method \Cms\Orm\Stat\Date\Query greaterThanColumnMonth()
 * @method \Cms\Orm\Stat\Date\Query lessThanColumnMonth()
 * @method \Cms\Orm\Stat\Date\Query greaterOrEqualsColumnMonth()
 * @method \Cms\Orm\Stat\Date\Query lessOrEqualsColumnMonth()
 * @method \Cms\Orm\Stat\Date\Query equalsColumnYear()
 * @method \Cms\Orm\Stat\Date\Query notEqualsColumnYear()
 * @method \Cms\Orm\Stat\Date\Query greaterThanColumnYear()
 * @method \Cms\Orm\Stat\Date\Query lessThanColumnYear()
 * @method \Cms\Orm\Stat\Date\Query greaterOrEqualsColumnYear()
 * @method \Cms\Orm\Stat\Date\Query lessOrEqualsColumnYear()
 * @method \Cms\Orm\Stat\Date\Query equalsColumnObject()
 * @method \Cms\Orm\Stat\Date\Query notEqualsColumnObject()
 * @method \Cms\Orm\Stat\Date\Query greaterThanColumnObject()
 * @method \Cms\Orm\Stat\Date\Query lessThanColumnObject()
 * @method \Cms\Orm\Stat\Date\Query greaterOrEqualsColumnObject()
 * @method \Cms\Orm\Stat\Date\Query lessOrEqualsColumnObject()
 * @method \Cms\Orm\Stat\Date\Query equalsColumnObjectId()
 * @method \Cms\Orm\Stat\Date\Query notEqualsColumnObjectId()
 * @method \Cms\Orm\Stat\Date\Query greaterThanColumnObjectId()
 * @method \Cms\Orm\Stat\Date\Query lessThanColumnObjectId()
 * @method \Cms\Orm\Stat\Date\Query greaterOrEqualsColumnObjectId()
 * @method \Cms\Orm\Stat\Date\Query lessOrEqualsColumnObjectId()
 * @method \Cms\Orm\Stat\Date\Query equalsColumnCount()
 * @method \Cms\Orm\Stat\Date\Query notEqualsColumnCount()
 * @method \Cms\Orm\Stat\Date\Query greaterThanColumnCount()
 * @method \Cms\Orm\Stat\Date\Query lessThanColumnCount()
 * @method \Cms\Orm\Stat\Date\Query greaterOrEqualsColumnCount()
 * @method \Cms\Orm\Stat\Date\Query lessOrEqualsColumnCount()
 */
class QueryField extends \Mmi\Orm\QueryField {

}
